// Code generated by command: go run asm_vpsravd_128.go -out ../asm_vpsravd_128.s -stubs ../stub_vpsravd_128.go -pkg vpsravd. DO NOT EDIT.

#include "textflag.h"

// func vpsravd128(vals *[4]int32, shifts *[4]uint32, ret *[4]int32)
// Requires: AVX, AVX2
TEXT ·vpsravd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPSRAVD: arithmetic right shift packed doubleword integers by variable counts
	VPSRAVD X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
