// Code generated by command: go run asm_vpsravd_256.go -out ../asm_vpsravd_256.s -stubs ../stub_vpsravd_256.go -pkg vpsravd. DO NOT EDIT.

#include "textflag.h"

// func vpsravd256(vals *[8]int32, shifts *[8]uint32, ret *[8]int32)
// Requires: AVX, AVX2
TEXT ·vpsravd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSRAVD: arithmetic right shift packed doubleword integers by variable counts
	VPSRAVD Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
