// Code generated by command: go run asm_vpsravd_256.go -out ../asm_vpsravd_256.s -stubs ../stub_vpsravd_256.go -pkg vpsravd. DO NOT EDIT.

package vpsravd

func vpsravd256(vals *[8]int32, shifts *[8]uint32, ret *[8]int32)
