// Code generated by command: go run asm_vpsravd_128.go -out ../asm_vpsravd_128.s -stubs ../stub_vpsravd_128.go -pkg vpsravd. DO NOT EDIT.

package vpsravd

func vpsravd128(vals *[4]int32, shifts *[4]uint32, ret *[4]int32)
