// Code generated by command: go run asm_vpmovsxbd_128.go -out ../asm_vpmovsxbd_128.s -stubs ../stub_vpmovsxbd_128.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxbd128(vals *[16]int8, ret *[4]int32)
// Requires: AVX
TEXT ·vpmovsxbd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXBD X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
