// Code generated by command: go run asm_vpmovsxbw_256.go -out ../asm_vpmovsxbw_256.s -stubs ../stub_vpmovsxbw_256.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxbw256(vals *[16]int8, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpmovsxbw256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXBW X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
