// Code generated by command: go run asm_vpmovsxdq_256.go -out ../asm_vpmovsxdq_256.s -stubs ../stub_vpmovsxdq_256.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxdq256(vals *[4]int32, ret *[4]int64)
// Requires: AVX, AVX2
TEXT ·vpmovsxdq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXDQ X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
