// Code generated by command: go run asm_vpmovsxbq_256.go -out ../asm_vpmovsxbq_256.s -stubs ../stub_vpmovsxbq_256.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxbq256(vals *[16]int8, ret *[4]int64)
// Requires: AVX, AVX2
TEXT ·vpmovsxbq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXBQ X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
