// Code generated by command: go run asm_vpmovsxwd_256.go -out ../asm_vpmovsxwd_256.s -stubs ../stub_vpmovsxwd_256.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxwd256(vals *[8]int16, ret *[8]int32)
// Requires: AVX, AVX2
TEXT ·vpmovsxwd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXWD X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
