// Code generated by command: go run asm_vpmovsxbq_128.go -out ../asm_vpmovsxbq_128.s -stubs ../stub_vpmovsxbq_128.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxbq128(vals *[16]int8, ret *[2]int64)
// Requires: AVX
TEXT ·vpmovsxbq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXBQ X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
