// Code generated by command: go run asm_vpmovsxwq_128.go -out ../asm_vpmovsxwq_128.s -stubs ../stub_vpmovsxwq_128.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxwq128(vals *[8]int16, ret *[2]int64)
// Requires: AVX
TEXT ·vpmovsxwq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXWQ X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
