// Code generated by command: go run asm_vpmovsxdq_128.go -out ../asm_vpmovsxdq_128.s -stubs ../stub_vpmovsxdq_128.go -pkg vpmovsx. DO NOT EDIT.

#include "textflag.h"

// func vpmovsxdq128(vals *[4]int32, ret *[2]int64)
// Requires: AVX
TEXT ·vpmovsxdq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVSXDQ X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
