// Code generated by command: go run asm_vpmovsxbw_256.go -out ../asm_vpmovsxbw_256.s -stubs ../stub_vpmovsxbw_256.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbw256(vals *[16]int8, ret *[16]int16)
