// Code generated by command: go run asm_vpmovsxbq_256.go -out ../asm_vpmovsxbq_256.s -stubs ../stub_vpmovsxbq_256.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbq256(vals *[16]int8, ret *[4]int64)
