// Code generated by command: go run asm_vpmovsxbw_128.go -out ../asm_vpmovsxbw_128.s -stubs ../stub_vpmovsxbw_128.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbw128(vals *[16]int8, ret *[8]int16)
