// Code generated by command: go run asm_vpmovsxbq_128.go -out ../asm_vpmovsxbq_128.s -stubs ../stub_vpmovsxbq_128.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbq128(vals *[16]int8, ret *[2]int64)
