// Code generated by command: go run asm_vpmovsxbd_128.go -out ../asm_vpmovsxbd_128.s -stubs ../stub_vpmovsxbd_128.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbd128(vals *[16]int8, ret *[4]int32)
