// Code generated by command: go run asm_vpmovsxbd_256.go -out ../asm_vpmovsxbd_256.s -stubs ../stub_vpmovsxbd_256.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxbd256(vals *[16]int8, ret *[8]int32)
