// Code generated by command: go run asm_vpmovsxwd_128.go -out ../asm_vpmovsxwd_128.s -stubs ../stub_vpmovsxwd_128.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxwd128(vals *[8]int16, ret *[4]int32)
