// Code generated by command: go run asm_vpmovsxwq_256.go -out ../asm_vpmovsxwq_256.s -stubs ../stub_vpmovsxwq_256.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxwq256(vals *[8]int16, ret *[4]int64)
