// Code generated by command: go run asm_vpmovsxdq_128.go -out ../asm_vpmovsxdq_128.s -stubs ../stub_vpmovsxdq_128.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxdq128(vals *[4]int32, ret *[2]int64)
