// Code generated by command: go run asm_vpmovsxdq_256.go -out ../asm_vpmovsxdq_256.s -stubs ../stub_vpmovsxdq_256.go -pkg vpmovsx. DO NOT EDIT.

package vpmovsx

func vpmovsxdq256(vals *[4]int32, ret *[4]int64)
