// Code generated by command: go run asm_vsqrtss_128.go -out ../asm_vsqrtss_128.s -stubs ../stub_vsqrtss_128.go -pkg sqrtss. DO NOT EDIT.

#include "textflag.h"

// func vsqrtss128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vsqrtss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute square root of scalar single precision value using VEX encoding
	VSQRTSS X0, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
