// Code generated by command: go run asm_sqrtss_128.go -out ../asm_sqrtss_128.s -stubs ../stub_sqrtss_128.go -pkg sqrtss. DO NOT EDIT.

package sqrtss

func sqrtss128(vals *[4]float32, ret *[4]float32)
