// Code generated by command: go run asm_vsqrtss_128.go -out ../asm_vsqrtss_128.s -stubs ../stub_vsqrtss_128.go -pkg sqrtss. DO NOT EDIT.

package sqrtss

func vsqrtss128(vals *[4]float32, ret *[4]float32)
