// Code generated by command: go run asm_subss_128.go -out ../asm_subss_128.s -stubs ../stub_subss_128.go -pkg subss. DO NOT EDIT.

package subss

func subss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
