// Code generated by command: go run asm_vbroadcasti128_256.go -out ../asm_vbroadcasti128_256.s -stubs ../stub_vbroadcasti128_256.go -pkg vbroadcasti128. DO NOT EDIT.

#include "textflag.h"

// func vbroadcasti128256(vals *[2]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vbroadcasti128256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Broadcast 128-bit valss from memory into both 128-bit lanes of YMM
	VBROADCASTI128 (AX), Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER
	RET
