// Code generated by command: go run asm_vbroadcasti128_256.go -out ../asm_vbroadcasti128_256.s -stubs ../stub_vbroadcasti128_256.go -pkg vbroadcasti128. DO NOT EDIT.

package vbroadcasti128

func vbroadcasti128256(vals *[2]uint64, ret *[4]uint64)
