// Code generated by command: go run asm_vpabsd_128.go -out ../asm_vpabsd_128.s -stubs ../stub_vpabsd_128.go -pkg vpabs. DO NOT EDIT.

#include "textflag.h"

// func vpabsd128(vals *[4]int32, ret *[4]int32)
// Requires: AVX
TEXT ·vpabsd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPABSD X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
