// Code generated by command: go run asm_vpabsb_128.go -out ../asm_vpabsb_128.s -stubs ../stub_vpabsb_128.go -pkg vpabs. DO NOT EDIT.

#include "textflag.h"

// func vpabsb128(vals *[16]int8, ret *[16]int8)
// Requires: AVX
TEXT ·vpabsb128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPABSB X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
