// Code generated by command: go run asm_vpabsd_256.go -out ../asm_vpabsd_256.s -stubs ../stub_vpabsd_256.go -pkg vpabs. DO NOT EDIT.

#include "textflag.h"

// func vpabsd256(vals *[8]int32, ret *[8]int32)
// Requires: AVX, AVX2
TEXT ·vpabsd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Execute the instruction being demonstrated
	VPABSD Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
