// Code generated by command: go run asm_unpcklps_128.go -out ../asm_unpcklps_128.s -stubs ../stub_unpcklps_128.go -pkg unpcklps. DO NOT EDIT.

package unpcklps

func unpcklps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
