// Code generated by command: go run asm_vunpcklps_256.go -out ../asm_vunpcklps_256.s -stubs ../stub_vunpcklps_256.go -pkg unpcklps. DO NOT EDIT.

package unpcklps

func vunpcklps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
