// Code generated by command: go run asm_cmpps_128_lt.go -out ../asm_cmpps_128_lt.s -stubs ../stub_cmpps_128_lt.go -pkg cmpps. DO NOT EDIT.

#include "textflag.h"

// func cmpps128Lt(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·cmpps128Lt(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Compare packed single-precision: LT (imm8=1)
	CMPPS X1, X0, $0x01

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
