// Code generated by command: go run asm_cmpps_128_unord.go -out ../asm_cmpps_128_unord.s -stubs ../stub_cmpps_128_unord.go -pkg cmpps. DO NOT EDIT.

package cmpps

func cmpps128Unord(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
