// Code generated by command: go run asm_vblendvpw_256.go -out ../asm_vblendvpw_256.s -stubs ../stub_vblendvpw_256.go -pkg blendvpw. DO NOT EDIT.

#include "textflag.h"

// func vblendvpw256(base *[16]uint16, blend *[16]uint16, mask *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vblendvpw256(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend, and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1
	VMOVDQA (DX), Y2

	// VPBLENDVB: variable blend using per-byte sign bits of mask
	VPBLENDVB Y2, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
