// Code generated by command: go run asm_vblendvpw_128.go -out ../asm_vblendvpw_128.s -stubs ../stub_vblendvpw_128.go -pkg blendvpw. DO NOT EDIT.

#include "textflag.h"

// func vblendvpw128(base *[8]uint16, blend *[8]uint16, mask *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vblendvpw128(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend, and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1
	VMOVDQA (DX), X2

	// VPBLENDVB: variable blend using per-byte sign bits of mask
	VPBLENDVB X2, X1, X0, X0

	// Store result
	VMOVDQA X0, (BX)

	// Return from function
	RET
