// Code generated by command: go run asm_vblendvpw_128.go -out ../asm_vblendvpw_128.s -stubs ../stub_vblendvpw_128.go -pkg blendvpw. DO NOT EDIT.

package blendvpw

func vblendvpw128(base *[8]uint16, blend *[8]uint16, mask *[8]uint16, ret *[8]uint16)
