// Code generated by command: go run asm_vblendvpw_256.go -out ../asm_vblendvpw_256.s -stubs ../stub_vblendvpw_256.go -pkg blendvpw. DO NOT EDIT.

package blendvpw

func vblendvpw256(base *[16]uint16, blend *[16]uint16, mask *[16]uint16, ret *[16]uint16)
