// Code generated by command: go run asm_vshufps_256_threes.go -out ../asm_vshufps_256_threes.s -stubs ../stub_vshufps_256_threes.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps256Threes(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vshufps256Threes(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// VSHUFPS imm8=0xFF (1111_1111b) per 128-bit lane: dst = [a3,a3,b3,b3 | a7,a7,b7,b7]
	VSHUFPS $0xff, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
