// Code generated by command: go run asm_vshufps_256_ones.go -out ../asm_vshufps_256_ones.s -stubs ../stub_vshufps_256_ones.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps256Ones(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vshufps256Ones(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// VSHUFPS imm8=0x55 (0101_0101b) per 128-bit lane: dst = [a1,a1,b1,b1 | a5,a5,b5,b5]
	VSHUFPS $0x55, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
