// Code generated by command: go run asm_vshufps_256_mixed.go -out ../asm_vshufps_256_mixed.s -stubs ../stub_vshufps_256_mixed.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps256Mixed(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vshufps256Mixed(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// VSHUFPS imm8=0xE4 (1110_0100b) per 128-bit lane: dst = [a0,a1,b2,b3 | a4,a5,b6,b7]
	VSHUFPS $0xe4, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
