// Code generated by command: go run asm_vshufps_128_twos.go -out ../asm_vshufps_128_twos.s -stubs ../stub_vshufps_128_twos.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps128Twos(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vshufps128Twos(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// VSHUFPS imm8=0xAA (1010_1010b): dst = [a2,a2,b2,b2]
	VSHUFPS $0xaa, X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
