// Code generated by command: go run asm_vshufps_256_zeros.go -out ../asm_vshufps_256_zeros.s -stubs ../stub_vshufps_256_zeros.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps256Zeros(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vshufps256Zeros(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// VSHUFPS imm8=0x00 (0000_0000b) per 128-bit lane: dst = [a0,a0,b0,b0 | a4,a4,b4,b4]
	VSHUFPS $0x00, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER
	RET
