// Code generated by command: go run asm_shufps_128_zeros.go -out ../asm_shufps_128_zeros.s -stubs ../stub_shufps_128_zeros.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func shufps128Zeros(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·shufps128Zeros(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// SHUFPS imm8=0x00 (0000_0000b): dst = [a0,a0,b0,b0]
	SHUFPS $0x00, X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
