// Code generated by command: go run asm_vshufps_256_twos.go -out ../asm_vshufps_256_twos.s -stubs ../stub_vshufps_256_twos.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func vshufps256Twos(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vshufps256Twos(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// VSHUFPS imm8=0xAA (1010_1010b) per 128-bit lane: dst = [a2,a2,b2,b2 | a6,a6,b6,b6]
	VSHUFPS $0xaa, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
