// Code generated by command: go run asm_shufps_128_ones.go -out ../asm_shufps_128_ones.s -stubs ../stub_shufps_128_ones.go -pkg shufps. DO NOT EDIT.

#include "textflag.h"

// func shufps128Ones(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·shufps128Ones(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// SHUFPS imm8=0x55 (0101_0101b): dst = [a1,a1,b1,b1]
	SHUFPS $0x55, X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
