// Code generated by command: go run asm_vshufps_256_threes.go -out ../asm_vshufps_256_threes.s -stubs ../stub_vshufps_256_threes.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps256Threes(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
