// Code generated by command: go run asm_vshufps_256_ones.go -out ../asm_vshufps_256_ones.s -stubs ../stub_vshufps_256_ones.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps256Ones(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
