// Code generated by command: go run asm_shufps_128_zeros.go -out ../asm_shufps_128_zeros.s -stubs ../stub_shufps_128_zeros.go -pkg shufps. DO NOT EDIT.

package shufps

func shufps128Zeros(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
