// Code generated by command: go run asm_shufps_128_mixed.go -out ../asm_shufps_128_mixed.s -stubs ../stub_shufps_128_mixed.go -pkg shufps. DO NOT EDIT.

package shufps

func shufps128Mixed(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
