// Code generated by command: go run asm_shufps_128_ones.go -out ../asm_shufps_128_ones.s -stubs ../stub_shufps_128_ones.go -pkg shufps. DO NOT EDIT.

package shufps

func shufps128Ones(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
