// Code generated by command: go run asm_vshufps_128_reverse.go -out ../asm_vshufps_128_reverse.s -stubs ../stub_vshufps_128_reverse.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps128Reverse(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
