// Code generated by command: go run asm_shufps_128_reverse.go -out ../asm_shufps_128_reverse.s -stubs ../stub_shufps_128_reverse.go -pkg shufps. DO NOT EDIT.

package shufps

func shufps128Reverse(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
