// Code generated by command: go run asm_vshufps_256_zeros.go -out ../asm_vshufps_256_zeros.s -stubs ../stub_vshufps_256_zeros.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps256Zeros(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
