// Code generated by command: go run asm_vshufps_128_threes.go -out ../asm_vshufps_128_threes.s -stubs ../stub_vshufps_128_threes.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps128Threes(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
