// Code generated by command: go run asm_shufps_128_twos.go -out ../asm_shufps_128_twos.s -stubs ../stub_shufps_128_twos.go -pkg shufps. DO NOT EDIT.

package shufps

func shufps128Twos(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
