// Code generated by command: go run asm_vshufps_128_mixed.go -out ../asm_vshufps_128_mixed.s -stubs ../stub_vshufps_128_mixed.go -pkg shufps. DO NOT EDIT.

package shufps

func vshufps128Mixed(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
