// Code generated by command: go run asm_vpsadbw_128.go -out ../asm_vpsadbw_128.s -stubs ../stub_vpsadbw_128.go -pkg psadbw. DO NOT EDIT.

#include "textflag.h"

// func vpsadbw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[8]uint16)
// Requires: AVX
TEXT ·vpsadbw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Sum of absolute differences of packed unsigned bytes with VEX (per 64-bit lane)
	VPSADBW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
