// Code generated by command: go run asm_psadbw_128.go -out ../asm_psadbw_128.s -stubs ../stub_psadbw_128.go -pkg psadbw. DO NOT EDIT.

#include "textflag.h"

// func psadbw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[8]uint16)
// Requires: AVX, SSE2
TEXT ·psadbw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Sum of absolute differences of packed unsigned bytes (per 64-bit lane)
	PSADBW X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
