// Code generated by command: go run asm_psadbw_128.go -out ../asm_psadbw_128.s -stubs ../stub_psadbw_128.go -pkg psadbw. DO NOT EDIT.

package psadbw

func psadbw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[8]uint16)
