// Code generated by command: go run asm_vpsadbw_256.go -out ../asm_vpsadbw_256.s -stubs ../stub_vpsadbw_256.go -pkg psadbw. DO NOT EDIT.

package psadbw

func vpsadbw256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[16]uint16)
