// Code generated by command: go run asm_vpsadbw_128.go -out ../asm_vpsadbw_128.s -stubs ../stub_vpsadbw_128.go -pkg psadbw. DO NOT EDIT.

package psadbw

func vpsadbw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[8]uint16)
