// Code generated by command: go run asm_vpsignw_256.go -out ../asm_vpsignw_256.s -stubs ../stub_vpsignw_256.go -pkg vpsign. DO NOT EDIT.

#include "textflag.h"

// func vpsignw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpsignw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load vals2 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VPSIGNW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
