// Code generated by command: go run asm_vpsignd_128.go -out ../asm_vpsignd_128.s -stubs ../stub_vpsignd_128.go -pkg vpsign. DO NOT EDIT.

#include "textflag.h"

// func vpsignd128(vals1 *[4]int32, vals2 *[4]int32, ret *[4]int32)
// Requires: AVX
TEXT ·vpsignd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQU (AX), X0

	// Load vals2 into XMM register
	VMOVDQU (CX), X1

	// Execute the instruction being demonstrated
	VPSIGND X0, X1, X0

	// Write results into return memory address
	VMOVDQU X0, (DX)

	// Return from function
	RET
