// Code generated by command: go run asm_vpsignb_128.go -out ../asm_vpsignb_128.s -stubs ../stub_vpsignb_128.go -pkg vpsign. DO NOT EDIT.

package vpsign

func vpsignb128(vals1 *[16]int8, vals2 *[16]int8, ret *[16]int8)
