// Code generated by command: go run asm_vpsignw_128.go -out ../asm_vpsignw_128.s -stubs ../stub_vpsignw_128.go -pkg vpsign. DO NOT EDIT.

package vpsign

func vpsignw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
