// Code generated by command: go run asm_vpsignw_256.go -out ../asm_vpsignw_256.s -stubs ../stub_vpsignw_256.go -pkg vpsign. DO NOT EDIT.

package vpsign

func vpsignw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
