// Code generated by command: go run asm_vpsignd_256.go -out ../asm_vpsignd_256.s -stubs ../stub_vpsignd_256.go -pkg vpsign. DO NOT EDIT.

package vpsign

func vpsignd256(vals1 *[8]int32, vals2 *[8]int32, ret *[8]int32)
