// Code generated by command: go run asm_vpsignb_256.go -out ../asm_vpsignb_256.s -stubs ../stub_vpsignb_256.go -pkg vpsign. DO NOT EDIT.

package vpsign

func vpsignb256(vals1 *[32]int8, vals2 *[32]int8, ret *[32]int8)
