// Code generated by command: go run asm_vpmaskmovq_128.go -out ../asm_vpmaskmovq_128.s -stubs ../stub_vpmaskmovq_128.go -pkg vpmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vpmaskmovq128(vals *[2]uint64, mask *[2]uint64, ret *[2]uint64)
// Requires: AVX, AVX2
TEXT ·vpmaskmovq128(SB), NOSPLIT, $0-24
	// Load parameters
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source (vals) and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Masked store of packed qwords: store elements where mask sign-bit is set
	VPMASKMOVQ X0, X1, (DX)

	// Return
	RET
