// Code generated by command: go run asm_vpmaskmovq_256.go -out ../asm_vpmaskmovq_256.s -stubs ../stub_vpmaskmovq_256.go -pkg vpmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vpmaskmovq256(vals *[4]uint64, mask *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpmaskmovq256(SB), NOSPLIT, $0-24
	// Load parameters
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source (vals) and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Masked store of packed qwords: store elements where mask sign-bit is set
	VPMASKMOVQ Y0, Y1, (DX)

	// Clear upper halves for AVX->SSE transition
	VZEROUPPER

	// Return
	RET
