// Code generated by command: go run asm_vpmaskmovd_128.go -out ../asm_vpmaskmovd_128.s -stubs ../stub_vpmaskmovd_128.go -pkg vpmaskmov. DO NOT EDIT.

package vpmaskmov

func vpmaskmovd128(vals *[4]uint32, mask *[4]uint32, ret *[4]uint32)
