// Code generated by command: go run asm_vpmaskmovq_256.go -out ../asm_vpmaskmovq_256.s -stubs ../stub_vpmaskmovq_256.go -pkg vpmaskmov. DO NOT EDIT.

package vpmaskmov

func vpmaskmovq256(vals *[4]uint64, mask *[4]uint64, ret *[4]uint64)
