// Code generated by command: go run asm_vpmaskmovd_256.go -out ../asm_vpmaskmovd_256.s -stubs ../stub_vpmaskmovd_256.go -pkg vpmaskmov. DO NOT EDIT.

package vpmaskmov

func vpmaskmovd256(vals *[8]uint32, mask *[8]uint32, ret *[8]uint32)
