// Code generated by command: go run asm_vpmaskmovq_128.go -out ../asm_vpmaskmovq_128.s -stubs ../stub_vpmaskmovq_128.go -pkg vpmaskmov. DO NOT EDIT.

package vpmaskmov

func vpmaskmovq128(vals *[2]uint64, mask *[2]uint64, ret *[2]uint64)
