// Code generated by command: go run asm_vmovlhps_64.go -out ../asm_vmovlhps_64.s -stubs ../stub_vmovlhps_64.go -pkg movlhps. DO NOT EDIT.

#include "textflag.h"

// func vmovlhps64(vals *[2]float32, ret *[2]float32)
// Requires: AVX, SSE
TEXT ·vmovlhps64(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into lower half of XMM register
	MOVLPS (AX), X0

	// Move lower half of XMM register into upper half of another register
	VMOVLHPS X0, X1, X1

	// Write upper half of XMM register into return memory address
	MOVHPS X1, (CX)

	// Return from function
	RET
