// Code generated by command: go run asm_movlhps_64.go -out ../asm_movlhps_64.s -stubs ../stub_movlhps_64.go -pkg movlhps. DO NOT EDIT.

package movlhps

func movlhps64(vals *[2]float32, ret *[2]float32)
