// Code generated by command: go run asm_vmovlhps_64.go -out ../asm_vmovlhps_64.s -stubs ../stub_vmovlhps_64.go -pkg movlhps. DO NOT EDIT.

package movlhps

func vmovlhps64(vals *[2]float32, ret *[2]float32)
