// Code generated by command: go run asm_vpbroadcastw_256.go -out ../asm_vpbroadcastw_256.s -stubs ../stub_vpbroadcastw_256.go -pkg vpbroadcastw. DO NOT EDIT.

package vpbroadcastw

func vpbroadcastw256(w uint16, ret *[16]uint16)
