// Code generated by command: go run asm_vpbroadcastw_128.go -out ../asm_vpbroadcastw_128.s -stubs ../stub_vpbroadcastw_128.go -pkg vpbroadcastw. DO NOT EDIT.

package vpbroadcastw

func vpbroadcastw128(w uint16, ret *[8]uint16)
