// Code generated by command: go run asm_vpgatherqq_256.go -out ../asm_vpgatherqq_256.s -stubs ../stub_vpgatherqq_256.go -pkg vpgatherqq. DO NOT EDIT.

#include "textflag.h"

// func vpgatherqq256(base *[8]uint64, index *[4]uint64, mask *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpgatherqq256(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 64-bit indices into YMM register (lower 4 qwords used)
	VMOVDQA (CX), Y0

	// Load mask into YMM register (MSB of each qword lane used)
	VMOVDQA (DX), Y1

	// Load destination/src vector
	VMOVDQA (BX), Y2

	// Gather using 64-bit indices; element size is 8 bytes (qword)
	VPGATHERQQ Y1, (AX)(Y0*8), Y2

	// Store result vector
	VMOVDQA Y2, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return
	RET
