// Code generated by command: go run asm_vpgatherqq_128.go -out ../asm_vpgatherqq_128.s -stubs ../stub_vpgatherqq_128.go -pkg vpgatherqq. DO NOT EDIT.

#include "textflag.h"

// func vpgatherqq128(base *[8]uint64, index *[2]uint64, mask *[2]uint64, ret *[2]uint64)
// Requires: AVX, AVX2
TEXT ·vpgatherqq128(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 64-bit indices into XMM register (lower 2 qwords used)
	VMOVDQA (CX), X0

	// Load mask into XMM register (MSB of each qword lane used)
	VMOVDQA (DX), X1

	// Load destination/src vector
	VMOVDQA (BX), X2

	// Gather using 64-bit indices; element size is 8 bytes (qword)
	VPGATHERQQ X1, (AX)(X0*8), X2

	// Store result vector
	VMOVDQA X2, (BX)

	// Return
	RET
