// Code generated by command: go run asm_vpgatherqq_256.go -out ../asm_vpgatherqq_256.s -stubs ../stub_vpgatherqq_256.go -pkg vpgatherqq. DO NOT EDIT.

package vpgatherqq

func vpgatherqq256(base *[8]uint64, index *[4]uint64, mask *[4]uint64, ret *[4]uint64)
