// Code generated by command: go run asm_vpgatherqq_128.go -out ../asm_vpgatherqq_128.s -stubs ../stub_vpgatherqq_128.go -pkg vpgatherqq. DO NOT EDIT.

package vpgatherqq

func vpgatherqq128(base *[8]uint64, index *[2]uint64, mask *[2]uint64, ret *[2]uint64)
