// Code generated by command: go run asm_vblendvpb_256.go -out ../asm_vblendvpb_256.s -stubs ../stub_vblendvpb_256.go -pkg blendvpb. DO NOT EDIT.

#include "textflag.h"

// func vblendvpb256(base *[32]uint8, blend *[32]uint8, mask *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vblendvpb256(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend, and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1
	VMOVDQA (DX), Y2

	// VPBLENDVB: variable blend using per-byte sign bits of mask
	VPBLENDVB Y2, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
