// Code generated by command: go run asm_vblendvpb_128.go -out ../asm_vblendvpb_128.s -stubs ../stub_vblendvpb_128.go -pkg blendvpb. DO NOT EDIT.

#include "textflag.h"

// func vblendvpb128(base *[16]uint8, blend *[16]uint8, mask *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vblendvpb128(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend, and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1
	VMOVDQA (DX), X2

	// VPBLENDVB: variable blend using per-byte sign bits of mask
	VPBLENDVB X2, X1, X0, X0

	// Store result
	VMOVDQA X0, (BX)

	// Return from function
	RET
