// Code generated by command: go run asm_vblendvpb_128.go -out ../asm_vblendvpb_128.s -stubs ../stub_vblendvpb_128.go -pkg blendvpb. DO NOT EDIT.

package blendvpb

func vblendvpb128(base *[16]uint8, blend *[16]uint8, mask *[16]uint8, ret *[16]uint8)
