// Code generated by command: go run asm_vblendvpb_256.go -out ../asm_vblendvpb_256.s -stubs ../stub_vblendvpb_256.go -pkg blendvpb. DO NOT EDIT.

package blendvpb

func vblendvpb256(base *[32]uint8, blend *[32]uint8, mask *[32]uint8, ret *[32]uint8)
