// Code generated by command: go run asm.go -out ../asm.s -stubs ../stub.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb(b byte, ret *[32]byte)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastb(SB), NOSPLIT, $0-16
	// load params
	MOVBQZX b+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Broadcast b into YMM register
	VPBROADCASTB X0, Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
