// Code generated by command: go run asm_vextractf128_256_one.go -out ../asm_vextractf128_256_one.s -stubs ../stub_vextractf128_256_one.go -pkg vextractf128. DO NOT EDIT.

#include "textflag.h"

// func vextractf128256One(base *[8]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vextractf128256One(SB), NOSPLIT, $0-16
	// load params
	MOVQ base+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load base YMM register
	VMOVDQA (AX), Y0

	// Extract upper 128-bit lane (imm8=1) directly to memory
	VEXTRACTF128 $0x01, Y0, (CX)

	// Return from function
	RET
