// Code generated by command: go run asm_vextractf128_256_one.go -out ../asm_vextractf128_256_one.s -stubs ../stub_vextractf128_256_one.go -pkg vextractf128. DO NOT EDIT.

package vextractf128

func vextractf128256One(base *[8]float32, ret *[4]float32)
