// Code generated by command: go run asm_vunpckhps_128.go -out ../asm_vunpckhps_128.s -stubs ../stub_vunpckhps_128.go -pkg unpckhps. DO NOT EDIT.

#include "textflag.h"

// func vunpckhps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vunpckhps128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// VUNPCKHPS: interleave high pairs -> dst = [a2,b2,a3,b3]
	VUNPCKHPS X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
