// Code generated by command: go run asm_unpckhps_128.go -out ../asm_unpckhps_128.s -stubs ../stub_unpckhps_128.go -pkg unpckhps. DO NOT EDIT.

package unpckhps

func unpckhps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
