// Code generated by command: go run asm_vunpckhps_128.go -out ../asm_vunpckhps_128.s -stubs ../stub_vunpckhps_128.go -pkg unpckhps. DO NOT EDIT.

package unpckhps

func vunpckhps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
