// Code generated by command: go run asm_vunpckhps_256.go -out ../asm_vunpckhps_256.s -stubs ../stub_vunpckhps_256.go -pkg unpckhps. DO NOT EDIT.

package unpckhps

func vunpckhps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
