// Code generated by command: go run asm_vhaddpd_256.go -out ../asm_vhaddpd_256.s -stubs ../stub_vhaddpd_256.go -pkg vhaddpd. DO NOT EDIT.

package vhaddpd

func vhaddpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
