// Code generated by command: go run asm_vhaddpd_128.go -out ../asm_vhaddpd_128.s -stubs ../stub_vhaddpd_128.go -pkg vhaddpd. DO NOT EDIT.

package vhaddpd

func vhaddpd128(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
