// Code generated by command: go run asm_vrcpps_128.go -out ../asm_vrcpps_128.s -stubs ../stub_vrcpps_128.go -pkg rcpps. DO NOT EDIT.

#include "textflag.h"

// func vrcpps128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vrcpps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal of packed float32 values with VEX encoding: regX1 = 1.0 / regX1
	VRCPPS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
