// Code generated by command: go run asm_vrcpps_128.go -out ../asm_vrcpps_128.s -stubs ../stub_vrcpps_128.go -pkg rcpps. DO NOT EDIT.

package rcpps

func vrcpps128(vals *[4]float32, ret *[4]float32)
