// Code generated by command: go run asm_vrcpps_256.go -out ../asm_vrcpps_256.s -stubs ../stub_vrcpps_256.go -pkg rcpps. DO NOT EDIT.

package rcpps

func vrcpps256(vals *[8]float32, ret *[8]float32)
