// Code generated by command: go run asm_pmaxub_128.go -out ../asm_pmaxub_128.s -stubs ../stub_pmaxub_128.go -pkg pmaxub. DO NOT EDIT.

package pmaxub

func pmaxub128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
