// Code generated by command: go run asm_vtestpd_128.go -out ../asm_vtestpd_128.s -stubs ../stub_vtestpd_128.go -pkg vtestpd. DO NOT EDIT.

#include "textflag.h"

// func vtestpd128(vals1 *[2]float64, vals2 *[2]float64, ret *uint32)
// Requires: AVX
TEXT ·vtestpd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load inputs into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VTESTPD sets ZF/CF based on sign-bit AND/ANDN across lanes
	VTESTPD X0, X1

	// Capture ZF (SETEQ) and CF (SETCS) into a 32-bit mask: bit0=ZF, bit1=CF
	SETEQ   AL
	SETCS   CL
	MOVBLZX AL, AX
	MOVBLZX CL, CX
	SHLL    $0x01, CX
	ORL     AX, CX
	MOVL    CX, (DX)

	// Return from function
	RET
