// Code generated by command: go run asm_vtestpd_256.go -out ../asm_vtestpd_256.s -stubs ../stub_vtestpd_256.go -pkg vtestpd. DO NOT EDIT.

package vtestpd

func vtestpd256(vals1 *[4]float64, vals2 *[4]float64, ret *uint32)
