// Code generated by command: go run asm_vtestpd_128.go -out ../asm_vtestpd_128.s -stubs ../stub_vtestpd_128.go -pkg vtestpd. DO NOT EDIT.

package vtestpd

func vtestpd128(vals1 *[2]float64, vals2 *[2]float64, ret *uint32)
