// Code generated by command: go run asm_64_loadstore_movlps.go -out ../asm_64_loadstore_movlps.s -stubs ../stub_64_loadstore_movlps.go -pkg movlps. DO NOT EDIT.

#include "textflag.h"

// func movlps64LoadStoreMovlps(vals *[2]float32, ret *[2]float32)
// Requires: SSE
TEXT ·movlps64LoadStoreMovlps(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVLPS (AX), X0

	// Write contents of the XMM register into memory region
	MOVLPS X0, (CX)
	RET
