// Code generated by command: go run asm_vmovlps_64.go -out ../asm_vmovlps_64.s -stubs ../stub_vmovlps_64.go -pkg movlps. DO NOT EDIT.

#include "textflag.h"

// func vmovlps64(lower *[2]float32, upper *[2]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·vmovlps64(SB), NOSPLIT, $0-24
	// load params
	MOVQ lower+0(FP), AX
	MOVQ upper+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load upper (64 bit) into upper half of XMM register
	MOVHPS (CX), X0

	// Load lower (64 bit) and merge with upper in register
	VMOVLPS (AX), X0, X0

	// Write contents of the merged XMM register into memory region
	VMOVUPS X0, (DX)
	RET
