// Code generated by command: go run asm_64_loadmergestore_movlps.go -out ../asm_64_loadmergestore_movlps.s -stubs ../stub_64_loadmergestore_movlps.go -pkg movlps. DO NOT EDIT.

#include "textflag.h"

// func movlps64LoadMergeStoreMovlps(lower *[2]float32, upper *[2]float32, ret *[4]float32)
// Requires: SSE
TEXT ·movlps64LoadMergeStoreMovlps(SB), NOSPLIT, $0-24
	// load params
	MOVQ lower+0(FP), AX
	MOVQ upper+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load upper (64 bit) into upper half of XMM register
	MOVHPS (CX), X0

	// Load lower (64 bit) and merge with upper in register
	MOVLPS (AX), X0

	// Write contents of the merged XMM register into memory region
	MOVUPS X0, (DX)
	RET
