// Code generated by command: go run asm_vmovlps_64.go -out ../asm_vmovlps_64.s -stubs ../stub_vmovlps_64.go -pkg movlps. DO NOT EDIT.

package movlps

func vmovlps64(lower *[2]float32, upper *[2]float32, ret *[4]float32)
