// Code generated by command: go run asm_movlps_64.go -out ../asm_movlps_64.s -stubs ../stub_movlps_64.go -pkg movlps. DO NOT EDIT.

package movlps

func movlps64(lower *[2]float32, upper *[2]float32, ret *[4]float32)
