// Code generated by command: go run asm_64_loadstore_movlps.go -out ../asm_64_loadstore_movlps.s -stubs ../stub_64_loadstore_movlps.go -pkg movlps. DO NOT EDIT.

package movlps

func movlps64LoadStoreMovlps(vals *[2]float32, ret *[2]float32)
