// Code generated by command: go run asm_64_loadmergestore_vmovlps.go -out ../asm_64_loadmergestore_vmovlps.s -stubs ../stub_64_loadmergestore_vmovlps.go -pkg movlps. DO NOT EDIT.

package movlps

func movlps64LoadMergeStoreVmovlps(lower *[2]float32, upper *[2]float32, ret *[4]float32)
