// Code generated by command: go run asm_64_loadmergestore_movlps.go -out ../asm_64_loadmergestore_movlps.s -stubs ../stub_64_loadmergestore_movlps.go -pkg movlps. DO NOT EDIT.

package movlps

func movlps64LoadMergeStoreMovlps(lower *[2]float32, upper *[2]float32, ret *[4]float32)
