// Code generated by command: go run asm_vunpckhpd_256.go -out ../asm_vunpckhpd_256.s -stubs ../stub_vunpckhpd_256.go -pkg vunpckhpd. DO NOT EDIT.

package vunpckhpd

func vunpckhpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
