// Code generated by command: go run asm_vunpckhpd_128.go -out ../asm_vunpckhpd_128.s -stubs ../stub_vunpckhpd_128.go -pkg vunpckhpd. DO NOT EDIT.

package vunpckhpd

func vunpckhpd128(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
