// Code generated by command: go run asm_vcvtps2dq_128.go -out ../asm_vcvtps2dq_128.s -stubs ../stub_vcvtps2dq_128.go -pkg cvtps2dq. DO NOT EDIT.

#include "textflag.h"

// func vcvtps2dq128(vals *[4]float32, ret *[4]int32)
// Requires: AVX
TEXT ·vcvtps2dq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTPS2DQ X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
