// Code generated by command: go run asm_vcvtps2dq_256.go -out ../asm_vcvtps2dq_256.s -stubs ../stub_vcvtps2dq_256.go -pkg cvtps2dq. DO NOT EDIT.

#include "textflag.h"

// func vcvtps2dq256(vals *[8]float32, ret *[8]int32)
// Requires: AVX
TEXT ·vcvtps2dq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Execute the instruction being demonstrated
	VCVTPS2DQ Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
