// Code generated by command: go run asm_vcvtps2dq_128.go -out ../asm_vcvtps2dq_128.s -stubs ../stub_vcvtps2dq_128.go -pkg cvtps2dq. DO NOT EDIT.

package cvtps2dq

func vcvtps2dq128(vals *[4]float32, ret *[4]int32)
