// Code generated by command: go run asm_vcvtdq2pd_256.go -out ../asm_vcvtdq2pd_256.s -stubs ../stub_vcvtdq2pd_256.go -pkg cvtdq2pd. DO NOT EDIT.

#include "textflag.h"

// func vcvtdq2pd256(vals *[4]int32, ret *[4]float64)
// Requires: AVX
TEXT ·vcvtdq2pd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTDQ2PD X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
