// Code generated by command: go run asm_vcvtdq2pd_256.go -out ../asm_vcvtdq2pd_256.s -stubs ../stub_vcvtdq2pd_256.go -pkg cvtdq2pd. DO NOT EDIT.

package cvtdq2pd

func vcvtdq2pd256(vals *[4]int32, ret *[4]float64)
