// Code generated by command: go run asm_vcvtdq2pd_128.go -out ../asm_vcvtdq2pd_128.s -stubs ../stub_vcvtdq2pd_128.go -pkg cvtdq2pd. DO NOT EDIT.

package cvtdq2pd

func vcvtdq2pd128(vals *[4]int32, ret *[2]float64)
