// Code generated by command: go run asm_vcvtpd2dq_128.go -out ../asm_vcvtpd2dq_128.s -stubs ../stub_vcvtpd2dq_128.go -pkg cvtpd2dq. DO NOT EDIT.

package cvtpd2dq

func vcvtpd2dq128(vals *[2]float64, ret *[4]int32)
