// Code generated by command: go run asm_vcvtpd2dq_256.go -out ../asm_vcvtpd2dq_256.s -stubs ../stub_vcvtpd2dq_256.go -pkg cvtpd2dq. DO NOT EDIT.

package cvtpd2dq

func vcvtpd2dq256(vals *[4]float64, ret *[4]int32)
