// Code generated by command: go run asm_vcvtss2si_128_int64.go -out ../asm_vcvtss2si_128_int64.s -stubs ../stub_vcvtss2si_128_int64.go -pkg cvtss2si. DO NOT EDIT.

#include "textflag.h"

// func vcvtss2si128Int64(vals *[4]float32, ret *int64)
// Requires: AVX
TEXT ·vcvtss2si128Int64(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Convert scalar single in lowest lane to signed 64-bit integer
	VCVTSS2SIQ X0, AX

	// Write result to return memory address
	MOVQ AX, (CX)

	// Return from function
	RET
