// Code generated by command: go run asm_vcvtss2si_128_int32.go -out ../asm_vcvtss2si_128_int32.s -stubs ../stub_vcvtss2si_128_int32.go -pkg cvtss2si. DO NOT EDIT.

package cvtss2si

func vcvtss2si128Int32(vals *[4]float32, ret *int32)
