// Code generated by command: go run asm_vcvtpd2ps_256.go -out ../asm_vcvtpd2ps_256.s -stubs ../stub_vcvtpd2ps_256.go -pkg cvtpd2ps. DO NOT EDIT.

#include "textflag.h"

// func vcvtpd2ps256(vals *[4]float64, ret *[4]float32)
// Requires: AVX
TEXT ·vcvtpd2ps256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Execute the instruction being demonstrated
	VCVTPD2PSY Y0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
