// Code generated by command: go run asm_vcvtpd2ps_128.go -out ../asm_vcvtpd2ps_128.s -stubs ../stub_vcvtpd2ps_128.go -pkg cvtpd2ps. DO NOT EDIT.

#include "textflag.h"

// func vcvtpd2ps128(vals *[2]float64, ret *[4]float32)
// Requires: AVX
TEXT ·vcvtpd2ps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTPD2PSX X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
