// Code generated by command: go run asm_vcvtpd2ps_256.go -out ../asm_vcvtpd2ps_256.s -stubs ../stub_vcvtpd2ps_256.go -pkg cvtpd2ps. DO NOT EDIT.

package cvtpd2ps

func vcvtpd2ps256(vals *[4]float64, ret *[4]float32)
