// Code generated by command: go run asm_vcvtpd2ps_128.go -out ../asm_vcvtpd2ps_128.s -stubs ../stub_vcvtpd2ps_128.go -pkg cvtpd2ps. DO NOT EDIT.

package cvtpd2ps

func vcvtpd2ps128(vals *[2]float64, ret *[4]float32)
