// Code generated by command: go run asm_vperm2i128_256_lowa_zeroed.go -out ../asm_vperm2i128_256_lowa_zeroed.s -stubs ../stub_vperm2i128_256_lowa_zeroed.go -pkg vperm2i128. DO NOT EDIT.

#include "textflag.h"

// func vperm2i128256Lowa_zeroed(valsA *[4]uint64, valsB *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vperm2i128256Lowa_zeroed(SB), NOSPLIT, $0-24
	// load params
	MOVQ valsA+0(FP), AX
	MOVQ valsB+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load A and B into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERM2I128 imm: low=a.low (0000), high=zero (0100) → imm=0x80
	VPERM2I128 $0x80, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
