// Code generated by command: go run asm_vperm2i128_256_highb_highb.go -out ../asm_vperm2i128_256_highb_highb.s -stubs ../stub_vperm2i128_256_highb_highb.go -pkg vperm2i128. DO NOT EDIT.

package vperm2i128

func vperm2i128256Highb_highb(valsA *[4]uint64, valsB *[4]uint64, ret *[4]uint64)
