// Code generated by command: go run asm_vperm2i128_256_lowb_higha.go -out ../asm_vperm2i128_256_lowb_higha.s -stubs ../stub_vperm2i128_256_lowb_higha.go -pkg vperm2i128. DO NOT EDIT.

package vperm2i128

func vperm2i128256Lowb_higha(valsA *[4]uint64, valsB *[4]uint64, ret *[4]uint64)
