// Code generated by command: go run asm_vinserti128_256_one.go -out ../asm_vinserti128_256_one.s -stubs ../stub_vinserti128_256_one.go -pkg vinserti128. DO NOT EDIT.

#include "textflag.h"

// func vinserti128256One(vals128 *[4]uint32, vals256 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vinserti128256One(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals128+0(FP), AX
	MOVQ vals256+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals128 into XMM register
	VMOVDQU (AX), X0

	// Load vals256 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VINSERTI128 $0x01, X0, Y1, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
