// Code generated by command: go run asm_vinserti128_256_zero.go -out ../asm_vinserti128_256_zero.s -stubs ../stub_vinserti128_256_zero.go -pkg vinserti128. DO NOT EDIT.

#include "textflag.h"

// func vinserti128256Zero(vals128 *[4]uint32, vals256 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vinserti128256Zero(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals128+0(FP), AX
	MOVQ vals256+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals256 into YMM register
	VMOVDQU (CX), Y0

	// Insert 128-bit block into lower 128-bit lane (0) of YMM; upper lane preserved from vals256
	VINSERTI128 $0x00, (AX), Y0, Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER
	RET
