// Code generated by command: go run asm_vinserti128_256_zero.go -out ../asm_vinserti128_256_zero.s -stubs ../stub_vinserti128_256_zero.go -pkg vinserti128. DO NOT EDIT.

package vinserti128

func vinserti128256Zero(vals128 *[4]uint32, vals256 *[8]uint32, ret *[8]uint32)
