// Code generated by command: go run asm_vmovmskpd_128.go -out ../asm_vmovmskpd_128.s -stubs ../stub_vmovmskpd_128.go -pkg movmskpd. DO NOT EDIT.

#include "textflag.h"

// func vmovmskpd128(vals *[2]float64, ret *[4]byte)
// Requires: AVX
TEXT ·vmovmskpd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPD (AX), X0

	// Extract sign mask values from vals
	VMOVMSKPD X0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
