// Code generated by command: go run asm_movmskpd_128.go -out ../asm_movmskpd_128.s -stubs ../stub_movmskpd_128.go -pkg movmskpd. DO NOT EDIT.

#include "textflag.h"

// func movmskpd128(vals *[2]float64, ret *[4]byte)
// Requires: SSE2
TEXT ·movmskpd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVAPD (AX), X0

	// Extract sign mask values from vals
	MOVMSKPD X0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
