// Code generated by command: go run asm_vmovmskpd_256.go -out ../asm_vmovmskpd_256.s -stubs ../stub_vmovmskpd_256.go -pkg movmskpd. DO NOT EDIT.

#include "textflag.h"

// func vmovmskpd256(vals *[4]float64, ret *[4]byte)
// Requires: AVX
TEXT ·vmovmskpd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVAPD (AX), Y0

	// Extract sign mask values from vals
	VMOVMSKPD Y0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
