// Code generated by command: go run asm_movmskpd_128.go -out ../asm_movmskpd_128.s -stubs ../stub_movmskpd_128.go -pkg movmskpd. DO NOT EDIT.

package movmskpd

func movmskpd128(vals *[2]float64, ret *[4]byte)
