// Code generated by command: go run asm_vmovmskpd_128.go -out ../asm_vmovmskpd_128.s -stubs ../stub_vmovmskpd_128.go -pkg movmskpd. DO NOT EDIT.

package movmskpd

func vmovmskpd128(vals *[2]float64, ret *[4]byte)
