// Code generated by command: go run asm_vmovmskpd_256.go -out ../asm_vmovmskpd_256.s -stubs ../stub_vmovmskpd_256.go -pkg movmskpd. DO NOT EDIT.

package movmskpd

func vmovmskpd256(vals *[4]float64, ret *[4]byte)
