// Code generated by command: go run asm_vpackssdw_256.go -out ../asm_vpackssdw_256.s -stubs ../stub_vpackssdw_256.go -pkg packss. DO NOT EDIT.

#include "textflag.h"

// func vpackssdw256(vals1 *[8]int32, vals2 *[8]int32, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpackssdw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Pack signed dwords to signed words with saturation (per 128-bit lane)
	VPACKSSDW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
