// Code generated by command: go run asm_vpackssdw_128.go -out ../asm_vpackssdw_128.s -stubs ../stub_vpackssdw_128.go -pkg packss. DO NOT EDIT.

package packss

func vpackssdw128(vals1 *[4]int32, vals2 *[4]int32, ret *[8]int16)
