// Code generated by command: go run asm_vpacksswb_128.go -out ../asm_vpacksswb_128.s -stubs ../stub_vpacksswb_128.go -pkg packss. DO NOT EDIT.

package packss

func vpacksswb128(vals1 *[8]int16, vals2 *[8]int16, ret *[16]int8)
