// Code generated by command: go run asm_vpacksswb_256.go -out ../asm_vpacksswb_256.s -stubs ../stub_vpacksswb_256.go -pkg packss. DO NOT EDIT.

package packss

func vpacksswb256(vals1 *[16]int16, vals2 *[16]int16, ret *[32]int8)
