// Code generated by command: go run asm_vpackssdw_256.go -out ../asm_vpackssdw_256.s -stubs ../stub_vpackssdw_256.go -pkg packss. DO NOT EDIT.

package packss

func vpackssdw256(vals1 *[8]int32, vals2 *[8]int32, ret *[16]int16)
