// Code generated by command: go run asm_vpsrld_128.go -out ../asm_vpsrld_128.s -stubs ../stub_vpsrld_128.go -pkg psrl. DO NOT EDIT.

#include "textflag.h"

// func vpsrld128(vals *[4]uint32, shift *[2]uint64, ret *[4]uint32)
// Requires: AVX
TEXT ·vpsrld128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Logical right shift packed dwords by per-lane counts (register)
	VPSRLD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
