// Code generated by command: go run asm_vpsrlw_128.go -out ../asm_vpsrlw_128.s -stubs ../stub_vpsrlw_128.go -pkg psrl. DO NOT EDIT.

#include "textflag.h"

// func vpsrlw128(vals *[8]uint16, shift *[2]uint64, ret *[8]uint16)
// Requires: AVX
TEXT ·vpsrlw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Logical right shift packed words by per-lane counts (register)
	VPSRLW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
