// Code generated by command: go run asm_vpsrlw_256.go -out ../asm_vpsrlw_256.s -stubs ../stub_vpsrlw_256.go -pkg psrl. DO NOT EDIT.

#include "textflag.h"

// func vpsrlw256(vals *[16]uint16, shift *[4]uint64, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpsrlw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), X1

	// Logical right shift packed words by per-lane counts (register)
	VPSRLW X1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
