// Code generated by command: go run asm_vpsrld_256.go -out ../asm_vpsrld_256.s -stubs ../stub_vpsrld_256.go -pkg psrl. DO NOT EDIT.

package psrl

func vpsrld256(vals *[8]uint32, shift *[4]uint64, ret *[8]uint32)
