// Code generated by command: go run asm_vpsrlq_128.go -out ../asm_vpsrlq_128.s -stubs ../stub_vpsrlq_128.go -pkg psrl. DO NOT EDIT.

package psrl

func vpsrlq128(vals *[2]uint64, shift *[2]uint64, ret *[2]uint64)
