// Code generated by command: go run asm_vpsrlw_128.go -out ../asm_vpsrlw_128.s -stubs ../stub_vpsrlw_128.go -pkg psrl. DO NOT EDIT.

package psrl

func vpsrlw128(vals *[8]uint16, shift *[2]uint64, ret *[8]uint16)
