// Code generated by command: go run asm_vpsrld_128.go -out ../asm_vpsrld_128.s -stubs ../stub_vpsrld_128.go -pkg psrl. DO NOT EDIT.

package psrl

func vpsrld128(vals *[4]uint32, shift *[2]uint64, ret *[4]uint32)
