// Code generated by command: go run asm_vpgatherdq_256.go -out ../asm_vpgatherdq_256.s -stubs ../stub_vpgatherdq_256.go -pkg vpgatherdq. DO NOT EDIT.

#include "textflag.h"

// func vpgatherdq256(base *[8]uint64, index *[4]uint32, mask *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpgatherdq256(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 32-bit indices into XMM register (lower 4 qwords used)
	VMOVDQA (CX), X0

	// Load mask into YMM register (MSB of each dword lane used)
	VMOVDQA (DX), Y1

	// Load destination/src vector
	VMOVDQA (BX), Y2

	// Gather using 32-bit indices; element size is 4 bytes (dword)
	VPGATHERDQ Y1, (AX)(X0*8), Y2

	// Store result vector
	VMOVDQA Y2, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return
	RET
