// Code generated by command: go run asm_vpgatherdq_256.go -out ../asm_vpgatherdq_256.s -stubs ../stub_vpgatherdq_256.go -pkg vpgatherdq. DO NOT EDIT.

package vpgatherdq

func vpgatherdq256(base *[8]uint64, index *[4]uint32, mask *[4]uint64, ret *[4]uint64)
