// Code generated by command: go run asm_vpgatherdq_128.go -out ../asm_vpgatherdq_128.s -stubs ../stub_vpgatherdq_128.go -pkg vpgatherdq. DO NOT EDIT.

package vpgatherdq

func vpgatherdq128(base *[4]uint64, index *[4]uint32, mask *[2]uint64, ret *[2]uint64)
