// Code generated by command: go run asm_vcvtsi2ss_128_int64.go -out ../asm_vcvtsi2ss_128_int64.s -stubs ../stub_vcvtsi2ss_128_int64.go -pkg cvtsi2ss. DO NOT EDIT.

#include "textflag.h"

// func vcvtsi2ss128int64(vals *[4]float32, ival *int64, ret *[4]float32)
// Requires: AVX
TEXT ·vcvtsi2ss128int64(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ival+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Convert signed 64-bit integer to scalar single and insert into lowest lane
	VCVTSI2SSQ (CX), X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
