// Code generated by command: go run asm_vcvtsi2ss_128_int64.go -out ../asm_vcvtsi2ss_128_int64.s -stubs ../stub_vcvtsi2ss_128_int64.go -pkg cvtsi2ss. DO NOT EDIT.

package cvtsi2ss

func vcvtsi2ss128int64(vals *[4]float32, ival *int64, ret *[4]float32)
