// Code generated by command: go run asm_vcvtsi2ss_128_int32.go -out ../asm_vcvtsi2ss_128_int32.s -stubs ../stub_vcvtsi2ss_128_int32.go -pkg cvtsi2ss. DO NOT EDIT.

package cvtsi2ss

func vcvtsi2ss128int32(vals *[4]float32, ival *int32, ret *[4]float32)
