// Code generated by command: go run asm_vpminsb_256.go -out ../asm_vpminsb_256.s -stubs ../stub_vpminsb_256.go -pkg pmins. DO NOT EDIT.

#include "textflag.h"

// func vpminsb256(vals1 *[32]int8, vals2 *[32]int8, ret *[32]int8)
// Requires: AVX, AVX2
TEXT ·vpminsb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Signed min of packed bytes (per 128-bit lane)
	VPMINSB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
