// Code generated by command: go run asm_vpminsw_256.go -out ../asm_vpminsw_256.s -stubs ../stub_vpminsw_256.go -pkg pmins. DO NOT EDIT.

#include "textflag.h"

// func vpminsw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpminsw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Signed min of packed words (per 128-bit lane)
	VPMINSW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
