// Code generated by command: go run asm_vpminsb_128.go -out ../asm_vpminsb_128.s -stubs ../stub_vpminsb_128.go -pkg pmins. DO NOT EDIT.

#include "textflag.h"

// func vpminsb128(vals1 *[16]int8, vals2 *[16]int8, ret *[16]int8)
// Requires: AVX
TEXT ·vpminsb128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Signed min of packed bytes
	VPMINSB X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
