// Code generated by command: go run asm_vpminsd_256.go -out ../asm_vpminsd_256.s -stubs ../stub_vpminsd_256.go -pkg pmins. DO NOT EDIT.

package pmins

func vpminsd256(vals1 *[8]int32, vals2 *[8]int32, ret *[8]int32)
