// Code generated by command: go run asm_vpminsb_256.go -out ../asm_vpminsb_256.s -stubs ../stub_vpminsb_256.go -pkg pmins. DO NOT EDIT.

package pmins

func vpminsb256(vals1 *[32]int8, vals2 *[32]int8, ret *[32]int8)
