// Code generated by command: go run asm_vpminsw_256.go -out ../asm_vpminsw_256.s -stubs ../stub_vpminsw_256.go -pkg pmins. DO NOT EDIT.

package pmins

func vpminsw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
