// Code generated by command: go run asm_vpminsd_128.go -out ../asm_vpminsd_128.s -stubs ../stub_vpminsd_128.go -pkg pmins. DO NOT EDIT.

package pmins

func vpminsd128(vals1 *[4]int32, vals2 *[4]int32, ret *[4]int32)
