// Code generated by command: go run asm_vpminsb_128.go -out ../asm_vpminsb_128.s -stubs ../stub_vpminsb_128.go -pkg pmins. DO NOT EDIT.

package pmins

func vpminsb128(vals1 *[16]int8, vals2 *[16]int8, ret *[16]int8)
