// Code generated by command: go run asm_vptest_128.go -out ../asm_vptest_128.s -stubs ../stub_vptest_128.go -pkg vptest. DO NOT EDIT.

#include "textflag.h"

// func vptest128(vals1 *[16]uint8, vals2 *[16]uint8, ret *uint32)
// Requires: AVX
TEXT ·vptest128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQU (AX), X0

	// Load vals2 into XMM register
	VMOVDQU (CX), X1

	// Execute the instruction being demonstrated
	VPTEST X0, X1

	// Capture ZF (SETEQ) and CF (SETCS) into a 32-bit mask: bit0=ZF, bit1=CF
	SETEQ   AL
	SETCS   CL
	MOVBLZX AL, AX
	MOVBLZX CL, CX
	SHLL    $0x01, CX
	ORL     AX, CX

	// Store flags into *ret (bit0=ZF, bit1=CF)
	MOVL CX, (DX)

	// Return from function
	RET
