// Code generated by command: go run asm_vptest_256.go -out ../asm_vptest_256.s -stubs ../stub_vptest_256.go -pkg vptest. DO NOT EDIT.

#include "textflag.h"

// func vptest256(vals1 *[32]uint8, vals2 *[32]uint8, ret *uint32)
// Requires: AVX
TEXT ·vptest256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load vals2 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VPTEST Y0, Y1

	// Capture ZF (SETEQ) and CF (SETCS) into a 32-bit mask: bit0=ZF, bit1=CF
	SETEQ   AL
	SETCS   CL
	MOVBLZX AL, AX
	MOVBLZX CL, CX
	SHLL    $0x01, CX
	ORL     AX, CX

	// Store flags into *ret (bit0=ZF, bit1=CF)
	MOVL CX, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
