// Code generated by command: go run asm_vptest_128.go -out ../asm_vptest_128.s -stubs ../stub_vptest_128.go -pkg vptest. DO NOT EDIT.

package vptest

func vptest128(vals1 *[16]uint8, vals2 *[16]uint8, ret *uint32)
