// Code generated by command: go run asm_vpsrad_128.go -out ../asm_vpsrad_128.s -stubs ../stub_vpsrad_128.go -pkg psra. DO NOT EDIT.

#include "textflag.h"

// func vpsrad128(vals *[4]int32, shift *[2]uint64, ret *[4]int32)
// Requires: AVX
TEXT ·vpsrad128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Arithmetical right shift packed dwords by per-lane counts (register)
	VPSRAD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
