// Code generated by command: go run asm_vpsraq_256.go -out ../asm_vpsraq_256.s -stubs ../stub_vpsraq_256.go -pkg psra. DO NOT EDIT.

#include "textflag.h"

// func vpsraq256(vals *[4]int64, shift *[4]uint64, ret *[4]int64)
// Requires: AVX, AVX512F, AVX512VL
TEXT ·vpsraq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), X1

	// Arithmetical right shift packed qwords by per-lane counts (register)
	VPSRAQ X1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
