// Code generated by command: go run asm_vpsraq_128.go -out ../asm_vpsraq_128.s -stubs ../stub_vpsraq_128.go -pkg psra. DO NOT EDIT.

#include "textflag.h"

// func vpsraq128(vals *[2]int64, shift *[2]uint64, ret *[2]int64)
// Requires: AVX, AVX512F, AVX512VL
TEXT ·vpsraq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Arithmetical right shift packed qwords by per-lane counts (register)
	VPSRAQ X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
