// Code generated by command: go run asm_vpsrad_256.go -out ../asm_vpsrad_256.s -stubs ../stub_vpsrad_256.go -pkg psra. DO NOT EDIT.

package psra

func vpsrad256(vals *[8]int32, shift *[4]uint64, ret *[8]int32)
