// Code generated by command: go run asm_vpsraq_256.go -out ../asm_vpsraq_256.s -stubs ../stub_vpsraq_256.go -pkg psra. DO NOT EDIT.

package psra

func vpsraq256(vals *[4]int64, shift *[4]uint64, ret *[4]int64)
