// Code generated by command: go run asm_vpsraq_128.go -out ../asm_vpsraq_128.s -stubs ../stub_vpsraq_128.go -pkg psra. DO NOT EDIT.

package psra

func vpsraq128(vals *[2]int64, shift *[2]uint64, ret *[2]int64)
