// Code generated by command: go run asm_vpsraw_128.go -out ../asm_vpsraw_128.s -stubs ../stub_vpsraw_128.go -pkg psra. DO NOT EDIT.

package psra

func vpsraw128(vals *[8]int16, shift *[2]uint64, ret *[8]int16)
