// Code generated by command: go run asm_vpsraw_256.go -out ../asm_vpsraw_256.s -stubs ../stub_vpsraw_256.go -pkg psra. DO NOT EDIT.

package psra

func vpsraw256(vals *[16]int16, shift *[4]uint64, ret *[16]int16)
