// Code generated by command: go run asm_vgatherdpd_128.go -out ../asm_vgatherdpd_128.s -stubs ../stub_vgatherdpd_128.go -pkg vgatherdpd. DO NOT EDIT.

#include "textflag.h"

// func vgatherdpd128(base *[8]float64, index *[4]uint32, mask *[2]float64, ret *[2]float64)
// Requires: AVX, AVX2
TEXT ·vgatherdpd128(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load index (i32) into XMM index register
	VMOVDQA (CX), X0

	// Load mask (packed f64; MSB of each element used)
	VMOVDQA (DX), X1

	// Load destination/src vector (merge for masked-off lanes)
	VMOVDQA (BX), X2

	// Gather two f64 elements using 32-bit indices; scale=8 for f64 element size
	VGATHERDPD X1, (AX)(X0*8), X2

	// Store result vector
	VMOVDQA X2, (BX)

	// Return
	RET
