// Code generated by command: go run asm_vgatherdpd_256.go -out ../asm_vgatherdpd_256.s -stubs ../stub_vgatherdpd_256.go -pkg vgatherdpd. DO NOT EDIT.

#include "textflag.h"

// func vgatherdpd256(base *[8]float64, index *[4]uint32, mask *[4]float64, ret *[4]float64)
// Requires: AVX, AVX2
TEXT ·vgatherdpd256(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 32-bit indices into XMM register (lower 4 dwords used)
	VMOVDQA (CX), X0

	// Load mask into YMM register
	VMOVDQA (DX), Y1

	// Load destination/src vector
	VMOVDQA (BX), Y2

	// Gather four f64 elements using 32-bit indices; scale=8 for f64 element size
	VGATHERDPD Y1, (AX)(X0*8), Y2

	// Store result vector
	VMOVDQA Y2, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return
	RET
