// Code generated by command: go run asm_vgatherdpd_128.go -out ../asm_vgatherdpd_128.s -stubs ../stub_vgatherdpd_128.go -pkg vgatherdpd. DO NOT EDIT.

package vgatherdpd

func vgatherdpd128(base *[8]float64, index *[4]uint32, mask *[2]float64, ret *[2]float64)
