// Code generated by command: go run asm_vgatherdpd_256.go -out ../asm_vgatherdpd_256.s -stubs ../stub_vgatherdpd_256.go -pkg vgatherdpd. DO NOT EDIT.

package vgatherdpd

func vgatherdpd256(base *[8]float64, index *[4]uint32, mask *[4]float64, ret *[4]float64)
