// Code generated by command: go run asm_vpminub_256.go -out ../asm_vpminub_256.s -stubs ../stub_vpminub_256.go -pkg pminub. DO NOT EDIT.

#include "textflag.h"

// func vpminub256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpminub256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Packed unsigned byte min per lane (VEX, per 128-bit lane)
	VPMINUB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
