// Code generated by command: go run asm_vpminub_128.go -out ../asm_vpminub_128.s -stubs ../stub_vpminub_128.go -pkg pminub. DO NOT EDIT.

package pminub

func vpminub128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
