// Code generated by command: go run asm_vpminub_256.go -out ../asm_vpminub_256.s -stubs ../stub_vpminub_256.go -pkg pminub. DO NOT EDIT.

package pminub

func vpminub256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
