// Code generated by command: go run asm_pminub_128.go -out ../asm_pminub_128.s -stubs ../stub_pminub_128.go -pkg pminub. DO NOT EDIT.

package pminub

func pminub128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
