// Code generated by command: go run asm_vmovhps_64.go -out ../asm_vmovhps_64.s -stubs ../stub_vmovhps_64.go -pkg movhps. DO NOT EDIT.

#include "textflag.h"

// func vmovhps64(lower *[2]float32, upper *[2]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·vmovhps64(SB), NOSPLIT, $0-24
	// load params
	MOVQ lower+0(FP), AX
	MOVQ upper+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load lower (64 bit) into lower half of XMM register
	MOVLPS (AX), X0

	// Load upper (64 bit) and merge with lower in register
	VMOVHPS (CX), X0, X0

	// Write contents of the merged XMM register into memory region
	VMOVUPS X0, (DX)
	RET
