// Code generated by command: go run asm_64_loadmergestore_vmovhps.go -out ../asm_64_loadmergestore_vmovhps.s -stubs ../stub_64_loadmergestore_vmovhps.go -pkg movhps. DO NOT EDIT.

package movhps

func movhps64LoadMergeStoreVmovhps(lower *[2]float32, upper *[2]float32, ret *[4]float32)
