// Code generated by command: go run asm_64_loadmergestore_movhps.go -out ../asm_64_loadmergestore_movhps.s -stubs ../stub_64_loadmergestore_movhps.go -pkg movhps. DO NOT EDIT.

package movhps

func movhps64Loadmergestore(lower *[2]float32, upper *[2]float32, ret *[4]float32)
