// Code generated by command: go run asm_movhps_64.go -out ../asm_movhps_64.s -stubs ../stub_movhps_64.go -pkg movhps. DO NOT EDIT.

package movhps

func movhps64(lower *[2]float32, upper *[2]float32, ret *[4]float32)
