// Code generated by command: go run asm_vpor_256.go -out ../asm_vpor_256.s -stubs ../stub_vpor_256.go -pkg por. DO NOT EDIT.

package por

func vpor256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
