// Code generated by command: go run asm_vpor_128.go -out ../asm_vpor_128.s -stubs ../stub_vpor_128.go -pkg por. DO NOT EDIT.

package por

func vpor128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
