// Code generated by command: go run asm_vpsrldq_128_eight.go -out ../asm_vpsrldq_128_eight.s -stubs ../stub_vpsrldq_128_eight.go -pkg vpsrldq. DO NOT EDIT.

#include "textflag.h"

// func vpsrldq128Eight(vals *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpsrldq128Eight(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPSRLDQ $0x08, X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
