// Code generated by command: go run asm_vpsrldq_256_one.go -out ../asm_vpsrldq_256_one.s -stubs ../stub_vpsrldq_256_one.go -pkg vpsrldq. DO NOT EDIT.

#include "textflag.h"

// func vpsrldq256One(vals *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpsrldq256One(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Execute the instruction being demonstrated
	VPSRLDQ $0x01, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
