// Code generated by command: go run asm_vpsrldq_256_one.go -out ../asm_vpsrldq_256_one.s -stubs ../stub_vpsrldq_256_one.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq256One(vals *[32]uint8, ret *[32]uint8)
