// Code generated by command: go run asm_vpsrldq_256_eight.go -out ../asm_vpsrldq_256_eight.s -stubs ../stub_vpsrldq_256_eight.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq256Eight(vals *[32]uint8, ret *[32]uint8)
