// Code generated by command: go run asm_vpsrldq_256_sixteen.go -out ../asm_vpsrldq_256_sixteen.s -stubs ../stub_vpsrldq_256_sixteen.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq256Sixteen(vals *[32]uint8, ret *[32]uint8)
