// Code generated by command: go run asm_vpsrldq_256_fifteen.go -out ../asm_vpsrldq_256_fifteen.s -stubs ../stub_vpsrldq_256_fifteen.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq256Fifteen(vals *[32]uint8, ret *[32]uint8)
