// Code generated by command: go run asm_vpsrldq_128_one.go -out ../asm_vpsrldq_128_one.s -stubs ../stub_vpsrldq_128_one.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq128One(vals *[16]uint8, ret *[16]uint8)
