// Code generated by command: go run asm_vpsrldq_128_zero.go -out ../asm_vpsrldq_128_zero.s -stubs ../stub_vpsrldq_128_zero.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq128Zero(vals *[16]uint8, ret *[16]uint8)
