// Code generated by command: go run asm_vpsrldq_128_eight.go -out ../asm_vpsrldq_128_eight.s -stubs ../stub_vpsrldq_128_eight.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq128Eight(vals *[16]uint8, ret *[16]uint8)
