// Code generated by command: go run asm_vpsrldq_128_fifteen.go -out ../asm_vpsrldq_128_fifteen.s -stubs ../stub_vpsrldq_128_fifteen.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq128Fifteen(vals *[16]uint8, ret *[16]uint8)
