// Code generated by command: go run asm_vpsrldq_256_zero.go -out ../asm_vpsrldq_256_zero.s -stubs ../stub_vpsrldq_256_zero.go -pkg vpsrldq. DO NOT EDIT.

package vpsrldq

func vpsrldq256Zero(vals *[32]uint8, ret *[32]uint8)
