// Code generated by command: go run asm_vmovss_128.go -out ../asm_vmovss_128.s -stubs ../stub_vmovss_128.go -pkg movss. DO NOT EDIT.

#include "textflag.h"

// func vmovss128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmovss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVSS (AX), X0

	// Move vals into another XMM register
	VMOVSS X0, X1, X1

	// Write contents of the second XMM register into memory region
	VMOVSS X1, (CX)
	RET
