// Code generated by command: go run asm_movss_128.go -out ../asm_movss_128.s -stubs ../stub_movss_128.go -pkg movss. DO NOT EDIT.

#include "textflag.h"

// func movss128(vals *[4]float32, ret *[4]float32)
// Requires: SSE
TEXT ·movss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVSS (AX), X0

	// Move vals into another XMM register
	MOVSS X0, X1

	// Write contents of the second XMM register into memory region
	MOVSS X1, (CX)
	RET
