// Code generated by command: go run asm_128_loadstore_vmovss.go -out ../asm_128_loadstore_vmovss.s -stubs ../stub_128_loadstore_vmovss.go -pkg movss. DO NOT EDIT.

#include "textflag.h"

// func movss128LoadStoreVmovss(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·movss128LoadStoreVmovss(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVSS (AX), X0

	// Move vals into another XMM register
	VMOVSS X0, X1, X1

	// Write contents of the second XMM register into memory region
	VMOVSS X1, (CX)
	RET
