// Code generated by command: go run asm_vmovss_128.go -out ../asm_vmovss_128.s -stubs ../stub_vmovss_128.go -pkg movss. DO NOT EDIT.

package movss

func vmovss128(vals *[4]float32, ret *[4]float32)
