// Code generated by command: go run asm_128_loadstore_vmovss.go -out ../asm_128_loadstore_vmovss.s -stubs ../stub_128_loadstore_vmovss.go -pkg movss. DO NOT EDIT.

package movss

func movss128LoadStoreVmovss(vals *[4]float32, ret *[4]float32)
