// Code generated by command: go run asm_128_loadstore_movss.go -out ../asm_128_loadstore_movss.s -stubs ../stub_128_loadstore_movss.go -pkg movss. DO NOT EDIT.

package movss

func movss128LoadStoreMovss(vals *[4]float32, ret *[4]float32)
