// Code generated by command: go run asm_vdppd_128_low_only.go -out ../asm_vdppd_128_low_only.s -stubs ../stub_vdppd_128_low_only.go -pkg dppd. DO NOT EDIT.

#include "textflag.h"

// func vdppd128Low_only(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vdppd128Low_only(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Dot product of packed doubles with imm8=0x13 (write low only)
	VDPPD $0x13, X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
