// Code generated by command: go run asm_vdppd_128_none.go -out ../asm_vdppd_128_none.s -stubs ../stub_vdppd_128_none.go -pkg dppd. DO NOT EDIT.

package dppd

func vdppd128None(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
