// Code generated by command: go run asm_vdppd_128_low_only.go -out ../asm_vdppd_128_low_only.s -stubs ../stub_vdppd_128_low_only.go -pkg dppd. DO NOT EDIT.

package dppd

func vdppd128Low_only(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
