// Code generated by command: go run asm_vminps_256.go -out ../asm_vminps_256.s -stubs ../stub_vminps_256.go -pkg minps. DO NOT EDIT.

#include "textflag.h"

// func vminps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vminps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Return minimum of packed float32 values with VEX encoding: regY1 = min(regY1, regY2)
	VMINPS Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
