// Code generated by command: go run asm_minps_128.go -out ../asm_minps_128.s -stubs ../stub_minps_128.go -pkg minps. DO NOT EDIT.

package minps

func minps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
