// Code generated by command: go run asm_vminps_256.go -out ../asm_vminps_256.s -stubs ../stub_vminps_256.go -pkg minps. DO NOT EDIT.

package minps

func vminps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
