// Code generated by command: go run asm_vtestps_256.go -out ../asm_vtestps_256.s -stubs ../stub_vtestps_256.go -pkg vtestps. DO NOT EDIT.

#include "textflag.h"

// func vtestps256(vals1 *[8]float32, vals2 *[8]float32, ret *uint32)
// Requires: AVX
TEXT ·vtestps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load inputs into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VTESTPS sets ZF/CF based on sign-bit AND/ANDN across lanes (per 128-bit lane)
	VTESTPS Y0, Y1

	// Capture ZF (SETEQ) and CF (SETCS) into a 32-bit mask: bit0=ZF, bit1=CF
	SETEQ   AL
	SETCS   CL
	MOVBLZX AL, AX
	MOVBLZX CL, CX
	SHLL    $0x01, CX
	ORL     AX, CX
	MOVL    CX, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
