// Code generated by command: go run asm_vtestps_128.go -out ../asm_vtestps_128.s -stubs ../stub_vtestps_128.go -pkg vtestps. DO NOT EDIT.

#include "textflag.h"

// func vtestps128(vals1 *[4]float32, vals2 *[4]float32, ret *uint32)
// Requires: AVX
TEXT ·vtestps128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load inputs into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VTESTPS sets ZF/CF based on sign-bit AND/ANDN across lanes
	VTESTPS X0, X1

	// Capture ZF (SETEQ) and CF (SETCS) into a 32-bit mask: bit0=ZF, bit1=CF
	SETEQ   AL
	SETCS   CL
	MOVBLZX AL, AX
	MOVBLZX CL, CX
	SHLL    $0x01, CX
	ORL     AX, CX
	MOVL    CX, (DX)

	// Return from function
	RET
