// Code generated by command: go run asm_vtestps_128.go -out ../asm_vtestps_128.s -stubs ../stub_vtestps_128.go -pkg vtestps. DO NOT EDIT.

package vtestps

func vtestps128(vals1 *[4]float32, vals2 *[4]float32, ret *uint32)
