// Code generated by command: go run asm_vtestps_256.go -out ../asm_vtestps_256.s -stubs ../stub_vtestps_256.go -pkg vtestps. DO NOT EDIT.

package vtestps

func vtestps256(vals1 *[8]float32, vals2 *[8]float32, ret *uint32)
