// Code generated by command: go run asm_vpandn_256.go -out ../asm_vpandn_256.s -stubs ../stub_vpandn_256.go -pkg pandn. DO NOT EDIT.

package pandn

func vpandn256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
