// Code generated by command: go run asm_vpandn_128.go -out ../asm_vpandn_128.s -stubs ../stub_vpandn_128.go -pkg pandn. DO NOT EDIT.

package pandn

func vpandn128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
