// Code generated by command: go run asm_vmovdqu_128.go -out ../asm_vmovdqu_128.s -stubs ../stub_vmovdqu_128.go -pkg vmovdqu. DO NOT EDIT.

#include "textflag.h"

// func vmovdqu128(vals *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vmovdqu128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Write contents of XMM register into memory region
	VMOVDQU X0, (CX)
	RET
