// Code generated by command: go run asm_vmovdqu_256.go -out ../asm_vmovdqu_256.s -stubs ../stub_vmovdqu_256.go -pkg vmovdqu. DO NOT EDIT.

#include "textflag.h"

// func vmovdqu256(vals *[8]uint32, ret *[8]uint32)
// Requires: AVX
TEXT ·vmovdqu256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER
	RET
