// Code generated by command: go run asm_vmovdqu_128.go -out ../asm_vmovdqu_128.s -stubs ../stub_vmovdqu_128.go -pkg vmovdqu. DO NOT EDIT.

package vmovdqu

func vmovdqu128(vals *[4]uint32, ret *[4]uint32)
