// Code generated by command: go run asm_vmovdqu_256.go -out ../asm_vmovdqu_256.s -stubs ../stub_vmovdqu_256.go -pkg vmovdqu. DO NOT EDIT.

package vmovdqu

func vmovdqu256(vals *[8]uint32, ret *[8]uint32)
