// Code generated by command: go run asm_vpmullw_128.go -out ../asm_vpmullw_128.s -stubs ../stub_vpmullw_128.go -pkg pmull. DO NOT EDIT.

#include "textflag.h"

// func vpmullw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpmullw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPMULLW: multiply packed words, keep low 16 bits per lane
	VPMULLW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
