// Code generated by command: go run asm_vpmullw_256.go -out ../asm_vpmullw_256.s -stubs ../stub_vpmullw_256.go -pkg pmull. DO NOT EDIT.

#include "textflag.h"

// func vpmullw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpmullw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPMULLW: multiply packed words, keep low 16 bits per lane
	VPMULLW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
