// Code generated by command: go run asm_vpmullq_256.go -out ../asm_vpmullq_256.s -stubs ../stub_vpmullq_256.go -pkg pmull. DO NOT EDIT.

#include "textflag.h"

// func vpmullq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX512DQ, AVX512VL
TEXT ·vpmullq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPMULLQ: multiply packed quadwords, keep low 64 bits per lane
	VPMULLQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
