// Code generated by command: go run asm_vpmullq_128.go -out ../asm_vpmullq_128.s -stubs ../stub_vpmullq_128.go -pkg pmull. DO NOT EDIT.

#include "textflag.h"

// func vpmullq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
// Requires: AVX, AVX512DQ, AVX512VL
TEXT ·vpmullq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPMULLQ: multiply packed quadwords, keep low 64 bits per lane
	VPMULLQ X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
