// Code generated by command: go run asm_vpmullw_128.go -out ../asm_vpmullw_128.s -stubs ../stub_vpmullw_128.go -pkg pmull. DO NOT EDIT.

package pmull

func vpmullw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
