// Code generated by command: go run asm_vpmullq_128.go -out ../asm_vpmullq_128.s -stubs ../stub_vpmullq_128.go -pkg pmull. DO NOT EDIT.

package pmull

func vpmullq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
