// Code generated by command: go run asm_vpmulld_256.go -out ../asm_vpmulld_256.s -stubs ../stub_vpmulld_256.go -pkg pmull. DO NOT EDIT.

package pmull

func vpmulld256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
