// Code generated by command: go run asm_vpmullw_256.go -out ../asm_vpmullw_256.s -stubs ../stub_vpmullw_256.go -pkg pmull. DO NOT EDIT.

package pmull

func vpmullw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
