// Code generated by command: go run asm_vpgatherqd_128.go -out ../asm_vpgatherqd_128.s -stubs ../stub_vpgatherqd_128.go -pkg vpgatherqd. DO NOT EDIT.

#include "textflag.h"

// func vpgatherqd128(base *[8]uint32, index *[2]uint64, mask *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpgatherqd128(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 64-bit indices into XMM register (lower 2 qwords used)
	VMOVDQA (CX), X0

	// Load mask into XMM register (MSB of each dword lane used)
	VMOVDQA (DX), X1

	// Load destination/src vector
	VMOVDQA (BX), X2

	// Gather two u32 elements using 64-bit indices; scale=4 for dword element size
	VPGATHERQD X1, (AX)(X0*4), X2

	// Store result vector
	VMOVDQA X2, (BX)

	// Return
	RET
