// Code generated by command: go run asm_vpgatherqd_128.go -out ../asm_vpgatherqd_128.s -stubs ../stub_vpgatherqd_128.go -pkg vpgatherqd. DO NOT EDIT.

package vpgatherqd

func vpgatherqd128(base *[8]uint32, index *[2]uint64, mask *[4]uint32, ret *[4]uint32)
