// Code generated by command: go run asm_vpgatherqd_256.go -out ../asm_vpgatherqd_256.s -stubs ../stub_vpgatherqd_256.go -pkg vpgatherqd. DO NOT EDIT.

package vpgatherqd

func vpgatherqd256(base *[16]uint32, index *[4]uint64, mask *[4]uint32, ret *[4]uint32)
