// Code generated by command: go run asm_vblendvpd_128.go -out ../asm_vblendvpd_128.s -stubs ../stub_vblendvpd_128.go -pkg blendvpd. DO NOT EDIT.

#include "textflag.h"

// func vblendvpd128(base *[2]float64, blend *[2]float64, mask *[2]uint64, ret *[2]float64)
// Requires: AVX
TEXT ·vblendvpd128(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1
	VMOVDQA (DX), X2

	// VBLENDVPD 128: blend using per-lane sign-bit mask
	VBLENDVPD X2, X1, X0, X0

	// Store result
	VMOVDQA X0, (BX)

	// Return from function
	RET
