// Code generated by command: go run asm_vblendvpd_256.go -out ../asm_vblendvpd_256.s -stubs ../stub_vblendvpd_256.go -pkg blendvpd. DO NOT EDIT.

#include "textflag.h"

// func vblendvpd256(base *[4]float64, blend *[4]float64, mask *[4]uint64, ret *[4]float64)
// Requires: AVX
TEXT ·vblendvpd256(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1
	VMOVDQA (DX), Y2

	// VBLENDVPD 256: blend using per-lane sign-bit mask
	VBLENDVPD Y2, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
