// Code generated by command: go run asm_vblendvpd_256.go -out ../asm_vblendvpd_256.s -stubs ../stub_vblendvpd_256.go -pkg blendvpd. DO NOT EDIT.

package blendvpd

func vblendvpd256(base *[4]float64, blend *[4]float64, mask *[4]uint64, ret *[4]float64)
