// Code generated by command: go run asm_vblendvpd_128.go -out ../asm_vblendvpd_128.s -stubs ../stub_vblendvpd_128.go -pkg blendvpd. DO NOT EDIT.

package blendvpd

func vblendvpd128(base *[2]float64, blend *[2]float64, mask *[2]uint64, ret *[2]float64)
