// Code generated by command: go run asm_comiss_128.go -out ../asm_comiss_128.s -stubs ../stub_comiss_128.go -pkg comiss. DO NOT EDIT.

#include "textflag.h"

// func comiss128(vals1 *[4]float32, vals2 *[4]float32) (flags uint32)
// Requires: AVX, SSE
TEXT ·comiss128(SB), NOSPLIT, $0-20
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Compare lowest 32 bit floats from vals1 and vals2, sets EFLAGS as a side effect
	COMISS X1, X0

	// Set byte if ZF flag is true (set to 1 if compared values are equal)
	SETEQ   AL
	MOVBLZX AL, CX

	// Set byte if PF flag is true (set to 1 if either values were NaN)
	SETPS   AL
	MOVBLZX AL, AX
	SHLL    $0x08, CX
	ORL     AX, CX

	// Set byte if CF flag is true (set to 1 if vals1 is less than vals2)
	SETCS   AL
	MOVBLZX AL, AX
	SHLL    $0x08, CX
	ORL     AX, CX
	MOVL    CX, flags+16(FP)

	// Return from function
	RET
