// Code generated by command: go run asm_vcomiss_128.go -out ../asm_vcomiss_128.s -stubs ../stub_vcomiss_128.go -pkg comiss. DO NOT EDIT.

package comiss

func vcomiss128(vals1 *[4]float32, vals2 *[4]float32) (flags uint32)
