// Code generated by command: go run asm_comiss_128.go -out ../asm_comiss_128.s -stubs ../stub_comiss_128.go -pkg comiss. DO NOT EDIT.

package comiss

func comiss128(vals1 *[4]float32, vals2 *[4]float32) (flags uint32)
