// Code generated by command: go run asm_vpaddq_256.go -out ../asm_vpaddq_256.s -stubs ../stub_vpaddq_256.go -pkg padd. DO NOT EDIT.

#include "textflag.h"

// func vpaddq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpaddq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPADDQ: add packed qwords
	VPADDQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
