// Code generated by command: go run asm_vpaddb_256.go -out ../asm_vpaddb_256.s -stubs ../stub_vpaddb_256.go -pkg padd. DO NOT EDIT.

#include "textflag.h"

// func vpaddb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpaddb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPADDB: add packed bytes
	VPADDB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
