// Code generated by command: go run asm_vpaddd_128.go -out ../asm_vpaddd_128.s -stubs ../stub_vpaddd_128.go -pkg padd. DO NOT EDIT.

#include "textflag.h"

// func vpaddd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vpaddd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPADDD: add packed dwords
	VPADDD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
