// Code generated by command: go run asm_vpaddb_128.go -out ../asm_vpaddb_128.s -stubs ../stub_vpaddb_128.go -pkg padd. DO NOT EDIT.

package padd

func vpaddb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
