// Code generated by command: go run asm_vpaddd_256.go -out ../asm_vpaddd_256.s -stubs ../stub_vpaddd_256.go -pkg padd. DO NOT EDIT.

package padd

func vpaddd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
