// Code generated by command: go run asm_vpaddq_256.go -out ../asm_vpaddq_256.s -stubs ../stub_vpaddq_256.go -pkg padd. DO NOT EDIT.

package padd

func vpaddq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
