// Code generated by command: go run asm_vpaddw_128.go -out ../asm_vpaddw_128.s -stubs ../stub_vpaddw_128.go -pkg padd. DO NOT EDIT.

package padd

func vpaddw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
