// Code generated by command: go run asm_vpaddd_128.go -out ../asm_vpaddd_128.s -stubs ../stub_vpaddd_128.go -pkg padd. DO NOT EDIT.

package padd

func vpaddd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
