// Code generated by command: go run asm_vpaddw_256.go -out ../asm_vpaddw_256.s -stubs ../stub_vpaddw_256.go -pkg padd. DO NOT EDIT.

package padd

func vpaddw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
