// Code generated by command: go run asm_vpaddb_256.go -out ../asm_vpaddb_256.s -stubs ../stub_vpaddb_256.go -pkg padd. DO NOT EDIT.

package padd

func vpaddb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
