// Code generated by command: go run asm_vpaddq_128.go -out ../asm_vpaddq_128.s -stubs ../stub_vpaddq_128.go -pkg padd. DO NOT EDIT.

package padd

func vpaddq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
