// Code generated by command: go run asm_divps_128.go -out ../asm_divps_128.s -stubs ../stub_divps_128.go -pkg divps. DO NOT EDIT.

#include "textflag.h"

// func divps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·divps128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Divide packed float32 values: regX1 = regX1 / regX2
	DIVPS X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
