// Code generated by command: go run asm_vdivps_256.go -out ../asm_vdivps_256.s -stubs ../stub_vdivps_256.go -pkg divps. DO NOT EDIT.

package divps

func vdivps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
