// Code generated by command: go run asm_divps_128.go -out ../asm_divps_128.s -stubs ../stub_divps_128.go -pkg divps. DO NOT EDIT.

package divps

func divps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
