// Code generated by command: go run asm_vdivps_128.go -out ../asm_vdivps_128.s -stubs ../stub_vdivps_128.go -pkg divps. DO NOT EDIT.

package divps

func vdivps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
