// Code generated by command: go run asm_vdivss_128.go -out ../asm_vdivss_128.s -stubs ../stub_vdivss_128.go -pkg divss. DO NOT EDIT.

package divss

func vdivss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
