// Code generated by command: go run asm_divss_128.go -out ../asm_divss_128.s -stubs ../stub_divss_128.go -pkg divss. DO NOT EDIT.

package divss

func divss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
