// Code generated by command: go run asm_vpminub_256.go -out ../asm_vpminub_256.s -stubs ../stub_vpminub_256.go -pkg pminu. DO NOT EDIT.

#include "textflag.h"

// func vpminub256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpminub256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Unsigned min of packed bytes (per 128-bit lane)
	VPMINUB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
