// Code generated by command: go run asm_vpminuw_256.go -out ../asm_vpminuw_256.s -stubs ../stub_vpminuw_256.go -pkg pminu. DO NOT EDIT.

#include "textflag.h"

// func vpminuw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpminuw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Unsigned min of packed words (per 128-bit lane)
	VPMINUW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
