// Code generated by command: go run asm_vpminud_256.go -out ../asm_vpminud_256.s -stubs ../stub_vpminud_256.go -pkg pminu. DO NOT EDIT.

#include "textflag.h"

// func vpminud256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpminud256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Unsigned min of packed dwords (per 128-bit lane)
	VPMINUD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
