// Code generated by command: go run asm_vpminuw_128.go -out ../asm_vpminuw_128.s -stubs ../stub_vpminuw_128.go -pkg pminu. DO NOT EDIT.

package pminu

func vpminuw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
