// Code generated by command: go run asm_vpminuw_256.go -out ../asm_vpminuw_256.s -stubs ../stub_vpminuw_256.go -pkg pminu. DO NOT EDIT.

package pminu

func vpminuw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
