// Code generated by command: go run asm_vpminud_256.go -out ../asm_vpminud_256.s -stubs ../stub_vpminud_256.go -pkg pminu. DO NOT EDIT.

package pminu

func vpminud256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
