// Code generated by command: go run asm_vpminud_128.go -out ../asm_vpminud_128.s -stubs ../stub_vpminud_128.go -pkg pminu. DO NOT EDIT.

package pminu

func vpminud128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
