// Code generated by command: go run asm_vpermd_256.go -out ../asm_vpermd_256.s -stubs ../stub_vpermd_256.go -pkg vpermd. DO NOT EDIT.

#include "textflag.h"

// func vpermd256(vals *[8]uint32, control *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpermd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load control and source into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERMD: permute packed 32-bit integers with per-lane dword indices
	VPERMD Y0, Y1, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
