// Code generated by command: go run asm_256_loadstore.go -out ../asm_256_loadstore.s -stubs ../stub_256_loadstore.go -pkg vmovdqa. DO NOT EDIT.

#include "textflag.h"

// func vmovdqa256LoadStore(vals *[8]uint32, ret *[8]uint32)
// Requires: AVX
TEXT ·vmovdqa256LoadStore(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQA (AX), Y0

	// Write contents of YMM register into memory region
	VMOVDQA Y0, (CX)
	RET
