// Code generated by command: go run asm_vmovdqa_128.go -out ../asm_vmovdqa_128.s -stubs ../stub_vmovdqa_128.go -pkg vmovdqa. DO NOT EDIT.

#include "textflag.h"

// func vmovdqa128(vals *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vmovdqa128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Write contents of XMM register into memory region
	VMOVDQA X0, (CX)
	RET
