// Code generated by command: go run asm_vmovdqa_256.go -out ../asm_vmovdqa_256.s -stubs ../stub_vmovdqa_256.go -pkg vmovdqa. DO NOT EDIT.

package vmovdqa

func vmovdqa256(vals *[8]uint32, ret *[8]uint32)
