// Code generated by command: go run asm_256_loadstore.go -out ../asm_256_loadstore.s -stubs ../stub_256_loadstore.go -pkg vmovdqa. DO NOT EDIT.

package vmovdqa

func vmovdqa256LoadStore(vals *[8]uint32, ret *[8]uint32)
