// Code generated by command: go run asm_128_loadstore.go -out ../asm_128_loadstore.s -stubs ../stub_128_loadstore.go -pkg vmovdqu. DO NOT EDIT.

package vmovdqu

func vmovdqu128LoadStore(vals *[4]uint32, ret *[4]uint32)
