// Code generated by command: go run asm_vaddps_256.go -out ../asm_vaddps_256.s -stubs ../stub_vaddps_256.go -pkg addps. DO NOT EDIT.

#include "textflag.h"

// func vaddps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vaddps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Sum packed float32 values from vals1 and vals2
	VADDPS Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)
	RET
