// Code generated by command: go run asm_128_addps.go -out ../asm_128_addps.s -stubs ../stub_128_addps.go -pkg addps. DO NOT EDIT.

package addps

func addps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
