// Code generated by command: go run asm_vaddps_128.go -out ../asm_vaddps_128.s -stubs ../stub_vaddps_128.go -pkg addps. DO NOT EDIT.

package addps

func vaddps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
