// Code generated by command: go run asm_128_vaddps.go -out ../asm_128_vaddps.s -stubs ../stub_128_vaddps.go -pkg addps. DO NOT EDIT.

package addps

func vaddps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
