// Code generated by command: go run asm_256_vaddps.go -out ../asm_256_vaddps.s -stubs ../stub_256_vaddps.go -pkg addps. DO NOT EDIT.

package addps

func vaddps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
