// Code generated by command: go run asm_vaddps_256.go -out ../asm_vaddps_256.s -stubs ../stub_vaddps_256.go -pkg addps. DO NOT EDIT.

package addps

func vaddps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
