// Code generated by command: go run asm_addps_128.go -out ../asm_addps_128.s -stubs ../stub_addps_128.go -pkg addps. DO NOT EDIT.

package addps

func addps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
