// Code generated by command: go run asm_vpsrlvd_128.go -out ../asm_vpsrlvd_128.s -stubs ../stub_vpsrlvd_128.go -pkg vpsrlvd. DO NOT EDIT.

#include "textflag.h"

// func vpsrlvd128(vals *[4]uint32, shifts *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpsrlvd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPSRLVD: shift packed doubleword integers in vals right by variable counts in shifts
	VPSRLVD X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
