// Code generated by command: go run asm_vpsrlvd_256.go -out ../asm_vpsrlvd_256.s -stubs ../stub_vpsrlvd_256.go -pkg vpsrlvd. DO NOT EDIT.

#include "textflag.h"

// func vpsrlvd256(vals *[8]uint32, shifts *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpsrlvd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSRLVD: shift packed doubleword integers in vals right by variable counts in shifts
	VPSRLVD Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
