// Code generated by command: go run asm_vpsrlvd_256.go -out ../asm_vpsrlvd_256.s -stubs ../stub_vpsrlvd_256.go -pkg vpsrlvd. DO NOT EDIT.

package vpsrlvd

func vpsrlvd256(vals *[8]uint32, shifts *[8]uint32, ret *[8]uint32)
