// Code generated by command: go run asm_vpsrlvd_128.go -out ../asm_vpsrlvd_128.s -stubs ../stub_vpsrlvd_128.go -pkg vpsrlvd. DO NOT EDIT.

package vpsrlvd

func vpsrlvd128(vals *[4]uint32, shifts *[4]uint32, ret *[4]uint32)
