// Code generated by command: go run asm_vpmovzxbw_256.go -out ../asm_vpmovzxbw_256.s -stubs ../stub_vpmovzxbw_256.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxbw256(vals *[16]uint8, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpmovzxbw256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXBW X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
