// Code generated by command: go run asm_vpmovzxbw_128.go -out ../asm_vpmovzxbw_128.s -stubs ../stub_vpmovzxbw_128.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxbw128(vals *[16]uint8, ret *[8]uint16)
// Requires: AVX
TEXT ·vpmovzxbw128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXBW X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
