// Code generated by command: go run asm_vpmovzxbq_256.go -out ../asm_vpmovzxbq_256.s -stubs ../stub_vpmovzxbq_256.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxbq256(vals *[16]uint8, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpmovzxbq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXBQ X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
