// Code generated by command: go run asm_vpmovzxwq_256.go -out ../asm_vpmovzxwq_256.s -stubs ../stub_vpmovzxwq_256.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxwq256(vals *[8]uint16, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpmovzxwq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXWQ X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
