// Code generated by command: go run asm_vpmovzxwd_256.go -out ../asm_vpmovzxwd_256.s -stubs ../stub_vpmovzxwd_256.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxwd256(vals *[8]uint16, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpmovzxwd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXWD X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
