// Code generated by command: go run asm_vpmovzxwq_128.go -out ../asm_vpmovzxwq_128.s -stubs ../stub_vpmovzxwq_128.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxwq128(vals *[8]uint16, ret *[2]uint64)
// Requires: AVX
TEXT ·vpmovzxwq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXWQ X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
