// Code generated by command: go run asm_vpmovzxwd_128.go -out ../asm_vpmovzxwd_128.s -stubs ../stub_vpmovzxwd_128.go -pkg vpmovzx. DO NOT EDIT.

#include "textflag.h"

// func vpmovzxwd128(vals *[8]uint16, ret *[4]uint32)
// Requires: AVX
TEXT ·vpmovzxwd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPMOVZXWD X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
