// Code generated by command: go run asm_vpmovzxwq_128.go -out ../asm_vpmovzxwq_128.s -stubs ../stub_vpmovzxwq_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxwq128(vals *[8]uint16, ret *[2]uint64)
