// Code generated by command: go run asm_vpmovzxdq_256.go -out ../asm_vpmovzxdq_256.s -stubs ../stub_vpmovzxdq_256.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxdq256(vals *[4]uint32, ret *[4]uint64)
