// Code generated by command: go run asm_vpmovzxbw_256.go -out ../asm_vpmovzxbw_256.s -stubs ../stub_vpmovzxbw_256.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxbw256(vals *[16]uint8, ret *[16]uint16)
