// Code generated by command: go run asm_vpmovzxbq_256.go -out ../asm_vpmovzxbq_256.s -stubs ../stub_vpmovzxbq_256.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxbq256(vals *[16]uint8, ret *[4]uint64)
