// Code generated by command: go run asm_vpmovzxdq_128.go -out ../asm_vpmovzxdq_128.s -stubs ../stub_vpmovzxdq_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxdq128(vals *[4]uint32, ret *[2]uint64)
