// Code generated by command: go run asm_vpmovzxwq_256.go -out ../asm_vpmovzxwq_256.s -stubs ../stub_vpmovzxwq_256.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxwq256(vals *[8]uint16, ret *[4]uint64)
