// Code generated by command: go run asm_vpmovzxbd_128.go -out ../asm_vpmovzxbd_128.s -stubs ../stub_vpmovzxbd_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxbd128(vals *[16]uint8, ret *[4]uint32)
