// Code generated by command: go run asm_vpmovzxbw_128.go -out ../asm_vpmovzxbw_128.s -stubs ../stub_vpmovzxbw_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxbw128(vals *[16]uint8, ret *[8]uint16)
