// Code generated by command: go run asm_vpmovzxbq_128.go -out ../asm_vpmovzxbq_128.s -stubs ../stub_vpmovzxbq_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxbq128(vals *[16]uint8, ret *[2]uint64)
