// Code generated by command: go run asm_vpmovzxwd_128.go -out ../asm_vpmovzxwd_128.s -stubs ../stub_vpmovzxwd_128.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxwd128(vals *[8]uint16, ret *[4]uint32)
