// Code generated by command: go run asm_vpmovzxwd_256.go -out ../asm_vpmovzxwd_256.s -stubs ../stub_vpmovzxwd_256.go -pkg vpmovzx. DO NOT EDIT.

package vpmovzx

func vpmovzxwd256(vals *[8]uint16, ret *[8]uint32)
