// Code generated by command: go run asm_vpcmpgtb_256.go -out ../asm_vpcmpgtb_256.s -stubs ../stub_vpcmpgtb_256.go -pkg pcmpgt. DO NOT EDIT.

#include "textflag.h"

// func vpcmpgtb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpcmpgtb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Compare packed signed bytes greater-than (per 128-bit lane)
	VPCMPGTB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
