// Code generated by command: go run asm_vpcmpgtd_256.go -out ../asm_vpcmpgtd_256.s -stubs ../stub_vpcmpgtd_256.go -pkg pcmpgt. DO NOT EDIT.

#include "textflag.h"

// func vpcmpgtd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpcmpgtd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Compare packed signed dwords greater-than (per 128-bit lane)
	VPCMPGTD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
