// Code generated by command: go run asm_vpcmpgtd_128.go -out ../asm_vpcmpgtd_128.s -stubs ../stub_vpcmpgtd_128.go -pkg pcmpgt. DO NOT EDIT.

#include "textflag.h"

// func vpcmpgtd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vpcmpgtd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Compare packed signed dwords greater-than
	VPCMPGTD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
