// Code generated by command: go run asm_vpcmpgtw_256.go -out ../asm_vpcmpgtw_256.s -stubs ../stub_vpcmpgtw_256.go -pkg pcmpgt. DO NOT EDIT.

#include "textflag.h"

// func vpcmpgtw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpcmpgtw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Compare packed signed words greater-than (per 128-bit lane)
	VPCMPGTW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
