// Code generated by command: go run asm_vpcmpgtd_256.go -out ../asm_vpcmpgtd_256.s -stubs ../stub_vpcmpgtd_256.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
