// Code generated by command: go run asm_vpcmpgtd_128.go -out ../asm_vpcmpgtd_128.s -stubs ../stub_vpcmpgtd_128.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
