// Code generated by command: go run asm_vpcmpgtb_128.go -out ../asm_vpcmpgtb_128.s -stubs ../stub_vpcmpgtb_128.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
