// Code generated by command: go run asm_vpcmpgtw_128.go -out ../asm_vpcmpgtw_128.s -stubs ../stub_vpcmpgtw_128.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
