// Code generated by command: go run asm_vpcmpgtb_256.go -out ../asm_vpcmpgtb_256.s -stubs ../stub_vpcmpgtb_256.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
