// Code generated by command: go run asm_vpcmpgtq_256.go -out ../asm_vpcmpgtq_256.s -stubs ../stub_vpcmpgtq_256.go -pkg pcmpgt. DO NOT EDIT.

package pcmpgt

func vpcmpgtq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
