// Code generated by command: go run asm_vpmaxsd_128.go -out ../asm_vpmaxsd_128.s -stubs ../stub_vpmaxsd_128.go -pkg pmaxs. DO NOT EDIT.

#include "textflag.h"

// func vpmaxsd128(vals1 *[4]int32, vals2 *[4]int32, ret *[4]int32)
// Requires: AVX
TEXT ·vpmaxsd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Signed max of packed dwords
	VPMAXSD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
