// Code generated by command: go run asm_vpmaxsw_256.go -out ../asm_vpmaxsw_256.s -stubs ../stub_vpmaxsw_256.go -pkg pmaxs. DO NOT EDIT.

package pmaxs

func vpmaxsw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
