// Code generated by command: go run asm_vpmaxsd_256.go -out ../asm_vpmaxsd_256.s -stubs ../stub_vpmaxsd_256.go -pkg pmaxs. DO NOT EDIT.

package pmaxs

func vpmaxsd256(vals1 *[8]int32, vals2 *[8]int32, ret *[8]int32)
