// Code generated by command: go run asm_vpmaxsb_128.go -out ../asm_vpmaxsb_128.s -stubs ../stub_vpmaxsb_128.go -pkg pmaxs. DO NOT EDIT.

package pmaxs

func vpmaxsb128(vals1 *[16]int8, vals2 *[16]int8, ret *[16]int8)
