// Code generated by command: go run asm_vpmaxsb_256.go -out ../asm_vpmaxsb_256.s -stubs ../stub_vpmaxsb_256.go -pkg pmaxs. DO NOT EDIT.

package pmaxs

func vpmaxsb256(vals1 *[32]int8, vals2 *[32]int8, ret *[32]int8)
