// Code generated by command: go run asm_vpmaxsd_128.go -out ../asm_vpmaxsd_128.s -stubs ../stub_vpmaxsd_128.go -pkg pmaxs. DO NOT EDIT.

package pmaxs

func vpmaxsd128(vals1 *[4]int32, vals2 *[4]int32, ret *[4]int32)
