// Code generated by command: go run asm_vcvtdq2ps_128.go -out ../asm_vcvtdq2ps_128.s -stubs ../stub_vcvtdq2ps_128.go -pkg cvtdq2ps. DO NOT EDIT.

#include "textflag.h"

// func vcvtdq2ps128(vals *[4]int32, ret *[4]float32)
// Requires: AVX
TEXT ·vcvtdq2ps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTDQ2PS X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
