// Code generated by command: go run asm_vcvtdq2ps_256.go -out ../asm_vcvtdq2ps_256.s -stubs ../stub_vcvtdq2ps_256.go -pkg cvtdq2ps. DO NOT EDIT.

package cvtdq2ps

func vcvtdq2ps256(vals *[8]int32, ret *[8]float32)
