// Code generated by command: go run asm_vcvtdq2ps_128.go -out ../asm_vcvtdq2ps_128.s -stubs ../stub_vcvtdq2ps_128.go -pkg cvtdq2ps. DO NOT EDIT.

package cvtdq2ps

func vcvtdq2ps128(vals *[4]int32, ret *[4]float32)
