// Code generated by command: go run asm_vpinsrw_128_three_idx.go -out ../asm_vpinsrw_128_three_idx.s -stubs ../stub_vpinsrw_128_three_idx.go -pkg pinsrw. DO NOT EDIT.

#include "textflag.h"

// func vpinsrw128Three_idx(base *[8]uint16, scalar *uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpinsrw128Three_idx(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ scalar+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base into XMM register
	VMOVDQA (AX), X0

	// Insert 16-bit word at index 3 (VEX) from memory into XMM
	VPINSRW $0x03, (CX), X0, X0

	// Write result into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
