// Code generated by command: go run asm_pinsrw_128_three_idx.go -out ../asm_pinsrw_128_three_idx.s -stubs ../stub_pinsrw_128_three_idx.go -pkg pinsrw. DO NOT EDIT.

package pinsrw

func pinsrw128Three_idx(base *[8]uint16, scalar *uint16, ret *[8]uint16)
