// Code generated by command: go run asm_vpinsrw_128_three_idx.go -out ../asm_vpinsrw_128_three_idx.s -stubs ../stub_vpinsrw_128_three_idx.go -pkg pinsrw. DO NOT EDIT.

package pinsrw

func vpinsrw128Three_idx(base *[8]uint16, scalar *uint16, ret *[8]uint16)
