// Code generated by command: go run asm_mulss_128.go -out ../asm_mulss_128.s -stubs ../stub_mulss_128.go -pkg mulss. DO NOT EDIT.

#include "textflag.h"

// func mulss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·mulss128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Multiply scalar single precision values (lowest 32 bits)
	MULSS X0, X1

	// Write results into return memory address
	VMOVDQA X1, (DX)

	// Return from function
	RET
