// Code generated by command: go run asm_vmulss_128.go -out ../asm_vmulss_128.s -stubs ../stub_vmulss_128.go -pkg mulss. DO NOT EDIT.

package mulss

func vmulss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
