// Code generated by command: go run asm_mulss_128.go -out ../asm_mulss_128.s -stubs ../stub_mulss_128.go -pkg mulss. DO NOT EDIT.

package mulss

func mulss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
