// Code generated by command: go run asm_vpmuldq_256.go -out ../asm_vpmuldq_256.s -stubs ../stub_vpmuldq_256.go -pkg vpmuldq. DO NOT EDIT.

package vpmuldq

func vpmuldq256(vals1 *[8]int32, vals2 *[8]int32, ret *[4]int64)
