// Code generated by command: go run asm_vpmuldq_128.go -out ../asm_vpmuldq_128.s -stubs ../stub_vpmuldq_128.go -pkg vpmuldq. DO NOT EDIT.

package vpmuldq

func vpmuldq128(vals1 *[4]int32, vals2 *[4]int32, ret *[2]int64)
