// Code generated by command: go run asm_vpshuflw_128_odds.go -out ../asm_vpshuflw_128_odds.s -stubs ../stub_vpshuflw_128_odds.go -pkg pshuflw. DO NOT EDIT.

#include "textflag.h"

// func vpshuflw128Odds(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshuflw128Odds(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFLW imm8=0xDD (odds: [w5,w7,w5,w7])
	VPSHUFLW $0xdd, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
