// Code generated by command: go run asm_vpshuflw_128_identity.go -out ../asm_vpshuflw_128_identity.s -stubs ../stub_vpshuflw_128_identity.go -pkg pshuflw. DO NOT EDIT.

#include "textflag.h"

// func vpshuflw128Identity(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshuflw128Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFLW imm8=0xE4 (identity for low words)
	VPSHUFLW $0xe4, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
