// Code generated by command: go run asm_vpshuflw_256_identity.go -out ../asm_vpshuflw_256_identity.s -stubs ../stub_vpshuflw_256_identity.go -pkg pshuflw. DO NOT EDIT.

#include "textflag.h"

// func vpshuflw256Identity(vals *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpshuflw256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFLW imm8=0xE4 (identity for low words, per 128-bit lane)
	VPSHUFLW $0xe4, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
