// Code generated by command: go run asm_vpshuflw_128_evens.go -out ../asm_vpshuflw_128_evens.s -stubs ../stub_vpshuflw_128_evens.go -pkg pshuflw. DO NOT EDIT.

#include "textflag.h"

// func vpshuflw128Evens(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshuflw128Evens(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFLW imm8=0x88 (evens: [w4,w6,w4,w6])
	VPSHUFLW $0x88, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
