// Code generated by command: go run asm_vpshuflw_128_reverse.go -out ../asm_vpshuflw_128_reverse.s -stubs ../stub_vpshuflw_128_reverse.go -pkg pshuflw. DO NOT EDIT.

#include "textflag.h"

// func vpshuflw128Reverse(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshuflw128Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFLW imm8=0x1B (reverse low words)
	VPSHUFLW $0x1b, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
