// Code generated by command: go run asm_vpshuflw_128_evens.go -out ../asm_vpshuflw_128_evens.s -stubs ../stub_vpshuflw_128_evens.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw128Evens(vals *[8]uint16, ret *[8]uint16)
