// Code generated by command: go run asm_vpshuflw_128_odds.go -out ../asm_vpshuflw_128_odds.s -stubs ../stub_vpshuflw_128_odds.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw128Odds(vals *[8]uint16, ret *[8]uint16)
