// Code generated by command: go run asm_vpshuflw_128_identity.go -out ../asm_vpshuflw_128_identity.s -stubs ../stub_vpshuflw_128_identity.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw128Identity(vals *[8]uint16, ret *[8]uint16)
