// Code generated by command: go run asm_vpshuflw_256_odds.go -out ../asm_vpshuflw_256_odds.s -stubs ../stub_vpshuflw_256_odds.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw256Odds(vals *[16]uint16, ret *[16]uint16)
