// Code generated by command: go run asm_vpshuflw_256_reverse.go -out ../asm_vpshuflw_256_reverse.s -stubs ../stub_vpshuflw_256_reverse.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw256Reverse(vals *[16]uint16, ret *[16]uint16)
