// Code generated by command: go run asm_vpshuflw_256_identity.go -out ../asm_vpshuflw_256_identity.s -stubs ../stub_vpshuflw_256_identity.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw256Identity(vals *[16]uint16, ret *[16]uint16)
