// Code generated by command: go run asm_vpshuflw_256_evens.go -out ../asm_vpshuflw_256_evens.s -stubs ../stub_vpshuflw_256_evens.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw256Evens(vals *[16]uint16, ret *[16]uint16)
