// Code generated by command: go run asm_vpshuflw_128_reverse.go -out ../asm_vpshuflw_128_reverse.s -stubs ../stub_vpshuflw_128_reverse.go -pkg pshuflw. DO NOT EDIT.

package pshuflw

func vpshuflw128Reverse(vals *[8]uint16, ret *[8]uint16)
