// Code generated by command: go run asm_vpxor_128.go -out ../asm_vpxor_128.s -stubs ../stub_vpxor_128.go -pkg pxor. DO NOT EDIT.

package pxor

func vpxor128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
