// Code generated by command: go run asm_vpxor_256.go -out ../asm_vpxor_256.s -stubs ../stub_vpxor_256.go -pkg pxor. DO NOT EDIT.

package pxor

func vpxor256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
