// Code generated by command: go run asm_vpbroadcastb_128_k.go -out ../asm_vpbroadcastb_128_k.s -stubs ../stub_vpbroadcastb_128_k.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb128K(b byte, k uint64, ret *[16]byte)
// Requires: AVX, AVX512BW, AVX512VL, SSE2
TEXT ·vpbroadcastb128K(SB), NOSPLIT, $0-24
	// load params
	MOVBQZX b+0(FP), AX
	KMOVQ   k+8(FP), K1
	MOVQ    ret+16(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Broadcast b into XMM register
	VPBROADCASTB X0, K1, X1

	// Write contents of XMM register into memory region
	VMOVDQU X1, (CX)
	RET
