// Code generated by command: go run asm_vpbroadcastb_256_k.go -out ../asm_vpbroadcastb_256_k.s -stubs ../stub_vpbroadcastb_256_k.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb256K(b byte, k uint64, ret *[32]byte)
// Requires: AVX, AVX512BW, AVX512VL, SSE2
TEXT ·vpbroadcastb256K(SB), NOSPLIT, $0-24
	// load params
	MOVBQZX b+0(FP), AX
	KMOVQ   k+8(FP), K1
	MOVQ    ret+16(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Broadcast b into YMM register
	VPBROADCASTB X0, K1, Y1

	// Write contents of YMM register into memory region
	VMOVDQU Y1, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
