// Code generated by command: go run asm_vpbroadcastb_128.go -out ../asm_vpbroadcastb_128.s -stubs ../stub_vpbroadcastb_128.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb128(b byte, ret *[16]byte)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastb128(SB), NOSPLIT, $0-16
	// load b into a 64 bit register, required for load into XMM register
	MOVBQZX b+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Load b into XMM register, required for broadcast
	MOVQ AX, X0

	// Execute the instruction being demonstrated
	VPBROADCASTB X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
