// Code generated by command: go run asm_512_k.go -out ../asm_512_k.s -stubs ../stub_512_k.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb512K(b byte, k uint64, ret *[64]byte)
// Requires: AVX, AVX512BW, AVX512F, SSE2
TEXT ·vpbroadcastb512K(SB), NOSPLIT, $0-24
	// load params
	MOVBQZX b+0(FP), AX
	KMOVQ   k+8(FP), K1
	MOVQ    ret+16(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Broadcast b into YMM register
	VPBROADCASTB X0, K1, Z1

	// Write contents of ZMM register into memory region
	VMOVDQU64 Z1, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
