// Code generated by command: go run asm_vpbroadcastb_256.go -out ../asm_vpbroadcastb_256.s -stubs ../stub_vpbroadcastb_256.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb256(b byte, ret *[32]byte)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastb256(SB), NOSPLIT, $0-16
	// load b into 64 bit register, required for load in XMM register
	MOVBQZX b+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Execute the instruction being demonstrated
	VPBROADCASTB X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
