// Code generated by command: go run asm_512.go -out ../asm_512.s -stubs ../stub_512.go -pkg vpbroadcastb. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastb512(b byte, ret *[64]byte)
// Requires: AVX, AVX2, AVX512F, AVX512VL, SSE2
TEXT ·vpbroadcastb512(SB), NOSPLIT, $0-16
	// load params
	MOVBQZX b+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Need to move b into an XMM register to work with VPBROADCASTB instruction
	MOVQ AX, X0

	// Broadcast b into ZMM register
	VPBROADCASTB X0, Y0

	// Write contents of ZMM register into memory region
	VMOVDQU64 Y0, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
