// Code generated by command: go run asm_vpbroadcastb_512.go -out ../asm_vpbroadcastb_512.s -stubs ../stub_vpbroadcastb_512.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb512(b byte, ret *[64]byte)
