// Code generated by command: go run asm_256_k.go -out ../asm_256_k.s -stubs ../stub_256_k.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb256K(b byte, k uint64, ret *[32]byte)
