// Code generated by command: go run asm_vpbroadcastb_128.go -out ../asm_vpbroadcastb_128.s -stubs ../stub_vpbroadcastb_128.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb128(b byte, ret *[16]byte)
