// Code generated by command: go run asm.go -out ../asm.s -stubs ../stub.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb128(b byte, ret *[16]byte)

func vpbroadcastb256(b byte, ret *[32]byte)

func vpbroadcastb512(b byte, ret *[64]byte)
