// Code generated by command: go run asm_vpbroadcastb_512_k.go -out ../asm_vpbroadcastb_512_k.s -stubs ../stub_vpbroadcastb_512_k.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb512K(b byte, k uint64, ret *[64]byte)
