// Code generated by command: go run asm_128_k.go -out ../asm_128_k.s -stubs ../stub_128_k.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb128K(b byte, k uint64, ret *[16]byte)
