// Code generated by command: go run asm_vpbroadcastb_256.go -out ../asm_vpbroadcastb_256.s -stubs ../stub_vpbroadcastb_256.go -pkg vpbroadcastb. DO NOT EDIT.

package vpbroadcastb

func vpbroadcastb256(b byte, ret *[32]byte)
