// Code generated by command: go run asm_vorps_128.go -out ../asm_vorps_128.s -stubs ../stub_vorps_128.go -pkg orps. DO NOT EDIT.

package orps

func vorps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
