// Code generated by command: go run asm_orps_128.go -out ../asm_orps_128.s -stubs ../stub_orps_128.go -pkg orps. DO NOT EDIT.

package orps

func orps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
