// Code generated by command: go run asm_vorps_256.go -out ../asm_vorps_256.s -stubs ../stub_vorps_256.go -pkg orps. DO NOT EDIT.

package orps

func vorps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
