// Code generated by command: go run asm_vdpps_128_all.go -out ../asm_vdpps_128_all.s -stubs ../stub_vdpps_128_all.go -pkg dpps. DO NOT EDIT.

package dpps

func vdpps128All(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
