// Code generated by command: go run asm_vblendps_128_even.go -out ../asm_vblendps_128_even.s -stubs ../stub_vblendps_128_even.go -pkg blendps. DO NOT EDIT.

#include "textflag.h"

// func vblendps128Even(base *[4]float32, blend *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vblendps128Even(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VBLENDPS 128: imm=0x05 selects even lanes (0,2) from blend; others from base
	VBLENDPS $0x05, X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
