// Code generated by command: go run asm_vblendps_256_high_half.go -out ../asm_vblendps_256_high_half.s -stubs ../stub_vblendps_256_high_half.go -pkg blendps. DO NOT EDIT.

#include "textflag.h"

// func vblendps256High_half(base *[8]float32, blend *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vblendps256High_half(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VBLENDPS 256: imm=0xF0 selects high half (lanes 4..7) from blend; others from base
	VBLENDPS $0xf0, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
