// Code generated by command: go run asm_vblendps_256_none.go -out ../asm_vblendps_256_none.s -stubs ../stub_vblendps_256_none.go -pkg blendps. DO NOT EDIT.

#include "textflag.h"

// func vblendps256None(base *[8]float32, blend *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vblendps256None(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VBLENDPS 256: imm=0x00 selects all lanes from base
	VBLENDPS $0x00, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
