// Code generated by command: go run asm_vblendps_256_odd.go -out ../asm_vblendps_256_odd.s -stubs ../stub_vblendps_256_odd.go -pkg blendps. DO NOT EDIT.

#include "textflag.h"

// func vblendps256Odd(base *[8]float32, blend *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vblendps256Odd(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VBLENDPS 256: imm=0xAA selects odd lanes (1,3,5,7) from blend; others from base
	VBLENDPS $0xaa, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
