// Code generated by command: go run asm_vblendps_256_even.go -out ../asm_vblendps_256_even.s -stubs ../stub_vblendps_256_even.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps256Even(base *[8]float32, blend *[8]float32, ret *[8]float32)
