// Code generated by command: go run asm_vblendps_256_odd.go -out ../asm_vblendps_256_odd.s -stubs ../stub_vblendps_256_odd.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps256Odd(base *[8]float32, blend *[8]float32, ret *[8]float32)
