// Code generated by command: go run asm_vblendps_128_odd.go -out ../asm_vblendps_128_odd.s -stubs ../stub_vblendps_128_odd.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps128Odd(base *[4]float32, blend *[4]float32, ret *[4]float32)
