// Code generated by command: go run asm_vblendps_256_high_half.go -out ../asm_vblendps_256_high_half.s -stubs ../stub_vblendps_256_high_half.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps256High_half(base *[8]float32, blend *[8]float32, ret *[8]float32)
