// Code generated by command: go run asm_vblendps_128_all.go -out ../asm_vblendps_128_all.s -stubs ../stub_vblendps_128_all.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps128All(base *[4]float32, blend *[4]float32, ret *[4]float32)
