// Code generated by command: go run asm_vblendps_128_even.go -out ../asm_vblendps_128_even.s -stubs ../stub_vblendps_128_even.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps128Even(base *[4]float32, blend *[4]float32, ret *[4]float32)
