// Code generated by command: go run asm_vblendps_128_low_half.go -out ../asm_vblendps_128_low_half.s -stubs ../stub_vblendps_128_low_half.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps128Low_half(base *[4]float32, blend *[4]float32, ret *[4]float32)
