// Code generated by command: go run asm_vblendps_128_none.go -out ../asm_vblendps_128_none.s -stubs ../stub_vblendps_128_none.go -pkg blendps. DO NOT EDIT.

package blendps

func vblendps128None(base *[4]float32, blend *[4]float32, ret *[4]float32)
