// Code generated by command: go run asm_vunpcklpd_128.go -out ../asm_vunpcklpd_128.s -stubs ../stub_vunpcklpd_128.go -pkg vunpcklpd. DO NOT EDIT.

package vunpcklpd

func vunpcklpd128(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
