// Code generated by command: go run asm_vunpcklpd_256.go -out ../asm_vunpcklpd_256.s -stubs ../stub_vunpcklpd_256.go -pkg vunpcklpd. DO NOT EDIT.

package vunpcklpd

func vunpcklpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
