// Code generated by command: go run asm_vpmulhuw_256.go -out ../asm_vpmulhuw_256.s -stubs ../stub_vpmulhuw_256.go -pkg pmulhuw. DO NOT EDIT.

#include "textflag.h"

// func vpmulhuw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpmulhuw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Multiply packed unsigned 16-bit integers (per 128-bit lane); keep high 16 bits
	VPMULHUW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
