// Code generated by command: go run asm_pmulhuw_128.go -out ../asm_pmulhuw_128.s -stubs ../stub_pmulhuw_128.go -pkg pmulhuw. DO NOT EDIT.

#include "textflag.h"

// func pmulhuw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
// Requires: AVX, SSE2
TEXT ·pmulhuw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Multiply packed unsigned 16-bit integers and keep high 16 bits of 32-bit products
	PMULHUW X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
