// Code generated by command: go run asm_vpmulhuw_128.go -out ../asm_vpmulhuw_128.s -stubs ../stub_vpmulhuw_128.go -pkg pmulhuw. DO NOT EDIT.

package pmulhuw

func vpmulhuw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
