// Code generated by command: go run asm_vpmulhuw_256.go -out ../asm_vpmulhuw_256.s -stubs ../stub_vpmulhuw_256.go -pkg pmulhuw. DO NOT EDIT.

package pmulhuw

func vpmulhuw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
