// Code generated by command: go run asm_pmulhuw_128.go -out ../asm_pmulhuw_128.s -stubs ../stub_pmulhuw_128.go -pkg pmulhuw. DO NOT EDIT.

package pmulhuw

func pmulhuw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
