// Code generated by command: go run asm_rsqrtps_128.go -out ../asm_rsqrtps_128.s -stubs ../stub_rsqrtps_128.go -pkg rsqrtps. DO NOT EDIT.

#include "textflag.h"

// func rsqrtps128(vals *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·rsqrtps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal square root of packed float32 values: regX1 = 1.0 / sqrt(regX1)
	RSQRTPS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
