// Code generated by command: go run asm_vrsqrtps_128.go -out ../asm_vrsqrtps_128.s -stubs ../stub_vrsqrtps_128.go -pkg rsqrtps. DO NOT EDIT.

#include "textflag.h"

// func vrsqrtps128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vrsqrtps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal square root of packed float32 values with VEX encoding: regX1 = 1.0 / sqrt(regX1)
	VRSQRTPS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
