// Code generated by command: go run asm_vrsqrtps_256.go -out ../asm_vrsqrtps_256.s -stubs ../stub_vrsqrtps_256.go -pkg rsqrtps. DO NOT EDIT.

package rsqrtps

func vrsqrtps256(vals *[8]float32, ret *[8]float32)
