// Code generated by command: go run asm_rsqrtps_128.go -out ../asm_rsqrtps_128.s -stubs ../stub_rsqrtps_128.go -pkg rsqrtps. DO NOT EDIT.

package rsqrtps

func rsqrtps128(vals *[4]float32, ret *[4]float32)
