// Code generated by command: go run asm_vpmaddubsw_128.go -out ../asm_vpmaddubsw_128.s -stubs ../stub_vpmaddubsw_128.go -pkg pmaddubsw. DO NOT EDIT.

#include "textflag.h"

// func vpmaddubsw128(u *[16]uint8, s *[16]uint8, ret *[8]int16)
// Requires: AVX
TEXT ·vpmaddubsw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ u+0(FP), AX
	MOVQ s+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPMADDUBSW: (unsigned u8 * signed i8) pairwise -> add adjacent -> saturated i16
	VPMADDUBSW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
