// Code generated by command: go run asm_vpmaddubsw_256.go -out ../asm_vpmaddubsw_256.s -stubs ../stub_vpmaddubsw_256.go -pkg pmaddubsw. DO NOT EDIT.

#include "textflag.h"

// func vpmaddubsw256(u *[32]uint8, s *[32]uint8, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpmaddubsw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ u+0(FP), AX
	MOVQ s+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPMADDUBSW: (unsigned u8 * signed i8) pairwise -> add adjacent -> saturated i16 (per 128-bit lane)
	VPMADDUBSW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
