// Code generated by command: go run asm_vpmaddubsw_256.go -out ../asm_vpmaddubsw_256.s -stubs ../stub_vpmaddubsw_256.go -pkg pmaddubsw. DO NOT EDIT.

package pmaddubsw

func vpmaddubsw256(u *[32]uint8, s *[32]uint8, ret *[16]int16)
