// Code generated by command: go run asm_vpmaddubsw_128.go -out ../asm_vpmaddubsw_128.s -stubs ../stub_vpmaddubsw_128.go -pkg pmaddubsw. DO NOT EDIT.

package pmaddubsw

func vpmaddubsw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[8]int16)
