// Code generated by command: go run asm_vpmaddubsw_256.go -out ../asm_vpmaddubsw_256.s -stubs ../stub_vpmaddubsw_256.go -pkg pmaddubsw. DO NOT EDIT.

package pmaddubsw

func vpmaddubsw256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[16]int16)
