// Code generated by command: go run asm_vhsubpd_128.go -out ../asm_vhsubpd_128.s -stubs ../stub_vhsubpd_128.go -pkg vhsubpd. DO NOT EDIT.

package vhsubpd

func vhsubpd128(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
