// Code generated by command: go run asm_vhsubpd_256.go -out ../asm_vhsubpd_256.s -stubs ../stub_vhsubpd_256.go -pkg vhsubpd. DO NOT EDIT.

package vhsubpd

func vhsubpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
