// Code generated by command: go run asm_vaddsubps_256.go -out ../asm_vaddsubps_256.s -stubs ../stub_vaddsubps_256.go -pkg vaddsubps. DO NOT EDIT.

package vaddsubps

func vaddsubps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
