// Code generated by command: go run asm_vblendvps_128.go -out ../asm_vblendvps_128.s -stubs ../stub_vblendvps_128.go -pkg blendvps. DO NOT EDIT.

#include "textflag.h"

// func vblendvps128(base *[4]float32, blend *[4]float32, mask *[4]uint32, ret *[4]float32)
// Requires: AVX
TEXT ·vblendvps128(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1
	VMOVDQA (DX), X2

	// VBLENDVPS 128: blend using per-lane sign-bit mask
	VBLENDVPS X2, X1, X0, X0

	// Store result
	VMOVDQA X0, (BX)

	// Return from function
	RET
