// Code generated by command: go run asm_vblendvps_256.go -out ../asm_vblendvps_256.s -stubs ../stub_vblendvps_256.go -pkg blendvps. DO NOT EDIT.

#include "textflag.h"

// func vblendvps256(base *[8]float32, blend *[8]float32, mask *[8]uint32, ret *[8]float32)
// Requires: AVX
TEXT ·vblendvps256(SB), NOSPLIT, $0-32
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load base, blend and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1
	VMOVDQA (DX), Y2

	// VBLENDVPS 256: blend using per-lane sign-bit mask
	VBLENDVPS Y2, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
