// Code generated by command: go run asm_vblendvps_256.go -out ../asm_vblendvps_256.s -stubs ../stub_vblendvps_256.go -pkg blendvps. DO NOT EDIT.

package blendvps

func vblendvps256(base *[8]float32, blend *[8]float32, mask *[8]uint32, ret *[8]float32)
