// Code generated by command: go run asm_vblendvps_128.go -out ../asm_vblendvps_128.s -stubs ../stub_vblendvps_128.go -pkg blendvps. DO NOT EDIT.

package blendvps

func vblendvps128(base *[4]float32, blend *[4]float32, mask *[4]uint32, ret *[4]float32)
