// Code generated by command: go run asm_vminss_128.go -out ../asm_vminss_128.s -stubs ../stub_vminss_128.go -pkg minss. DO NOT EDIT.

package minss

func vminss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
