// Code generated by command: go run asm_minss_128.go -out ../asm_minss_128.s -stubs ../stub_minss_128.go -pkg minss. DO NOT EDIT.

package minss

func minss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
