// Code generated by command: go run asm_vpextrw_128_one_idx.go -out ../asm_vpextrw_128_one_idx.s -stubs ../stub_vpextrw_128_one_idx.go -pkg pextrw. DO NOT EDIT.

#include "textflag.h"

// func vpextrw128One_idx(vals *[8]uint16, ret *uint32)
// Requires: AVX
TEXT ·vpextrw128One_idx(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Extract 16-bit word at index 1 into 32-bit GPR (zero-extended, VEX)
	VPEXTRW $0x01, X0, AX

	// Write result into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
