// Code generated by command: go run asm_pextrw_128_three_idx.go -out ../asm_pextrw_128_three_idx.s -stubs ../stub_pextrw_128_three_idx.go -pkg pextrw. DO NOT EDIT.

#include "textflag.h"

// func pextrw128Three_idx(vals *[8]uint16, ret *uint32)
// Requires: AVX, SSE4.1
TEXT ·pextrw128Three_idx(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Extract 16-bit word at index 3 into 32-bit GPR (zero-extended)
	PEXTRW $0x03, X0, AX

	// Write result into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
