// Code generated by command: go run asm_pextrw_128_six_idx.go -out ../asm_pextrw_128_six_idx.s -stubs ../stub_pextrw_128_six_idx.go -pkg pextrw. DO NOT EDIT.

package pextrw

func pextrw128Six_idx(vals *[8]uint16, ret *uint32)
