// Code generated by command: go run asm_pextrw_128_four_idx.go -out ../asm_pextrw_128_four_idx.s -stubs ../stub_pextrw_128_four_idx.go -pkg pextrw. DO NOT EDIT.

package pextrw

func pextrw128Four_idx(vals *[8]uint16, ret *uint32)
