// Code generated by command: go run asm_vpextrw_128_two_idx.go -out ../asm_vpextrw_128_two_idx.s -stubs ../stub_vpextrw_128_two_idx.go -pkg pextrw. DO NOT EDIT.

package pextrw

func vpextrw128Two_idx(vals *[8]uint16, ret *uint32)
