// Code generated by command: go run asm_vpextrw_128_six_idx.go -out ../asm_vpextrw_128_six_idx.s -stubs ../stub_vpextrw_128_six_idx.go -pkg pextrw. DO NOT EDIT.

package pextrw

func vpextrw128Six_idx(vals *[8]uint16, ret *uint32)
