// Code generated by command: go run asm_vcvtps2pd_128.go -out ../asm_vcvtps2pd_128.s -stubs ../stub_vcvtps2pd_128.go -pkg cvtps2pd. DO NOT EDIT.

#include "textflag.h"

// func vcvtps2pd128(vals *[4]float32, ret *[2]float64)
// Requires: AVX
TEXT ·vcvtps2pd128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTPS2PD X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
