// Code generated by command: go run asm_vcvtps2pd_256.go -out ../asm_vcvtps2pd_256.s -stubs ../stub_vcvtps2pd_256.go -pkg cvtps2pd. DO NOT EDIT.

#include "textflag.h"

// func vcvtps2pd256(vals *[4]float32, ret *[4]float64)
// Requires: AVX
TEXT ·vcvtps2pd256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VCVTPS2PD X0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
