// Code generated by command: go run asm_vcvtps2pd_128.go -out ../asm_vcvtps2pd_128.s -stubs ../stub_vcvtps2pd_128.go -pkg cvtps2pd. DO NOT EDIT.

package cvtps2pd

func vcvtps2pd128(vals *[4]float32, ret *[2]float64)
