// Code generated by command: go run asm_vcvtps2pd_256.go -out ../asm_vcvtps2pd_256.s -stubs ../stub_vcvtps2pd_256.go -pkg cvtps2pd. DO NOT EDIT.

package cvtps2pd

func vcvtps2pd256(vals *[4]float32, ret *[4]float64)
