// Code generated by command: go run asm_vmulps_256.go -out ../asm_vmulps_256.s -stubs ../stub_vmulps_256.go -pkg mulps. DO NOT EDIT.

#include "textflag.h"

// func vmulps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vmulps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Multiply packed float32 values with VEX encoding: regY2 = regY1 * regY2
	VMULPS Y0, Y1, Y1

	// Write results into return memory address
	VMOVDQA Y1, (DX)

	// Return from function
	RET
