// Code generated by command: go run asm_mulps_128.go -out ../asm_mulps_128.s -stubs ../stub_mulps_128.go -pkg mulps. DO NOT EDIT.

package mulps

func mulps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
