// Code generated by command: go run asm_vmulps_128.go -out ../asm_vmulps_128.s -stubs ../stub_vmulps_128.go -pkg mulps. DO NOT EDIT.

package mulps

func vmulps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
