// Code generated by command: go run asm_vmulps_256.go -out ../asm_vmulps_256.s -stubs ../stub_vmulps_256.go -pkg mulps. DO NOT EDIT.

package mulps

func vmulps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
