// Code generated by command: go run asm_vbroadcastsd_256_m64.go -out ../asm_vbroadcastsd_256_m64.s -stubs ../stub_vbroadcastsd_256_m64.go -pkg vbroadcast. DO NOT EDIT.

#include "textflag.h"

// func vbroadcastsd256M64(scalar *float64, ret *[4]float64)
// Requires: AVX
TEXT ·vbroadcastsd256M64(SB), NOSPLIT, $0-16
	// load params
	MOVQ scalar+0(FP), AX
	MOVQ ret+8(FP), CX

	// Broadcast 64-bit scalar from memory to all lanes of YMM (4 lanes)
	VBROADCASTSD (AX), Y0

	// Write result into return memory address
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
