// Code generated by command: go run asm_vbroadcastss_128_m32.go -out ../asm_vbroadcastss_128_m32.s -stubs ../stub_vbroadcastss_128_m32.go -pkg vbroadcast. DO NOT EDIT.

#include "textflag.h"

// func vbroadcastss128M32(scalar *float32, ret *[4]float32)
// Requires: AVX
TEXT ·vbroadcastss128M32(SB), NOSPLIT, $0-16
	// load params
	MOVQ scalar+0(FP), AX
	MOVQ ret+8(FP), CX

	// Broadcast 32-bit scalar from memory to all lanes of XMM
	VBROADCASTSS (AX), X0

	// Write result into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
