// Code generated by command: go run asm_vbroadcastsf128_256_m128.go -out ../asm_vbroadcastsf128_256_m128.s -stubs ../stub_vbroadcastsf128_256_m128.go -pkg vbroadcast. DO NOT EDIT.

#include "textflag.h"

// func vbroadcastsf128256M128(block *[4]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vbroadcastsf128256M128(SB), NOSPLIT, $0-16
	// load params
	MOVQ block+0(FP), AX
	MOVQ ret+8(FP), CX

	// Broadcast 128-bit block from memory to both 128-bit lanes of YMM
	VBROADCASTF128 (AX), Y0

	// Write result into return memory address
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
