// Code generated by command: go run asm_vbroadcastsf128_256_m128.go -out ../asm_vbroadcastsf128_256_m128.s -stubs ../stub_vbroadcastsf128_256_m128.go -pkg vbroadcast. DO NOT EDIT.

package vbroadcast

func vbroadcastsf128256M128(block *[4]float32, ret *[8]float32)
