// Code generated by command: go run asm_vbroadcastsd_256_m64.go -out ../asm_vbroadcastsd_256_m64.s -stubs ../stub_vbroadcastsd_256_m64.go -pkg vbroadcast. DO NOT EDIT.

package vbroadcast

func vbroadcastsd256M64(scalar *float64, ret *[4]float64)
