// Code generated by command: go run asm_vbroadcastss_256_m32.go -out ../asm_vbroadcastss_256_m32.s -stubs ../stub_vbroadcastss_256_m32.go -pkg vbroadcast. DO NOT EDIT.

package vbroadcast

func vbroadcastss256M32(scalar *float32, ret *[8]float32)
