// Code generated by command: go run asm_vandps_256.go -out ../asm_vandps_256.s -stubs ../stub_vandps_256.go -pkg andps. DO NOT EDIT.

#include "textflag.h"

// func vandps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vandps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Bitwise AND with VEX encoding (per 128-bit lane)
	VANDPS Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
