// Code generated by command: go run asm_andps_128.go -out ../asm_andps_128.s -stubs ../stub_andps_128.go -pkg andps. DO NOT EDIT.

package andps

func andps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
