// Code generated by command: go run asm_vandps_128.go -out ../asm_vandps_128.s -stubs ../stub_vandps_128.go -pkg andps. DO NOT EDIT.

package andps

func vandps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
