// Code generated by command: go run asm_vandps_256.go -out ../asm_vandps_256.s -stubs ../stub_vandps_256.go -pkg andps. DO NOT EDIT.

package andps

func vandps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
