// Code generated by command: go run asm_vpavgb_256.go -out ../asm_vpavgb_256.s -stubs ../stub_vpavgb_256.go -pkg pavgb. DO NOT EDIT.

#include "textflag.h"

// func vpavgb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpavgb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Average packed unsigned bytes with VEX (per 128-bit lane)
	VPAVGB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
