// Code generated by command: go run asm_pavgb_128.go -out ../asm_pavgb_128.s -stubs ../stub_pavgb_128.go -pkg pavgb. DO NOT EDIT.

#include "textflag.h"

// func pavgb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
// Requires: AVX, SSE2
TEXT ·pavgb128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Average packed unsigned bytes with rounding: (a+b+1)>>1
	PAVGB X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
