// Code generated by command: go run asm_vpavgb_128.go -out ../asm_vpavgb_128.s -stubs ../stub_vpavgb_128.go -pkg pavgb. DO NOT EDIT.

package pavgb

func vpavgb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
