// Code generated by command: go run asm_vpavgb_256.go -out ../asm_vpavgb_256.s -stubs ../stub_vpavgb_256.go -pkg pavgb. DO NOT EDIT.

package pavgb

func vpavgb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
