// Code generated by command: go run asm_pavgb_128.go -out ../asm_pavgb_128.s -stubs ../stub_pavgb_128.go -pkg pavgb. DO NOT EDIT.

package pavgb

func pavgb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
