// Code generated by command: go run asm_vpand_256.go -out ../asm_vpand_256.s -stubs ../stub_vpand_256.go -pkg pand. DO NOT EDIT.

package pand

func vpand256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
