// Code generated by command: go run asm_vpand_128.go -out ../asm_vpand_128.s -stubs ../stub_vpand_128.go -pkg pand. DO NOT EDIT.

package pand

func vpand128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
