// Code generated by command: go run asm_vpmaddhw_256.go -out ../asm_vpmaddhw_256.s -stubs ../stub_vpmaddhw_256.go -pkg pmaddhw. DO NOT EDIT.

#include "textflag.h"

// func vpmaddhw256(vals1 *[16]int16, vals2 *[16]int16, ret *[8]int32)
// Requires: AVX, AVX2
TEXT ·vpmaddhw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPMADDWD: multiply signed 16-bit pairs and add adjacent products -> 32-bit results (per 128-bit lane)
	VPMADDWD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
