// Code generated by command: go run asm_vpmaddhw_128.go -out ../asm_vpmaddhw_128.s -stubs ../stub_vpmaddhw_128.go -pkg pmaddhw. DO NOT EDIT.

#include "textflag.h"

// func vpmaddhw128(vals1 *[8]int16, vals2 *[8]int16, ret *[4]int32)
// Requires: AVX
TEXT ·vpmaddhw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPMADDWD: multiply signed 16-bit pairs and add adjacent products -> 32-bit results
	VPMADDWD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
