// Code generated by command: go run asm_vpmaddhw_256.go -out ../asm_vpmaddhw_256.s -stubs ../stub_vpmaddhw_256.go -pkg pmaddhw. DO NOT EDIT.

package pmaddhw

func vpmaddhw256(vals1 *[16]int16, vals2 *[16]int16, ret *[8]int32)
