// Code generated by command: go run asm_vmovaps_128.go -out ../asm_vmovaps_128.s -stubs ../stub_vmovaps_128.go -pkg movaps. DO NOT EDIT.

#include "textflag.h"

// func vmovaps128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmovaps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPS (AX), X0

	// Move vals into another XMM register
	VMOVAPS X0, X0

	// Write contents of the second XMM register into memory region
	VMOVAPS X0, (CX)
	RET
