// Code generated by command: go run asm_256_loadstore_vmovaps.go -out ../asm_256_loadstore_vmovaps.s -stubs ../stub_256_loadstore_vmovaps.go -pkg movaps. DO NOT EDIT.

#include "textflag.h"

// func movaps256LoadStoreVmovaps(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·movaps256LoadStoreVmovaps(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPS (AX), Y0

	// Move vals into another YMM register
	VMOVAPS Y0, Y0

	// Write contents of the second YMM register into memory region
	VMOVAPS Y0, (CX)
	RET
