// Code generated by command: go run asm_movaps_128.go -out ../asm_movaps_128.s -stubs ../stub_movaps_128.go -pkg movaps. DO NOT EDIT.

#include "textflag.h"

// func movaps128(vals *[4]float32, ret *[4]float32)
// Requires: SSE
TEXT ·movaps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVAPS (AX), X0

	// Move vals into another XMM register
	MOVAPS X0, X0

	// Write contents of the second XMM register into memory region
	MOVAPS X0, (CX)
	RET
