// Code generated by command: go run asm_128_loadstore_vmovaps.go -out ../asm_128_loadstore_vmovaps.s -stubs ../stub_128_loadstore_vmovaps.go -pkg movaps. DO NOT EDIT.

#include "textflag.h"

// func movaps128LoadStoreVmovaps(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·movaps128LoadStoreVmovaps(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPS (AX), X0

	// Move vals into another XMM register
	VMOVAPS X0, X0

	// Write contents of the second XMM register into memory region
	VMOVAPS X0, (CX)
	RET
