// Code generated by command: go run asm_128_loadstore_movaps.go -out ../asm_128_loadstore_movaps.s -stubs ../stub_128_loadstore_movaps.go -pkg movaps. DO NOT EDIT.

package movaps

func movaps128LoadStoreMovaps(vals *[4]float32, ret *[4]float32)
