// Code generated by command: go run asm_vmovaps_256.go -out ../asm_vmovaps_256.s -stubs ../stub_vmovaps_256.go -pkg movaps. DO NOT EDIT.

package movaps

func vmovaps256(vals *[8]float32, ret *[8]float32)
