// Code generated by command: go run asm_128_loadstore_vmovaps.go -out ../asm_128_loadstore_vmovaps.s -stubs ../stub_128_loadstore_vmovaps.go -pkg movaps. DO NOT EDIT.

package movaps

func movaps128LoadStoreVmovaps(vals *[4]float32, ret *[4]float32)
