// Code generated by command: go run asm_vmovaps_128.go -out ../asm_vmovaps_128.s -stubs ../stub_vmovaps_128.go -pkg movaps. DO NOT EDIT.

package movaps

func vmovaps128(vals *[4]float32, ret *[4]float32)
