// Code generated by command: go run asm_256_loadstore_vmovaps.go -out ../asm_256_loadstore_vmovaps.s -stubs ../stub_256_loadstore_vmovaps.go -pkg movaps. DO NOT EDIT.

package movaps

func movaps256LoadStoreVmovaps(vals *[8]float32, ret *[8]float32)
