// Code generated by command: go run asm_movaps_128.go -out ../asm_movaps_128.s -stubs ../stub_movaps_128.go -pkg movaps. DO NOT EDIT.

package movaps

func movaps128(vals *[4]float32, ret *[4]float32)
