// Code generated by command: go run asm_vroundpd_256_two.go -out ../asm_vroundpd_256_two.s -stubs ../stub_vroundpd_256_two.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundpd256Two(vals *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vroundpd256Two(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVAPD (AX), Y0

	// Round packed doubles imm8=2 (ceil)
	VROUNDPD $0x02, Y0, Y0

	// Write results into return memory address
	VMOVAPD Y0, (CX)
	VZEROUPPER

	// Return from function
	RET
