// Code generated by command: go run asm_vroundpd_128_three.go -out ../asm_vroundpd_128_three.s -stubs ../stub_vroundpd_128_three.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundpd128Three(vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vroundpd128Three(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPD (AX), X0

	// Round packed doubles imm8=3 (truncate)
	VROUNDPD $0x03, X0, X0

	// Write results into return memory address
	VMOVAPD X0, (CX)

	// Return from function
	RET
