// Code generated by command: go run asm_vroundps_128_two.go -out ../asm_vroundps_128_two.s -stubs ../stub_vroundps_128_two.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundps128Two(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vroundps128Two(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPS (AX), X0

	// Round packed singles imm8=2 (ceil)
	VROUNDPS $0x02, X0, X0

	// Write results into return memory address
	VMOVAPS X0, (CX)

	// Return from function
	RET
