// Code generated by command: go run asm_vroundpd_256_one.go -out ../asm_vroundpd_256_one.s -stubs ../stub_vroundpd_256_one.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundpd256One(vals *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vroundpd256One(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVAPD (AX), Y0

	// Round packed doubles imm8=1 (floor)
	VROUNDPD $0x01, Y0, Y0

	// Write results into return memory address
	VMOVAPD Y0, (CX)
	VZEROUPPER

	// Return from function
	RET
