// Code generated by command: go run asm_vroundpd_128_one.go -out ../asm_vroundpd_128_one.s -stubs ../stub_vroundpd_128_one.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundpd128One(vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vroundpd128One(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPD (AX), X0

	// Round packed doubles imm8=1 (floor)
	VROUNDPD $0x01, X0, X0

	// Write results into return memory address
	VMOVAPD X0, (CX)

	// Return from function
	RET
