// Code generated by command: go run asm_vroundps_256_zero.go -out ../asm_vroundps_256_zero.s -stubs ../stub_vroundps_256_zero.go -pkg roundp. DO NOT EDIT.

#include "textflag.h"

// func vroundps256Zero(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vroundps256Zero(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVAPS (AX), Y0

	// Round packed singles imm8=0 (nearest)
	VROUNDPS $0x00, Y0, Y0

	// Write results into return memory address
	VMOVAPS Y0, (CX)
	VZEROUPPER

	// Return from function
	RET
