// Code generated by command: go run asm_vroundpd_256_two.go -out ../asm_vroundpd_256_two.s -stubs ../stub_vroundpd_256_two.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd256Two(vals *[4]float64, ret *[4]float64)
