// Code generated by command: go run asm_vroundps_128_one.go -out ../asm_vroundps_128_one.s -stubs ../stub_vroundps_128_one.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps128One(vals *[4]float32, ret *[4]float32)
