// Code generated by command: go run asm_vroundpd_128_zero.go -out ../asm_vroundpd_128_zero.s -stubs ../stub_vroundpd_128_zero.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd128Zero(vals *[2]float64, ret *[2]float64)
