// Code generated by command: go run asm_vroundps_128_two.go -out ../asm_vroundps_128_two.s -stubs ../stub_vroundps_128_two.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps128Two(vals *[4]float32, ret *[4]float32)
