// Code generated by command: go run asm_vroundps_256_three.go -out ../asm_vroundps_256_three.s -stubs ../stub_vroundps_256_three.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps256Three(vals *[8]float32, ret *[8]float32)
