// Code generated by command: go run asm_vroundps_256_zero.go -out ../asm_vroundps_256_zero.s -stubs ../stub_vroundps_256_zero.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps256Zero(vals *[8]float32, ret *[8]float32)
