// Code generated by command: go run asm_vroundps_128_three.go -out ../asm_vroundps_128_three.s -stubs ../stub_vroundps_128_three.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps128Three(vals *[4]float32, ret *[4]float32)
