// Code generated by command: go run asm_vroundpd_128_one.go -out ../asm_vroundpd_128_one.s -stubs ../stub_vroundpd_128_one.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd128One(vals *[2]float64, ret *[2]float64)
