// Code generated by command: go run asm_vroundpd_128_two.go -out ../asm_vroundpd_128_two.s -stubs ../stub_vroundpd_128_two.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd128Two(vals *[2]float64, ret *[2]float64)
