// Code generated by command: go run asm_vroundpd_256_three.go -out ../asm_vroundpd_256_three.s -stubs ../stub_vroundpd_256_three.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd256Three(vals *[4]float64, ret *[4]float64)
