// Code generated by command: go run asm_vroundps_128_zero.go -out ../asm_vroundps_128_zero.s -stubs ../stub_vroundps_128_zero.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps128Zero(vals *[4]float32, ret *[4]float32)
