// Code generated by command: go run asm_vroundpd_256_one.go -out ../asm_vroundpd_256_one.s -stubs ../stub_vroundpd_256_one.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd256One(vals *[4]float64, ret *[4]float64)
