// Code generated by command: go run asm_vroundps_256_one.go -out ../asm_vroundps_256_one.s -stubs ../stub_vroundps_256_one.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps256One(vals *[8]float32, ret *[8]float32)
