// Code generated by command: go run asm_vroundpd_128_three.go -out ../asm_vroundpd_128_three.s -stubs ../stub_vroundpd_128_three.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd128Three(vals *[2]float64, ret *[2]float64)
