// Code generated by command: go run asm_vroundps_256_two.go -out ../asm_vroundps_256_two.s -stubs ../stub_vroundps_256_two.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundps256Two(vals *[8]float32, ret *[8]float32)
