// Code generated by command: go run asm_vroundpd_256_zero.go -out ../asm_vroundpd_256_zero.s -stubs ../stub_vroundpd_256_zero.go -pkg roundp. DO NOT EDIT.

package roundp

func vroundpd256Zero(vals *[4]float64, ret *[4]float64)
