// Code generated by command: go run asm_vaddss_128.go -out ../asm_vaddss_128.s -stubs ../stub_vaddss_128.go -pkg addss. DO NOT EDIT.

package addss

func vaddss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
