// Code generated by command: go run asm_vpmuludq_256.go -out ../asm_vpmuludq_256.s -stubs ../stub_vpmuludq_256.go -pkg pmuludq. DO NOT EDIT.

#include "textflag.h"

// func vpmuludq256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpmuludq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPMULUDQ: multiply pairs of unsigned doublewords, producing 64-bit results in even lanes
	VPMULUDQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
