// Code generated by command: go run asm_vpmuludq_128.go -out ../asm_vpmuludq_128.s -stubs ../stub_vpmuludq_128.go -pkg pmuludq. DO NOT EDIT.

package pmuludq

func vpmuludq128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[2]uint64)
