// Code generated by command: go run asm_vpmuludq_256.go -out ../asm_vpmuludq_256.s -stubs ../stub_vpmuludq_256.go -pkg pmuludq. DO NOT EDIT.

package pmuludq

func vpmuludq256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[4]uint64)
