// Code generated by command: go run asm_vpsubd_256.go -out ../asm_vpsubd_256.s -stubs ../stub_vpsubd_256.go -pkg psub. DO NOT EDIT.

#include "textflag.h"

// func vpsubd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpsubd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSUBD: subtract packed doublewords
	VPSUBD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
