// Code generated by command: go run asm_vpsubb_256.go -out ../asm_vpsubb_256.s -stubs ../stub_vpsubb_256.go -pkg psub. DO NOT EDIT.

package psub

func vpsubb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
