// Code generated by command: go run asm_vpsubd_256.go -out ../asm_vpsubd_256.s -stubs ../stub_vpsubd_256.go -pkg psub. DO NOT EDIT.

package psub

func vpsubd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
