// Code generated by command: go run asm_vpsubw_256.go -out ../asm_vpsubw_256.s -stubs ../stub_vpsubw_256.go -pkg psub. DO NOT EDIT.

package psub

func vpsubw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
