// Code generated by command: go run asm_vpsubq_256.go -out ../asm_vpsubq_256.s -stubs ../stub_vpsubq_256.go -pkg psub. DO NOT EDIT.

package psub

func vpsubq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
