// Code generated by command: go run asm_vpsubd_128.go -out ../asm_vpsubd_128.s -stubs ../stub_vpsubd_128.go -pkg psub. DO NOT EDIT.

package psub

func vpsubd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
