// Code generated by command: go run asm_vpsubb_128.go -out ../asm_vpsubb_128.s -stubs ../stub_vpsubb_128.go -pkg psub. DO NOT EDIT.

package psub

func vpsubb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
