// Code generated by command: go run asm_vpsubw_128.go -out ../asm_vpsubw_128.s -stubs ../stub_vpsubw_128.go -pkg psub. DO NOT EDIT.

package psub

func vpsubw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
