// Code generated by command: go run asm_vmaxss_128.go -out ../asm_vmaxss_128.s -stubs ../stub_vmaxss_128.go -pkg maxss. DO NOT EDIT.

#include "textflag.h"

// func vmaxss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmaxss128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Compare and return maximum scalar single precision values using VEX encoding
	VMAXSS X0, X1, X1

	// Write results into return memory address
	VMOVDQA X1, (DX)

	// Return from function
	RET
