// Code generated by command: go run asm_vmaxss_128.go -out ../asm_vmaxss_128.s -stubs ../stub_vmaxss_128.go -pkg maxss. DO NOT EDIT.

package maxss

func vmaxss128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
