// Code generated by command: go run asm_vcvttss2si_128_int32.go -out ../asm_vcvttss2si_128_int32.s -stubs ../stub_vcvttss2si_128_int32.go -pkg cvttss2si. DO NOT EDIT.

#include "textflag.h"

// func vcvttss2si128Int32(vals *[4]float32, ret *int32)
// Requires: AVX
TEXT ·vcvttss2si128Int32(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Truncate scalar single (lowest lane) to signed 32-bit integer
	VCVTTSS2SI X0, AX

	// Write result to return memory address
	MOVL AX, (CX)

	// Return from function
	RET
