// Code generated by command: go run asm_vcvttss2si_128_int32.go -out ../asm_vcvttss2si_128_int32.s -stubs ../stub_vcvttss2si_128_int32.go -pkg cvttss2si. DO NOT EDIT.

package cvttss2si

func vcvttss2si128Int32(vals *[4]float32, ret *int32)
