// Code generated by command: go run asm_vextracti128_256_one.go -out ../asm_vextracti128_256_one.s -stubs ../stub_vextracti128_256_one.go -pkg vextracti128. DO NOT EDIT.

#include "textflag.h"

// func vextracti128256One(vals256 *[8]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vextracti128256One(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals256+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals256 into YMM register
	VMOVDQU (AX), Y0

	// Extract upper 128-bit lane (1) from YMM to memory
	VEXTRACTI128 $0x01, Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER
	RET
