// Code generated by command: go run asm_vextracti128_256_one.go -out ../asm_vextracti128_256_one.s -stubs ../stub_vextracti128_256_one.go -pkg vextracti128. DO NOT EDIT.

package vextracti128

func vextracti128256One(vals256 *[8]uint32, ret *[4]uint32)
