// Code generated by command: go run asm_vperm2f128_128_lowb_highb.go -out ../asm_vperm2f128_128_lowb_highb.s -stubs ../stub_vperm2f128_128_lowb_highb.go -pkg vperm2f128. DO NOT EDIT.

#include "textflag.h"

// func vperm2f128128Lowb_highb(valsA *[8]float32, valsB *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vperm2f128128Lowb_highb(SB), NOSPLIT, $0-24
	// load params
	MOVQ valsA+0(FP), AX
	MOVQ valsB+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load A and B into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERM2F128 imm: low=b.low (10), high=b.high (11) → imm=0x32
	VPERM2F128 $0x32, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// Return from function
	RET
