// Code generated by command: go run asm_vperm2f128_256_zeroed_zeroed.go -out ../asm_vperm2f128_256_zeroed_zeroed.s -stubs ../stub_vperm2f128_256_zeroed_zeroed.go -pkg vperm2f128. DO NOT EDIT.

#include "textflag.h"

// func vperm2f128256Zeroed_zeroed(valsA *[8]float32, valsB *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vperm2f128256Zeroed_zeroed(SB), NOSPLIT, $0-24
	// load params
	MOVQ valsA+0(FP), AX
	MOVQ valsB+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load A and B into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERM2F128 imm: low=zero (0100), high=zero (0100) → imm=0x88
	VPERM2F128 $0x88, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
