// Code generated by command: go run asm_vperm2f128_128_lowb_lowb.go -out ../asm_vperm2f128_128_lowb_lowb.s -stubs ../stub_vperm2f128_128_lowb_lowb.go -pkg vperm2f128. DO NOT EDIT.

package vperm2f128

func vperm2f128128Lowb_lowb(valsA *[8]float32, valsB *[8]float32, ret *[8]float32)
