// Code generated by command: go run asm_vperm2f128_256_highb_highb.go -out ../asm_vperm2f128_256_highb_highb.s -stubs ../stub_vperm2f128_256_highb_highb.go -pkg vperm2f128. DO NOT EDIT.

package vperm2f128

func vperm2f128256Highb_highb(valsA *[8]float32, valsB *[8]float32, ret *[8]float32)
