// Code generated by command: go run asm_vperm2f128_128_lowa_lowa.go -out ../asm_vperm2f128_128_lowa_lowa.s -stubs ../stub_vperm2f128_128_lowa_lowa.go -pkg vperm2f128. DO NOT EDIT.

package vperm2f128

func vperm2f128128Lowa_lowa(valsA *[8]float32, valsB *[8]float32, ret *[8]float32)
