// Code generated by command: go run asm_vhsubps_128.go -out ../asm_vhsubps_128.s -stubs ../stub_vhsubps_128.go -pkg vhsubps. DO NOT EDIT.

package vhsubps

func vhsubps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
