// Code generated by command: go run asm_vhsubps_256.go -out ../asm_vhsubps_256.s -stubs ../stub_vhsubps_256.go -pkg vhsubps. DO NOT EDIT.

package vhsubps

func vhsubps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
