// Code generated by command: go run asm_movmskps_128.go -out ../asm_movmskps_128.s -stubs ../stub_movmskps_128.go -pkg movmskps. DO NOT EDIT.

#include "textflag.h"

// func movmskps128(vals *[4]float32, ret *[4]byte)
// Requires: SSE
TEXT ·movmskps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVAPS (AX), X0

	// Extract sign mask values from vals
	MOVMSKPS X0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
