// Code generated by command: go run asm_vmovmskps_256.go -out ../asm_vmovmskps_256.s -stubs ../stub_vmovmskps_256.go -pkg movmskps. DO NOT EDIT.

#include "textflag.h"

// func vmovmskps256(vals *[8]float32, ret *[4]byte)
// Requires: AVX
TEXT ·vmovmskps256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVAPS (AX), Y0

	// Extract sign mask values from vals
	VMOVMSKPS Y0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
