// Code generated by command: go run asm_vmovmskps_128.go -out ../asm_vmovmskps_128.s -stubs ../stub_vmovmskps_128.go -pkg movmskps. DO NOT EDIT.

#include "textflag.h"

// func vmovmskps128(vals *[4]float32, ret *[4]byte)
// Requires: AVX
TEXT ·vmovmskps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVAPS (AX), X0

	// Extract sign mask values from vals
	VMOVMSKPS X0, AX

	// Write sign mask values into return memory address
	MOVL AX, (CX)

	// Return from function
	RET
