// Code generated by command: go run asm_vmovmskps_256.go -out ../asm_vmovmskps_256.s -stubs ../stub_vmovmskps_256.go -pkg movmskps. DO NOT EDIT.

package movmskps

func vmovmskps256(vals *[8]float32, ret *[4]byte)
