// Code generated by command: go run asm_movmskps_128.go -out ../asm_movmskps_128.s -stubs ../stub_movmskps_128.go -pkg movmskps. DO NOT EDIT.

package movmskps

func movmskps128(vals *[4]float32, ret *[4]byte)
