// Code generated by command: go run asm_vpunpcklwd_128.go -out ../asm_vpunpcklwd_128.s -stubs ../stub_vpunpcklwd_128.go -pkg punpckl. DO NOT EDIT.

#include "textflag.h"

// func vpunpcklwd128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpunpcklwd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Interleave low-order words from each operand
	VPUNPCKLWD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
