// Code generated by command: go run asm_vpunpcklqdq_128.go -out ../asm_vpunpcklqdq_128.s -stubs ../stub_vpunpcklqdq_128.go -pkg punpckl. DO NOT EDIT.

#include "textflag.h"

// func vpunpcklqdq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
// Requires: AVX
TEXT ·vpunpcklqdq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Interleave low-order qwords from each operand
	VPUNPCKLQDQ X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
