// Code generated by command: go run asm_vpunpcklwd_256.go -out ../asm_vpunpcklwd_256.s -stubs ../stub_vpunpcklwd_256.go -pkg punpckl. DO NOT EDIT.

#include "textflag.h"

// func vpunpcklwd256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpunpcklwd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Interleave low-order words from each operand (per lane)
	VPUNPCKLWD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
