// Code generated by command: go run asm_vpunpcklqdq_256.go -out ../asm_vpunpcklqdq_256.s -stubs ../stub_vpunpcklqdq_256.go -pkg punpckl. DO NOT EDIT.

#include "textflag.h"

// func vpunpcklqdq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpunpcklqdq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Interleave low-order qwords from each operand (per lane)
	VPUNPCKLQDQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
