// Code generated by command: go run asm_vpunpcklqdq_256.go -out ../asm_vpunpcklqdq_256.s -stubs ../stub_vpunpcklqdq_256.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpcklqdq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
