// Code generated by command: go run asm_vpunpcklwd_128.go -out ../asm_vpunpcklwd_128.s -stubs ../stub_vpunpcklwd_128.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpcklwd128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
