// Code generated by command: go run asm_vpunpcklwd_256.go -out ../asm_vpunpcklwd_256.s -stubs ../stub_vpunpcklwd_256.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpcklwd256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
