// Code generated by command: go run asm_vpunpckldq_128.go -out ../asm_vpunpckldq_128.s -stubs ../stub_vpunpckldq_128.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpckldq128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
