// Code generated by command: go run asm_vpunpcklbw_256.go -out ../asm_vpunpcklbw_256.s -stubs ../stub_vpunpcklbw_256.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpcklbw256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
