// Code generated by command: go run asm_vpunpcklqdq_128.go -out ../asm_vpunpcklqdq_128.s -stubs ../stub_vpunpcklqdq_128.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpcklqdq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
