// Code generated by command: go run asm_vpunpckldq_256.go -out ../asm_vpunpckldq_256.s -stubs ../stub_vpunpckldq_256.go -pkg punpckl. DO NOT EDIT.

package punpckl

func vpunpckldq256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
