// Code generated by command: go run asm_vpackuswb_128.go -out ../asm_vpackuswb_128.s -stubs ../stub_vpackuswb_128.go -pkg packus. DO NOT EDIT.

#include "textflag.h"

// func vpackuswb128(vals1 *[8]int16, vals2 *[8]int16, ret *[16]int8)
// Requires: AVX
TEXT ·vpackuswb128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Pack signed words to unsigned bytes with saturation
	VPACKUSWB X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
