// Code generated by command: go run asm_vpackuswb_256.go -out ../asm_vpackuswb_256.s -stubs ../stub_vpackuswb_256.go -pkg packus. DO NOT EDIT.

#include "textflag.h"

// func vpackuswb256(vals1 *[16]int16, vals2 *[16]int16, ret *[32]int8)
// Requires: AVX, AVX2
TEXT ·vpackuswb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Pack signed words to unsigned bytes with saturation (per 128-bit lane)
	VPACKUSWB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
