// Code generated by command: go run asm_vpackusdw_128.go -out ../asm_vpackusdw_128.s -stubs ../stub_vpackusdw_128.go -pkg packus. DO NOT EDIT.

#include "textflag.h"

// func vpackusdw128(vals1 *[4]int32, vals2 *[4]int32, ret *[8]int16)
// Requires: AVX
TEXT ·vpackusdw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Pack signed dwords to unsigned words with saturation
	VPACKUSDW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
