// Code generated by command: go run asm_vpackuswb_128.go -out ../asm_vpackuswb_128.s -stubs ../stub_vpackuswb_128.go -pkg packus. DO NOT EDIT.

package packus

func vpackuswb128(vals1 *[8]int16, vals2 *[8]int16, ret *[16]int8)
