// Code generated by command: go run asm_vpackusdw_256.go -out ../asm_vpackusdw_256.s -stubs ../stub_vpackusdw_256.go -pkg packus. DO NOT EDIT.

package packus

func vpackusdw256(vals1 *[8]int32, vals2 *[8]int32, ret *[16]int16)
