// Code generated by command: go run asm_vpackusdw_128.go -out ../asm_vpackusdw_128.s -stubs ../stub_vpackusdw_128.go -pkg packus. DO NOT EDIT.

package packus

func vpackusdw128(vals1 *[4]int32, vals2 *[4]int32, ret *[8]int16)
