// Code generated by command: go run asm_vhaddps_256.go -out ../asm_vhaddps_256.s -stubs ../stub_vhaddps_256.go -pkg vhaddps. DO NOT EDIT.

package vhaddps

func vhaddps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
