// Code generated by command: go run asm_vhaddps_128.go -out ../asm_vhaddps_128.s -stubs ../stub_vhaddps_128.go -pkg vhaddps. DO NOT EDIT.

package vhaddps

func vhaddps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
