// Code generated by command: go run asm_vpshufb_128.go -out ../asm_vpshufb_128.s -stubs ../stub_vpshufb_128.go -pkg pshuf. DO NOT EDIT.

#include "textflag.h"

// func vpshufb128(vals1 *[16]uint8, mask *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpshufb128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Shuffle bytes in regData according to regMask
	VPSHUFB X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
