// Code generated by command: go run asm_vpshufb_256.go -out ../asm_vpshufb_256.s -stubs ../stub_vpshufb_256.go -pkg pshufb. DO NOT EDIT.

#include "textflag.h"

// func vpshufb256(vals1 *[32]uint8, control *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpshufb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load control into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VPSHUFB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
