// Code generated by command: go run asm_vpshufb_128.go -out ../asm_vpshufb_128.s -stubs ../stub_vpshufb_128.go -pkg pshufb. DO NOT EDIT.

#include "textflag.h"

// func vpshufb128(vals1 *[16]uint8, control *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpshufb128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQU (AX), X0

	// Load control into XMM register
	VMOVDQU (CX), X1

	// Execute the instruction being demonstrated
	VPSHUFB X1, X0, X0

	// Write results into return memory address
	VMOVDQU X0, (DX)

	// Return from function
	RET
