// Code generated by command: go run asm_vpshufb_256.go -out ../asm_vpshufb_256.s -stubs ../stub_vpshufb_256.go -pkg pshuf. DO NOT EDIT.

#include "textflag.h"

// func vpshufb256(vals1 *[32]uint8, mask *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpshufb256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Shuffle bytes in regData according to regMask (per lane)
	VPSHUFB Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
