// Code generated by command: go run asm_vpshufb_256.go -out ../asm_vpshufb_256.s -stubs ../stub_vpshufb_256.go -pkg pshufb. DO NOT EDIT.

package pshufb

func vpshufb256(vals1 *[32]uint8, control *[32]uint8, ret *[32]uint8)
