// Code generated by command: go run asm_vpshufb_128.go -out ../asm_vpshufb_128.s -stubs ../stub_vpshufb_128.go -pkg pshuf. DO NOT EDIT.

package pshufb

func vpshufb128(vals1 *[16]uint8, mask *[16]uint8, ret *[16]uint8)
