// Code generated by command: go run asm_pmovmskb_128.go -out ../asm_pmovmskb_128.s -stubs ../stub_pmovmskb_128.go -pkg pmovmskb. DO NOT EDIT.

#include "textflag.h"

// func pmovmskb128(vals *[16]uint8, ret *uint32)
// Requires: AVX, SSE2
TEXT ·pmovmskb128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Move MSBs of bytes to mask (lower 16 bits of 32-bit reg)
	PMOVMSKB X0, AX

	// Write mask to ret
	MOVL AX, (CX)

	// Return from function
	RET
