// Code generated by command: go run asm_vpmovmskb_128.go -out ../asm_vpmovmskb_128.s -stubs ../stub_vpmovmskb_128.go -pkg pmovmskb. DO NOT EDIT.

package pmovmskb

func vpmovmskb128(vals *[16]uint8, ret *uint32)
