// Code generated by command: go run asm_pmovmskb_128.go -out ../asm_pmovmskb_128.s -stubs ../stub_pmovmskb_128.go -pkg pmovmskb. DO NOT EDIT.

package pmovmskb

func pmovmskb128(vals *[16]uint8, ret *uint32)
