// Code generated by command: go run asm_vpermilps_128_reverse.go -out ../asm_vpermilps_128_reverse.s -stubs ../stub_vpermilps_128_reverse.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps128Reverse(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vpermilps128Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPS imm8=0x1B: reverse [a3 a2 a1 a0]
	VPERMILPS $0x1b, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
