// Code generated by command: go run asm_vpermilps_256.go -out ../asm_vpermilps_256.s -stubs ../stub_vpermilps_256.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps256(vals *[8]float32, control *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vpermilps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source and control into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERMILPS with control register (per-lane 2-bit selectors, per 128-bit lane)
	VPERMILPS Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// Return from function
	RET
