// Code generated by command: go run asm_vpermilps_256_reverse.go -out ../asm_vpermilps_256_reverse.s -stubs ../stub_vpermilps_256_reverse.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps256Reverse(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vpermilps256Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPS imm8=0x1B per 128-bit lane: reverse lane
	VPERMILPS $0x1b, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// Return from function
	RET
