// Code generated by command: go run asm_vpermilps_128_all_three.go -out ../asm_vpermilps_128_all_three.s -stubs ../stub_vpermilps_128_all_three.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps128All_three(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vpermilps128All_three(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPS imm8=0xFF: broadcast a3 to all lanes
	VPERMILPS $0xff, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
