// Code generated by command: go run asm_vpermilps_256_identity.go -out ../asm_vpermilps_256_identity.s -stubs ../stub_vpermilps_256_identity.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps256Identity(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vpermilps256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPS imm8=0xE4 per 128-bit lane: identity mapping
	VPERMILPS $0xe4, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// Return from function
	RET
