// Code generated by command: go run asm_vpermilps_256_all_two.go -out ../asm_vpermilps_256_all_two.s -stubs ../stub_vpermilps_256_all_two.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps256All_two(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vpermilps256All_two(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPS imm8=0xAA per 128-bit lane: broadcast lane2 element
	VPERMILPS $0xaa, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
