// Code generated by command: go run asm_vpermilps_128_identity.go -out ../asm_vpermilps_128_identity.s -stubs ../stub_vpermilps_128_identity.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps128Identity(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vpermilps128Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPS imm8=0xE4 (identity): dst = [a0 a1 a2 a3]
	VPERMILPS $0xe4, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
