// Code generated by command: go run asm_vpermilps_128.go -out ../asm_vpermilps_128.s -stubs ../stub_vpermilps_128.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps128(vals *[4]float32, control *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vpermilps128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source and control into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPERMILPS with control register (per-lane 2-bit selectors)
	VPERMILPS X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
