// Code generated by command: go run asm_vpermilps_256_all_three.go -out ../asm_vpermilps_256_all_three.s -stubs ../stub_vpermilps_256_all_three.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps256All_three(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vpermilps256All_three(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPS imm8=0xFF per 128-bit lane: broadcast lane3 element
	VPERMILPS $0xff, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// Return from function
	RET
