// Code generated by command: go run asm_vpermilps_128_all_zero.go -out ../asm_vpermilps_128_all_zero.s -stubs ../stub_vpermilps_128_all_zero.go -pkg vpermilps. DO NOT EDIT.

#include "textflag.h"

// func vpermilps128All_zero(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vpermilps128All_zero(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPS imm8=0x00: broadcast a0 to all lanes
	VPERMILPS $0x00, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
