// Code generated by command: go run asm_vpermilps_128_all_zero.go -out ../asm_vpermilps_128_all_zero.s -stubs ../stub_vpermilps_128_all_zero.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128All_zero(vals *[4]float32, ret *[4]float32)
