// Code generated by command: go run asm_vpermilps_256.go -out ../asm_vpermilps_256.s -stubs ../stub_vpermilps_256.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256(vals *[8]float32, control *[8]float32, ret *[8]float32)
