// Code generated by command: go run asm_vpermilps_256_reverse.go -out ../asm_vpermilps_256_reverse.s -stubs ../stub_vpermilps_256_reverse.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256Reverse(vals *[8]float32, ret *[8]float32)
