// Code generated by command: go run asm_vpermilps_256_all_zero.go -out ../asm_vpermilps_256_all_zero.s -stubs ../stub_vpermilps_256_all_zero.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256All_zero(vals *[8]float32, ret *[8]float32)
