// Code generated by command: go run asm_vpermilps_128_reverse.go -out ../asm_vpermilps_128_reverse.s -stubs ../stub_vpermilps_128_reverse.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128Reverse(vals *[4]float32, ret *[4]float32)
