// Code generated by command: go run asm_vpermilps_256_all_three.go -out ../asm_vpermilps_256_all_three.s -stubs ../stub_vpermilps_256_all_three.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256All_three(vals *[8]float32, ret *[8]float32)
