// Code generated by command: go run asm_vpermilps_256_identity.go -out ../asm_vpermilps_256_identity.s -stubs ../stub_vpermilps_256_identity.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256Identity(vals *[8]float32, ret *[8]float32)
