// Code generated by command: go run asm_vpermilps_128_all_one.go -out ../asm_vpermilps_128_all_one.s -stubs ../stub_vpermilps_128_all_one.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128All_one(vals *[4]float32, ret *[4]float32)
