// Code generated by command: go run asm_vpermilps_128_all_two.go -out ../asm_vpermilps_128_all_two.s -stubs ../stub_vpermilps_128_all_two.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128All_two(vals *[4]float32, ret *[4]float32)
