// Code generated by command: go run asm_vpermilps_128_all_three.go -out ../asm_vpermilps_128_all_three.s -stubs ../stub_vpermilps_128_all_three.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128All_three(vals *[4]float32, ret *[4]float32)
