// Code generated by command: go run asm_vpermilps_256_all_one.go -out ../asm_vpermilps_256_all_one.s -stubs ../stub_vpermilps_256_all_one.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps256All_one(vals *[8]float32, ret *[8]float32)
