// Code generated by command: go run asm_vpermilps_128_identity.go -out ../asm_vpermilps_128_identity.s -stubs ../stub_vpermilps_128_identity.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128Identity(vals *[4]float32, ret *[4]float32)
