// Code generated by command: go run asm_vpermilps_128.go -out ../asm_vpermilps_128.s -stubs ../stub_vpermilps_128.go -pkg vpermilps. DO NOT EDIT.

package vpermilps

func vpermilps128(vals *[4]float32, control *[4]float32, ret *[4]float32)
