// Code generated by command: go run asm_vpshufhw_128_odds.go -out ../asm_vpshufhw_128_odds.s -stubs ../stub_vpshufhw_128_odds.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw128Odds(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshufhw128Odds(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFHW imm8=0xDD (odds: [w5,w7,w5,w7])
	VPSHUFHW $0xdd, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
