// Code generated by command: go run asm_vpshufhw_128_evens.go -out ../asm_vpshufhw_128_evens.s -stubs ../stub_vpshufhw_128_evens.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw128Evens(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshufhw128Evens(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFHW imm8=0x88 (evens: [w4,w6,w4,w6])
	VPSHUFHW $0x88, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
