// Code generated by command: go run asm_vpshufhw_256_identity.go -out ../asm_vpshufhw_256_identity.s -stubs ../stub_vpshufhw_256_identity.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw256Identity(vals *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpshufhw256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFHW imm8=0xE4 (identity for high words, per 128-bit lane)
	VPSHUFHW $0xe4, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
