// Code generated by command: go run asm_vpshufhw_256_odds.go -out ../asm_vpshufhw_256_odds.s -stubs ../stub_vpshufhw_256_odds.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw256Odds(vals *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpshufhw256Odds(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFHW imm8=0xDD (odds per lane)
	VPSHUFHW $0xdd, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
