// Code generated by command: go run asm_vpshufhw_256_evens.go -out ../asm_vpshufhw_256_evens.s -stubs ../stub_vpshufhw_256_evens.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw256Evens(vals *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpshufhw256Evens(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFHW imm8=0x88 (evens per lane)
	VPSHUFHW $0x88, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
