// Code generated by command: go run asm_vpshufhw_128_reverse.go -out ../asm_vpshufhw_128_reverse.s -stubs ../stub_vpshufhw_128_reverse.go -pkg pshufhw. DO NOT EDIT.

#include "textflag.h"

// func vpshufhw128Reverse(vals *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpshufhw128Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFHW imm8=0x1B (reverse high words)
	VPSHUFHW $0x1b, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
