// Code generated by command: go run asm_vpshufhw_256_odds.go -out ../asm_vpshufhw_256_odds.s -stubs ../stub_vpshufhw_256_odds.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw256Odds(vals *[16]uint16, ret *[16]uint16)
