// Code generated by command: go run asm_vpshufhw_128_identity.go -out ../asm_vpshufhw_128_identity.s -stubs ../stub_vpshufhw_128_identity.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw128Identity(vals *[8]uint16, ret *[8]uint16)
