// Code generated by command: go run asm_vpshufhw_128_evens.go -out ../asm_vpshufhw_128_evens.s -stubs ../stub_vpshufhw_128_evens.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw128Evens(vals *[8]uint16, ret *[8]uint16)
