// Code generated by command: go run asm_vpshufhw_128_odds.go -out ../asm_vpshufhw_128_odds.s -stubs ../stub_vpshufhw_128_odds.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw128Odds(vals *[8]uint16, ret *[8]uint16)
