// Code generated by command: go run asm_vpshufhw_256_identity.go -out ../asm_vpshufhw_256_identity.s -stubs ../stub_vpshufhw_256_identity.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw256Identity(vals *[16]uint16, ret *[16]uint16)
