// Code generated by command: go run asm_vpshufhw_256_evens.go -out ../asm_vpshufhw_256_evens.s -stubs ../stub_vpshufhw_256_evens.go -pkg pshufhw. DO NOT EDIT.

package pshufhw

func vpshufhw256Evens(vals *[16]uint16, ret *[16]uint16)
