// Code generated by command: go run asm_vpsllvd_256.go -out ../asm_vpsllvd_256.s -stubs ../stub_vpsllvd_256.go -pkg vpsllvd. DO NOT EDIT.

#include "textflag.h"

// func vpsllvd256(vals *[8]uint32, shifts *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpsllvd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSLLVD: shift packed doubleword integers in vals left by variable counts in shifts
	VPSLLVD Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
