// Code generated by command: go run asm_vpsllvd_128.go -out ../asm_vpsllvd_128.s -stubs ../stub_vpsllvd_128.go -pkg vpsllvd. DO NOT EDIT.

#include "textflag.h"

// func vpsllvd128(vals *[4]uint32, shifts *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpsllvd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPSLLVD: shift packed doubleword integers in vals left by variable counts in shifts
	VPSLLVD X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
