// Code generated by command: go run asm_vpsllvd_128.go -out ../asm_vpsllvd_128.s -stubs ../stub_vpsllvd_128.go -pkg vpsllvd. DO NOT EDIT.

package vpsllvd

func vpsllvd128(vals *[4]uint32, shifts *[4]uint32, ret *[4]uint32)
