// Code generated by command: go run asm_vpsllvd_256.go -out ../asm_vpsllvd_256.s -stubs ../stub_vpsllvd_256.go -pkg vpsllvd. DO NOT EDIT.

package vpsllvd

func vpsllvd256(vals *[8]uint32, shifts *[8]uint32, ret *[8]uint32)
