// Code generated by command: go run asm_vpgatherdd_256.go -out ../asm_vpgatherdd_256.s -stubs ../stub_vpgatherdd_256.go -pkg vpgatherdd. DO NOT EDIT.

#include "textflag.h"

// func vpgatherdd256(base *[16]uint32, index *[8]uint32, mask *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpgatherdd256(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 32-bit indices into YMM register (lower 4 dwords; will be used with YMM gather semantics via VSIB)
	VMOVDQA (CX), Y0

	// Load mask into YMM register
	VMOVDQA (DX), Y1

	// Load destination/src vector
	VMOVDQA (BX), Y2

	// Gather eight u32 elements using 32-bit indices; scale=4 for dword element size
	VPGATHERDD Y1, (AX)(Y0*4), Y2

	// Store result vector
	VMOVDQA Y2, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return
	RET
