// Code generated by command: go run asm_vpgatherdd_128.go -out ../asm_vpgatherdd_128.s -stubs ../stub_vpgatherdd_128.go -pkg vpgatherdd. DO NOT EDIT.

#include "textflag.h"

// func vpgatherdd128(base *[8]uint32, index *[4]uint32, mask *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpgatherdd128(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 32-bit indices into XMM register (lower 4 dwords used)
	VMOVDQA (CX), X0

	// Load mask into XMM register (MSB of each dword lane used)
	VMOVDQA (DX), X1

	// Load destination/src vector
	VMOVDQA (BX), X2

	// Gather four u32 elements using 32-bit indices; scale=4 for dword element size
	VPGATHERDD X1, (AX)(X0*4), X2

	// Store result vector
	VMOVDQA X2, (BX)

	// Return
	RET
