// Code generated by command: go run asm_vpgatherdd_128.go -out ../asm_vpgatherdd_128.s -stubs ../stub_vpgatherdd_128.go -pkg vpgatherdd. DO NOT EDIT.

package vpgatherdd

func vpgatherdd128(base *[8]uint32, index *[4]uint32, mask *[4]uint32, ret *[4]uint32)
