// Code generated by command: go run asm_vpgatherdd_256.go -out ../asm_vpgatherdd_256.s -stubs ../stub_vpgatherdd_256.go -pkg vpgatherdd. DO NOT EDIT.

package vpgatherdd

func vpgatherdd256(base *[16]uint32, index *[8]uint32, mask *[8]uint32, ret *[8]uint32)
