// Code generated by command: go run asm_vsqrtps_128.go -out ../asm_vsqrtps_128.s -stubs ../stub_vsqrtps_128.go -pkg sqrtps. DO NOT EDIT.

#include "textflag.h"

// func vsqrtps128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vsqrtps128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute square root of packed float32 values with VEX encoding: regX1 = sqrt(regX1)
	VSQRTPS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
