// Code generated by command: go run asm_sqrtps_128.go -out ../asm_sqrtps_128.s -stubs ../stub_sqrtps_128.go -pkg sqrtps. DO NOT EDIT.

package sqrtps

func sqrtps128(vals *[4]float32, ret *[4]float32)
