// Code generated by command: go run asm_vsqrtps_256.go -out ../asm_vsqrtps_256.s -stubs ../stub_vsqrtps_256.go -pkg sqrtps. DO NOT EDIT.

package sqrtps

func vsqrtps256(vals *[8]float32, ret *[8]float32)
