// Code generated by command: go run asm_vsqrtps_128.go -out ../asm_vsqrtps_128.s -stubs ../stub_vsqrtps_128.go -pkg sqrtps. DO NOT EDIT.

package sqrtps

func vsqrtps128(vals *[4]float32, ret *[4]float32)
