// Code generated by command: go run asm_vpsllvq_256.go -out ../asm_vpsllvq_256.s -stubs ../stub_vpsllvq_256.go -pkg vpsllvq. DO NOT EDIT.

#include "textflag.h"

// func vpsllvq256(vals *[4]uint64, shifts *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpsllvq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSLLVQ: shift packed quadword integers in vals left by variable counts in shifts
	VPSLLVQ Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
