// Code generated by command: go run asm_vpsllvq_256.go -out ../asm_vpsllvq_256.s -stubs ../stub_vpsllvq_256.go -pkg vpsllvq. DO NOT EDIT.

package vpsllvq

func vpsllvq256(vals *[4]uint64, shifts *[4]uint64, ret *[4]uint64)
