// Code generated by command: go run asm_vpsllvq_128.go -out ../asm_vpsllvq_128.s -stubs ../stub_vpsllvq_128.go -pkg vpsllvq. DO NOT EDIT.

package vpsllvq

func vpsllvq128(vals *[2]uint64, shifts *[2]uint64, ret *[2]uint64)
