// Code generated by command: go run asm_vucomiss_128.go -out ../asm_vucomiss_128.s -stubs ../stub_vucomiss_128.go -pkg ucomiss. DO NOT EDIT.

package ucomiss

func vucomiss128(vals1 *[4]float32, vals2 *[4]float32) (flags uint32)
