// Code generated by command: go run asm_ucomiss_128.go -out ../asm_ucomiss_128.s -stubs ../stub_ucomiss_128.go -pkg ucomiss. DO NOT EDIT.

package ucomiss

func ucomiss128(vals1 *[4]float32, vals2 *[4]float32) (flags uint32)
