// Code generated by command: go run asm_vpbroadcastd_256.go -out ../asm_vpbroadcastd_256.s -stubs ../stub_vpbroadcastd_256.go -pkg vpbroadcastd. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastd256(d uint32, ret *[8]uint32)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastd256(SB), NOSPLIT, $0-16
	// load params
	MOVLQZX d+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Need to move d into an XMM register to work with VPBROADCASTD instruction
	MOVQ AX, X0

	// Broadcast d into YMM register
	VPBROADCASTD X0, Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
