// Code generated by command: go run asm_vpbroadcastd_128.go -out ../asm_vpbroadcastd_128.s -stubs ../stub_vpbroadcastd_128.go -pkg vpbroadcastd. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastd128(d uint32, ret *[4]uint32)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastd128(SB), NOSPLIT, $0-16
	// load params
	MOVLQZX d+0(FP), AX
	MOVQ    ret+8(FP), CX

	// Need to move d into an XMM register to work with VPBROADCASTD instruction
	MOVQ AX, X0

	// Broadcast d into XMM register
	VPBROADCASTD X0, X0

	// Write contents of XMM register into memory region
	VMOVDQU X0, (CX)
	RET
