// Code generated by command: go run asm_vpbroadcastd_128.go -out ../asm_vpbroadcastd_128.s -stubs ../stub_vpbroadcastd_128.go -pkg vpbroadcastd. DO NOT EDIT.

package vpbroadcastd

func vpbroadcastd128(d uint32, ret *[4]uint32)
