// Code generated by command: go run asm_vpunpckhbw_256.go -out ../asm_vpunpckhbw_256.s -stubs ../stub_vpunpckhbw_256.go -pkg punpckh. DO NOT EDIT.

#include "textflag.h"

// func vpunpckhbw256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpunpckhbw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Interleave high-order bytes from each operand (per lane)
	VPUNPCKHBW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
