// Code generated by command: go run asm_vpunpckhqdq_256.go -out ../asm_vpunpckhqdq_256.s -stubs ../stub_vpunpckhqdq_256.go -pkg punpckh. DO NOT EDIT.

#include "textflag.h"

// func vpunpckhqdq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpunpckhqdq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Interleave high-order quadwords from each operand (per lane)
	VPUNPCKHQDQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
