// Code generated by command: go run asm_vpunpckhdq_256.go -out ../asm_vpunpckhdq_256.s -stubs ../stub_vpunpckhdq_256.go -pkg punpckh. DO NOT EDIT.

#include "textflag.h"

// func vpunpckhdq256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpunpckhdq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane operation)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Interleave high-order doublewords from each operand (per lane)
	VPUNPCKHDQ Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
