// Code generated by command: go run asm_vpunpckhwd_128.go -out ../asm_vpunpckhwd_128.s -stubs ../stub_vpunpckhwd_128.go -pkg punpckh. DO NOT EDIT.

#include "textflag.h"

// func vpunpckhwd128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
// Requires: AVX
TEXT ·vpunpckhwd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Interleave high-order words from each operand
	VPUNPCKHWD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
