// Code generated by command: go run asm_vpunpckhwd_256.go -out ../asm_vpunpckhwd_256.s -stubs ../stub_vpunpckhwd_256.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhwd256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
