// Code generated by command: go run asm_vpunpckhwd_128.go -out ../asm_vpunpckhwd_128.s -stubs ../stub_vpunpckhwd_128.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhwd128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
