// Code generated by command: go run asm_vpunpckhbw_256.go -out ../asm_vpunpckhbw_256.s -stubs ../stub_vpunpckhbw_256.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhbw256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
