// Code generated by command: go run asm_vpunpckhqdq_256.go -out ../asm_vpunpckhqdq_256.s -stubs ../stub_vpunpckhqdq_256.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhqdq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
