// Code generated by command: go run asm_vpunpckhqdq_128.go -out ../asm_vpunpckhqdq_128.s -stubs ../stub_vpunpckhqdq_128.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhqdq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
