// Code generated by command: go run asm_vpunpckhdq_256.go -out ../asm_vpunpckhdq_256.s -stubs ../stub_vpunpckhdq_256.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhdq256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
