// Code generated by command: go run asm_vpunpckhbw_128.go -out ../asm_vpunpckhbw_128.s -stubs ../stub_vpunpckhbw_128.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhbw128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
