// Code generated by command: go run asm_vpunpckhdq_128.go -out ../asm_vpunpckhdq_128.s -stubs ../stub_vpunpckhdq_128.go -pkg punpckh. DO NOT EDIT.

package punpckh

func vpunpckhdq128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
