// Code generated by command: go run asm_vpmaddwd_256.go -out ../asm_vpmaddwd_256.s -stubs ../stub_vpmaddwd_256.go -pkg vpmaddwd. DO NOT EDIT.

#include "textflag.h"

// func vpmaddwd256(vals1 *[16]int16, vals2 *[16]int16, ret *[8]int32)
// Requires: AVX, AVX2
TEXT ·vpmaddwd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load vals2 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VPMADDWD Y0, Y1, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
