// Code generated by command: go run asm_vpmaddwd_256.go -out ../asm_vpmaddwd_256.s -stubs ../stub_vpmaddwd_256.go -pkg vpmaddwd. DO NOT EDIT.

package vpmaddwd

func vpmaddwd256(vals1 *[16]int16, vals2 *[16]int16, ret *[8]int32)
