// Code generated by command: go run asm_vpbroadcastq_128.go -out ../asm_vpbroadcastq_128.s -stubs ../stub_vpbroadcastq_128.go -pkg vpbroadcastq. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastq128(q uint64, ret *[2]uint64)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastq128(SB), NOSPLIT, $0-16
	// load params
	MOVQ q+0(FP), AX
	MOVQ ret+8(FP), CX

	// Need to move q into an XMM register to work with VPBROADCASTQ instruction
	MOVQ AX, X0

	// Broadcast q into XMM register
	VPBROADCASTQ X0, X0

	// Write contents of XMM register into memory region
	VMOVDQU X0, (CX)
	RET
