// Code generated by command: go run asm_vpbroadcastq_256.go -out ../asm_vpbroadcastq_256.s -stubs ../stub_vpbroadcastq_256.go -pkg vpbroadcastq. DO NOT EDIT.

#include "textflag.h"

// func vpbroadcastq256(q uint64, ret *[4]uint64)
// Requires: AVX, AVX2, SSE2
TEXT ·vpbroadcastq256(SB), NOSPLIT, $0-16
	// load params
	MOVQ q+0(FP), AX
	MOVQ ret+8(FP), CX

	// Need to move q into an XMM register to work with VPBROADCASTQ instruction
	MOVQ AX, X0

	// Broadcast q into YMM register
	VPBROADCASTQ X0, Y0

	// Write contents of YMM register into memory region
	VMOVDQU Y0, (CX)

	// Call VZEROUPPER to avoid performance problems after AVX work
	VZEROUPPER
	RET
