// Code generated by command: go run asm_vpbroadcastq_256.go -out ../asm_vpbroadcastq_256.s -stubs ../stub_vpbroadcastq_256.go -pkg vpbroadcastq. DO NOT EDIT.

package vpbroadcastq

func vpbroadcastq256(q uint64, ret *[4]uint64)
