// Code generated by command: go run asm_vpbroadcastq_128.go -out ../asm_vpbroadcastq_128.s -stubs ../stub_vpbroadcastq_128.go -pkg vpbroadcastq. DO NOT EDIT.

package vpbroadcastq

func vpbroadcastq128(q uint64, ret *[2]uint64)
