// Code generated by command: go run asm_subps_128.go -out ../asm_subps_128.s -stubs ../stub_subps_128.go -pkg subps. DO NOT EDIT.

package subps

func subps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
