// Code generated by command: go run asm_vsubps_256.go -out ../asm_vsubps_256.s -stubs ../stub_vsubps_256.go -pkg subps. DO NOT EDIT.

package subps

func vsubps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
