// Code generated by command: go run asm_vpalignr_256_zero.go -out ../asm_vpalignr_256_zero.s -stubs ../stub_vpalignr_256_zero.go -pkg palignr. DO NOT EDIT.

#include "textflag.h"

// func vpalignr256Zero(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpalignr256Zero(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into YMM registers (per-lane)
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Align right by 0 bytes across vals1/vals2 per 128-bit lane (imm8=0)
	VPALIGNR $0x00, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
