// Code generated by command: go run asm_vpalignr_128_one.go -out ../asm_vpalignr_128_one.s -stubs ../stub_vpalignr_128_one.go -pkg palignr. DO NOT EDIT.

#include "textflag.h"

// func vpalignr128One(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpalignr128One(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load operands into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Align right by 1 byte across vals1/vals2 (imm8=1)
	VPALIGNR $0x01, X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
