// Code generated by command: go run asm_vpalignr_128_four.go -out ../asm_vpalignr_128_four.s -stubs ../stub_vpalignr_128_four.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr128Four(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
