// Code generated by command: go run asm_vpalignr_256_one.go -out ../asm_vpalignr_256_one.s -stubs ../stub_vpalignr_256_one.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr256One(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
