// Code generated by command: go run asm_vpalignr_256_two.go -out ../asm_vpalignr_256_two.s -stubs ../stub_vpalignr_256_two.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr256Two(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
