// Code generated by command: go run asm_vpalignr_128_sixteen.go -out ../asm_vpalignr_128_sixteen.s -stubs ../stub_vpalignr_128_sixteen.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr128Sixteen(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
