// Code generated by command: go run asm_vpalignr_128_one.go -out ../asm_vpalignr_128_one.s -stubs ../stub_vpalignr_128_one.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr128One(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
