// Code generated by command: go run asm_vpalignr_256_sixteen.go -out ../asm_vpalignr_256_sixteen.s -stubs ../stub_vpalignr_256_sixteen.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr256Sixteen(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
