// Code generated by command: go run asm_vpalignr_128_zero.go -out ../asm_vpalignr_128_zero.s -stubs ../stub_vpalignr_128_zero.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr128Zero(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
