// Code generated by command: go run asm_vpalignr_256_four.go -out ../asm_vpalignr_256_four.s -stubs ../stub_vpalignr_256_four.go -pkg palignr. DO NOT EDIT.

package palignr

func vpalignr256Four(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
