// Code generated by command: go run asm_vmaskmovps_128_load.go -out ../asm_vmaskmovps_128_load.s -stubs ../stub_vmaskmovps_128_load.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovps128Load(vals *[4]float32, mask *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmaskmovps128Load(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load mask into XMM register
	VMOVDQA (CX), X0

	// Zero destination
	VXORPS X1, X1, X1

	// Masked load: load selected elements from memory into destination
	VMASKMOVPS (AX), X0, X1

	// Write results into return memory address
	VMOVDQA X1, (DX)

	// Return from function
	RET
