// Code generated by command: go run asm_vmaskmovpd_128_store.go -out ../asm_vmaskmovpd_128_store.s -stubs ../stub_vmaskmovpd_128_store.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovpd128Store(vals *[2]float64, mask *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vmaskmovpd128Store(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source (vals) and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Masked store: store selected double-precision elements to memory (ret)
	VMASKMOVPD X1, X0, (DX)

	// Return from function
	RET
