// Code generated by command: go run asm_vmaskmovpd_256_load.go -out ../asm_vmaskmovpd_256_load.s -stubs ../stub_vmaskmovpd_256_load.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovpd256Load(vals *[4]float64, mask *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vmaskmovpd256Load(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load mask into YMM register
	VMOVDQA (CX), Y0

	// Zero destination
	VXORPS Y1, Y1, Y1

	// Masked load: load selected double-precision elements from memory
	VMASKMOVPD (AX), Y0, Y1

	// Write results into return memory address
	VMOVDQA Y1, (DX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
