// Code generated by command: go run asm_vmaskmovps_128_store.go -out ../asm_vmaskmovps_128_store.s -stubs ../stub_vmaskmovps_128_store.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovps128Store(vals *[4]float32, mask *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmaskmovps128Store(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source (vals) and mask into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Masked store: store selected single-precision elements to memory (ret)
	VMASKMOVPS X1, X0, (DX)

	// Return from function
	RET
