// Code generated by command: go run asm_vmaskmovps_256_load.go -out ../asm_vmaskmovps_256_load.s -stubs ../stub_vmaskmovps_256_load.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovps256Load(vals *[8]float32, mask *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vmaskmovps256Load(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load mask into YMM register
	VMOVDQA (CX), Y0

	// Zero destination
	VXORPS Y1, Y1, Y1

	// Masked load: load selected elements from memory into destination
	VMASKMOVPS (AX), Y0, Y1

	// Write results into return memory address
	VMOVDQA Y1, (DX)

	// Return from function
	RET
