// Code generated by command: go run asm_vmaskmovpd_256_store.go -out ../asm_vmaskmovpd_256_store.s -stubs ../stub_vmaskmovpd_256_store.go -pkg vmaskmov. DO NOT EDIT.

#include "textflag.h"

// func vmaskmovpd256Store(vals *[4]float64, mask *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vmaskmovpd256Store(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ mask+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source (vals) and mask into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Masked store: store selected double-precision elements to memory (ret)
	VMASKMOVPD Y1, Y0, (DX)




	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
