// Code generated by command: go run asm_vmaskmovps_256_load.go -out ../asm_vmaskmovps_256_load.s -stubs ../stub_vmaskmovps_256_load.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovps256Load(vals *[8]float32, mask *[8]float32, ret *[8]float32)
