// Code generated by command: go run asm_vmaskmovpd_128_load.go -out ../asm_vmaskmovpd_128_load.s -stubs ../stub_vmaskmovpd_128_load.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovpd128Load(vals *[2]float64, mask *[2]float64, ret *[2]float64)
