// Code generated by command: go run asm_vmaskmovpd_256_load.go -out ../asm_vmaskmovpd_256_load.s -stubs ../stub_vmaskmovpd_256_load.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovpd256Load(vals *[4]float64, mask *[4]float64, ret *[4]float64)
