// Code generated by command: go run asm_vmaskmovps_128_store.go -out ../asm_vmaskmovps_128_store.s -stubs ../stub_vmaskmovps_128_store.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovps128Store(vals *[4]float32, mask *[4]float32, ret *[4]float32)
