// Code generated by command: go run asm_vmaskmovps_256_store.go -out ../asm_vmaskmovps_256_store.s -stubs ../stub_vmaskmovps_256_store.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovps256Store(vals *[8]float32, mask *[8]float32, ret *[8]float32)
