// Code generated by command: go run asm_vmaskmovps_128_load.go -out ../asm_vmaskmovps_128_load.s -stubs ../stub_vmaskmovps_128_load.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovps128Load(vals *[4]float32, mask *[4]float32, ret *[4]float32)
