// Code generated by command: go run asm_vmaskmovpd_128_store.go -out ../asm_vmaskmovpd_128_store.s -stubs ../stub_vmaskmovpd_128_store.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovpd128Store(vals *[2]float64, mask *[2]float64, ret *[2]float64)
