// Code generated by command: go run asm_vmaskmovpd_256_store.go -out ../asm_vmaskmovpd_256_store.s -stubs ../stub_vmaskmovpd_256_store.go -pkg vmaskmov. DO NOT EDIT.

package vmaskmov

func vmaskmovpd256Store(vals *[4]float64, mask *[4]float64, ret *[4]float64)
