// Code generated by command: go run asm_vpblendd_128_all.go -out ../asm_vpblendd_128_all.s -stubs ../stub_vpblendd_128_all.go -pkg vpblendd. DO NOT EDIT.

#include "textflag.h"

// func vpblendd128All(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpblendd128All(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load A and B into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPBLENDD: all from B (imm=0x0F selects all lanes from B)
	VPBLENDD $0x0f, X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
