// Code generated by command: go run asm_vpblendd_128_high_half.go -out ../asm_vpblendd_128_high_half.s -stubs ../stub_vpblendd_128_high_half.go -pkg vpblendd. DO NOT EDIT.

#include "textflag.h"

// func vpblendd128High_half(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
// Requires: AVX, AVX2
TEXT ·vpblendd128High_half(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load A and B into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPBLENDD: high half from B (imm=0x0C selects lanes 2 and 3 from B)
	VPBLENDD $0x0c, X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
