// Code generated by command: go run asm_vpblendd_128_all.go -out ../asm_vpblendd_128_all.s -stubs ../stub_vpblendd_128_all.go -pkg vpblendd. DO NOT EDIT.

package vpblendd

func vpblendd128All(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
