// Code generated by command: go run asm_vpblendd_128_even.go -out ../asm_vpblendd_128_even.s -stubs ../stub_vpblendd_128_even.go -pkg vpblendd. DO NOT EDIT.

package vpblendd

func vpblendd128Even(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
