// Code generated by command: go run asm_vpblendd_128_high_half.go -out ../asm_vpblendd_128_high_half.s -stubs ../stub_vpblendd_128_high_half.go -pkg vpblendd. DO NOT EDIT.

package vpblendd

func vpblendd128High_half(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
