// Code generated by command: go run asm_vpblendd_128_none.go -out ../asm_vpblendd_128_none.s -stubs ../stub_vpblendd_128_none.go -pkg vpblendd. DO NOT EDIT.

package vpblendd

func vpblendd128None(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
