// Code generated by command: go run asm_pmaxsw_128.go -out ../asm_pmaxsw_128.s -stubs ../stub_pmaxsw_128.go -pkg pmaxsw. DO NOT EDIT.

#include "textflag.h"

// func pmaxsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
// Requires: AVX, SSE2
TEXT ·pmaxsw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Packed signed word max per lane
	PMAXSW X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
