// Code generated by command: go run asm_pmaxsw_128.go -out ../asm_pmaxsw_128.s -stubs ../stub_pmaxsw_128.go -pkg pmaxsw. DO NOT EDIT.

package pmaxsw

func pmaxsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
