// Code generated by command: go run asm_vpmaxsw_128.go -out ../asm_vpmaxsw_128.s -stubs ../stub_vpmaxsw_128.go -pkg pmaxsw. DO NOT EDIT.

package pmaxsw

func vpmaxsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
