// Code generated by command: go run asm_vmovups_256.go -out ../asm_vmovups_256.s -stubs ../stub_vmovups_256.go -pkg movups. DO NOT EDIT.

#include "textflag.h"

// func vmovups256(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vmovups256(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVUPS (AX), Y0

	// Move vals into another YMM register
	VMOVUPS Y0, Y0

	// Write contents of the second YMM register into memory region
	VMOVUPS Y0, (CX)
	RET
