// Code generated by command: go run asm_vmovups_128.go -out ../asm_vmovups_128.s -stubs ../stub_vmovups_128.go -pkg movups. DO NOT EDIT.

#include "textflag.h"

// func vmovups128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vmovups128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVUPS (AX), X0

	// Move vals into another XMM register
	VMOVUPS X0, X0

	// Write contents of the second XMM register into memory region
	VMOVUPS X0, (CX)
	RET
