// Code generated by command: go run asm_256_loadstore_vmovups.go -out ../asm_256_loadstore_vmovups.s -stubs ../stub_256_loadstore_vmovups.go -pkg movups. DO NOT EDIT.

#include "textflag.h"

// func movups256LoadStoreVmovups(vals *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·movups256LoadStoreVmovups(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVUPS (AX), Y0

	// Move vals into another YMM register
	VMOVUPS Y0, Y0

	// Write contents of the second YMM register into memory region
	VMOVUPS Y0, (CX)
	RET
