// Code generated by command: go run asm_128_loadstore_vmovups.go -out ../asm_128_loadstore_vmovups.s -stubs ../stub_128_loadstore_vmovups.go -pkg movups. DO NOT EDIT.

#include "textflag.h"

// func movups128LoadStoreVmovups(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·movups128LoadStoreVmovups(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVUPS (AX), X0

	// Move vals into another XMM register
	VMOVUPS X0, X0

	// Write contents of the second XMM register into memory region
	VMOVUPS X0, (CX)
	RET
