// Code generated by command: go run asm_movups_128.go -out ../asm_movups_128.s -stubs ../stub_movups_128.go -pkg movups. DO NOT EDIT.

#include "textflag.h"

// func movups128(vals *[4]float32, ret *[4]float32)
// Requires: SSE
TEXT ·movups128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	MOVUPS (AX), X0

	// Move vals into another XMM register
	MOVUPS X0, X0

	// Write contents of the second XMM register into memory region
	MOVUPS X0, (CX)
	RET
