// Code generated by command: go run asm_vmovups_128.go -out ../asm_vmovups_128.s -stubs ../stub_vmovups_128.go -pkg movups. DO NOT EDIT.

package movups

func vmovups128(vals *[4]float32, ret *[4]float32)
