// Code generated by command: go run asm_movups_128.go -out ../asm_movups_128.s -stubs ../stub_movups_128.go -pkg movups. DO NOT EDIT.

package movups

func movups128(vals *[4]float32, ret *[4]float32)
