// Code generated by command: go run asm_256_loadstore_vmovups.go -out ../asm_256_loadstore_vmovups.s -stubs ../stub_256_loadstore_vmovups.go -pkg movups. DO NOT EDIT.

package movups

func movups256LoadStoreVmovups(vals *[8]float32, ret *[8]float32)
