// Code generated by command: go run asm_vmovups_256.go -out ../asm_vmovups_256.s -stubs ../stub_vmovups_256.go -pkg movups. DO NOT EDIT.

package movups

func vmovups256(vals *[8]float32, ret *[8]float32)
