// Code generated by command: go run asm_128_loadstore_movups.go -out ../asm_128_loadstore_movups.s -stubs ../stub_128_loadstore_movups.go -pkg movups. DO NOT EDIT.

package movups

func movups128LoadStoreMovups(vals *[4]float32, ret *[4]float32)
