// Code generated by command: go run asm_128_loadstore_vmovups.go -out ../asm_128_loadstore_vmovups.s -stubs ../stub_128_loadstore_vmovups.go -pkg movups. DO NOT EDIT.

package movups

func movups128LoadStoreVmovups(vals *[4]float32, ret *[4]float32)
