// Code generated by command: go run asm_vinsertf128_256_zero.go -out ../asm_vinsertf128_256_zero.s -stubs ../stub_vinsertf128_256_zero.go -pkg vinsertf128. DO NOT EDIT.

#include "textflag.h"

// func vinsertf128256Zero(base *[8]float32, block *[4]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vinsertf128256Zero(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ block+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base YMM register
	VMOVDQA (AX), Y0

	// Insert 128-bit block from memory into lane 0 of YMM (imm8=0)
	VINSERTF128 $0x00, (CX), Y0, Y0

	// Write result into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
