// Code generated by command: go run asm_vinsertf128_256_one.go -out ../asm_vinsertf128_256_one.s -stubs ../stub_vinsertf128_256_one.go -pkg vinsertf128. DO NOT EDIT.

package vinsertf128

func vinsertf128256One(base *[8]float32, block *[4]float32, ret *[8]float32)
