// Code generated by command: go run asm_vpcmpeqq_128.go -out ../asm_vpcmpeqq_128.s -stubs ../stub_vpcmpeqq_128.go -pkg pcmpeq. DO NOT EDIT.

#include "textflag.h"

// func vpcmpeqq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
// Requires: AVX
TEXT ·vpcmpeqq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Compare packed qwords for equality; result lanes are all-ones or zero
	VPCMPEQQ X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
