// Code generated by command: go run asm_vpcmpeqd_128.go -out ../asm_vpcmpeqd_128.s -stubs ../stub_vpcmpeqd_128.go -pkg pcmpeq. DO NOT EDIT.

#include "textflag.h"

// func vpcmpeqd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vpcmpeqd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Compare packed dwords for equality; result lanes are 0xFFFFFFFF or 0x00000000
	VPCMPEQD X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
