// Code generated by command: go run asm_vpcmpeqd_256.go -out ../asm_vpcmpeqd_256.s -stubs ../stub_vpcmpeqd_256.go -pkg pcmpeq. DO NOT EDIT.

#include "textflag.h"

// func vpcmpeqd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpcmpeqd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Compare packed dwords for equality (per 128-bit lane)
	VPCMPEQD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
