// Code generated by command: go run asm_vpcmpeqb_256.go -out ../asm_vpcmpeqb_256.s -stubs ../stub_vpcmpeqb_256.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqb256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
