// Code generated by command: go run asm_vpcmpeqd_128.go -out ../asm_vpcmpeqd_128.s -stubs ../stub_vpcmpeqd_128.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqd128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
