// Code generated by command: go run asm_vpcmpeqq_256.go -out ../asm_vpcmpeqq_256.s -stubs ../stub_vpcmpeqq_256.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqq256(vals1 *[4]uint64, vals2 *[4]uint64, ret *[4]uint64)
