// Code generated by command: go run asm_vpcmpeqw_256.go -out ../asm_vpcmpeqw_256.s -stubs ../stub_vpcmpeqw_256.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
