// Code generated by command: go run asm_vpcmpeqw_128.go -out ../asm_vpcmpeqw_128.s -stubs ../stub_vpcmpeqw_128.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
