// Code generated by command: go run asm_vpcmpeqd_256.go -out ../asm_vpcmpeqd_256.s -stubs ../stub_vpcmpeqd_256.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqd256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
