// Code generated by command: go run asm_vpcmpeqb_128.go -out ../asm_vpcmpeqb_128.s -stubs ../stub_vpcmpeqb_128.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqb128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
