// Code generated by command: go run asm_vpcmpeqq_128.go -out ../asm_vpcmpeqq_128.s -stubs ../stub_vpcmpeqq_128.go -pkg pcmpeq. DO NOT EDIT.

package pcmpeq

func vpcmpeqq128(vals1 *[2]uint64, vals2 *[2]uint64, ret *[2]uint64)
