// Code generated by command: go run asm_vpshufd_128_identity.go -out ../asm_vpshufd_128_identity.s -stubs ../stub_vpshufd_128_identity.go -pkg pshufd. DO NOT EDIT.

#include "textflag.h"

// func vpshufd128Identity(vals *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vpshufd128Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFD imm8=0xE4 (identity: [0,1,2,3])
	VPSHUFD $0xe4, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
