// Code generated by command: go run asm_vpshufd_256_evens.go -out ../asm_vpshufd_256_evens.s -stubs ../stub_vpshufd_256_evens.go -pkg pshufd. DO NOT EDIT.

#include "textflag.h"

// func vpshufd256Evens(vals *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpshufd256Evens(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFD imm8=0x88 (evens per 128-bit lane: [0,2,0,2])
	VPSHUFD $0x88, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
