// Code generated by command: go run asm_vpshufd_128_reverse.go -out ../asm_vpshufd_128_reverse.s -stubs ../stub_vpshufd_128_reverse.go -pkg pshufd. DO NOT EDIT.

#include "textflag.h"

// func vpshufd128Reverse(vals *[4]uint32, ret *[4]uint32)
// Requires: AVX
TEXT ·vpshufd128Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// VPSHUFD imm8=0x1B (reverse: [3,2,1,0])
	VPSHUFD $0x1b, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
