// Code generated by command: go run asm_vpshufd_256_identity.go -out ../asm_vpshufd_256_identity.s -stubs ../stub_vpshufd_256_identity.go -pkg pshufd. DO NOT EDIT.

#include "textflag.h"

// func vpshufd256Identity(vals *[8]uint32, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpshufd256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register (per-lane)
	VMOVDQA (AX), Y0

	// VPSHUFD imm8=0xE4 (identity per 128-bit lane)
	VPSHUFD $0xe4, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (CX)

	// Return from function
	RET
