// Code generated by command: go run asm_vpshufd_256_reverse.go -out ../asm_vpshufd_256_reverse.s -stubs ../stub_vpshufd_256_reverse.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd256Reverse(vals *[8]uint32, ret *[8]uint32)
