// Code generated by command: go run asm_vpshufd_256_evens.go -out ../asm_vpshufd_256_evens.s -stubs ../stub_vpshufd_256_evens.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd256Evens(vals *[8]uint32, ret *[8]uint32)
