// Code generated by command: go run asm_vpshufd_128_odds.go -out ../asm_vpshufd_128_odds.s -stubs ../stub_vpshufd_128_odds.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd128Odds(vals *[4]uint32, ret *[4]uint32)
