// Code generated by command: go run asm_vpshufd_128_evens.go -out ../asm_vpshufd_128_evens.s -stubs ../stub_vpshufd_128_evens.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd128Evens(vals *[4]uint32, ret *[4]uint32)
