// Code generated by command: go run asm_vpshufd_128_identity.go -out ../asm_vpshufd_128_identity.s -stubs ../stub_vpshufd_128_identity.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd128Identity(vals *[4]uint32, ret *[4]uint32)
