// Code generated by command: go run asm_vpshufd_256_identity.go -out ../asm_vpshufd_256_identity.s -stubs ../stub_vpshufd_256_identity.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd256Identity(vals *[8]uint32, ret *[8]uint32)
