// Code generated by command: go run asm_vpshufd_256_odds.go -out ../asm_vpshufd_256_odds.s -stubs ../stub_vpshufd_256_odds.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd256Odds(vals *[8]uint32, ret *[8]uint32)
