// Code generated by command: go run asm_vpshufd_128_reverse.go -out ../asm_vpshufd_128_reverse.s -stubs ../stub_vpshufd_128_reverse.go -pkg pshufd. DO NOT EDIT.

package pshufd

func vpshufd128Reverse(vals *[4]uint32, ret *[4]uint32)
