// Code generated by command: go run asm_vshufpd_128_lowa_highb.go -out ../asm_vshufpd_128_lowa_highb.s -stubs ../stub_vshufpd_128_lowa_highb.go -pkg vshufpd. DO NOT EDIT.

#include "textflag.h"

// func vshufpd128Lowa_highb(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vshufpd128Lowa_highb(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQU (AX), X0

	// Load vals2 into XMM register
	VMOVDQU (CX), X1

	// Execute the instruction being demonstrated
	VSHUFPD $0x02, X1, X0, X0

	// Write results into return memory address
	VMOVDQU X0, (DX)

	// Return from function
	RET
