// Code generated by command: go run asm_vshufpd_256_lowa_lowb.go -out ../asm_vshufpd_256_lowa_lowb.s -stubs ../stub_vshufpd_256_lowa_lowb.go -pkg vshufpd. DO NOT EDIT.

#include "textflag.h"

// func vshufpd256Lowa_lowb(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vshufpd256Lowa_lowb(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load vals2 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VSHUFPD $0x00, Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
