// Code generated by command: go run asm_vshufpd_256_higha_lowb.go -out ../asm_vshufpd_256_higha_lowb.s -stubs ../stub_vshufpd_256_higha_lowb.go -pkg vshufpd. DO NOT EDIT.

package vshufpd

func vshufpd256Higha_lowb(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
