// Code generated by command: go run asm_vshufpd_128_lowa_lowb.go -out ../asm_vshufpd_128_lowa_lowb.s -stubs ../stub_vshufpd_128_lowa_lowb.go -pkg vshufpd. DO NOT EDIT.

package vshufpd

func vshufpd128Lowa_lowb(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
