// Code generated by command: go run asm_vshufpd_128_higha_lowb.go -out ../asm_vshufpd_128_higha_lowb.s -stubs ../stub_vshufpd_128_higha_lowb.go -pkg vshufpd. DO NOT EDIT.

package vshufpd

func vshufpd128Higha_lowb(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
