// Code generated by command: go run asm_vshufpd_128_higha_highb.go -out ../asm_vshufpd_128_higha_highb.s -stubs ../stub_vshufpd_128_higha_highb.go -pkg vshufpd. DO NOT EDIT.

package vshufpd

func vshufpd128Higha_highb(vals1 *[2]float64, vals2 *[2]float64, ret *[2]float64)
