// Code generated by command: go run asm_vpslldq_256_eight.go -out ../asm_vpslldq_256_eight.s -stubs ../stub_vpslldq_256_eight.go -pkg vpslldq. DO NOT EDIT.

#include "textflag.h"

// func vpslldq256Eight(vals *[32]uint8, ret *[32]uint8)
// Requires: AVX, AVX2
TEXT ·vpslldq256Eight(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into YMM register
	VMOVDQU (AX), Y0

	// Execute the instruction being demonstrated
	VPSLLDQ $0x08, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (CX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
