// Code generated by command: go run asm_vpslldq_128_fifteen.go -out ../asm_vpslldq_128_fifteen.s -stubs ../stub_vpslldq_128_fifteen.go -pkg vpslldq. DO NOT EDIT.

#include "textflag.h"

// func vpslldq128Fifteen(vals *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpslldq128Fifteen(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQU (AX), X0

	// Execute the instruction being demonstrated
	VPSLLDQ $0x0f, X0, X0

	// Write results into return memory address
	VMOVDQU X0, (CX)

	// Return from function
	RET
