// Code generated by command: go run asm_vpslldq_256_eight.go -out ../asm_vpslldq_256_eight.s -stubs ../stub_vpslldq_256_eight.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq256Eight(vals *[32]uint8, ret *[32]uint8)
