// Code generated by command: go run asm_vpslldq_256_fifteen.go -out ../asm_vpslldq_256_fifteen.s -stubs ../stub_vpslldq_256_fifteen.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq256Fifteen(vals *[32]uint8, ret *[32]uint8)
