// Code generated by command: go run asm_vpslldq_128_fifteen.go -out ../asm_vpslldq_128_fifteen.s -stubs ../stub_vpslldq_128_fifteen.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq128Fifteen(vals *[16]uint8, ret *[16]uint8)
