// Code generated by command: go run asm_vpslldq_256_zero.go -out ../asm_vpslldq_256_zero.s -stubs ../stub_vpslldq_256_zero.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq256Zero(vals *[32]uint8, ret *[32]uint8)
