// Code generated by command: go run asm_vpslldq_128_one.go -out ../asm_vpslldq_128_one.s -stubs ../stub_vpslldq_128_one.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq128One(vals *[16]uint8, ret *[16]uint8)
