// Code generated by command: go run asm_vpslldq_256_one.go -out ../asm_vpslldq_256_one.s -stubs ../stub_vpslldq_256_one.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq256One(vals *[32]uint8, ret *[32]uint8)
