// Code generated by command: go run asm_vpslldq_256_sixteen.go -out ../asm_vpslldq_256_sixteen.s -stubs ../stub_vpslldq_256_sixteen.go -pkg vpslldq. DO NOT EDIT.

package vpslldq

func vpslldq256Sixteen(vals *[32]uint8, ret *[32]uint8)
