// Code generated by command: go run asm_rsqrtss_128.go -out ../asm_rsqrtss_128.s -stubs ../stub_rsqrtss_128.go -pkg rsqrtss. DO NOT EDIT.

#include "textflag.h"

// func rsqrtss128(vals *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·rsqrtss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal square root of scalar single precision value (lowest 32 bits)
	RSQRTSS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
