// Code generated by command: go run asm_vrsqrtss_128.go -out ../asm_vrsqrtss_128.s -stubs ../stub_vrsqrtss_128.go -pkg rsqrtss. DO NOT EDIT.

#include "textflag.h"

// func vrsqrtss128(vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vrsqrtss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal square root of scalar single precision value using VEX encoding
	VRSQRTSS X0, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
