// Code generated by command: go run asm_rsqrtss_128.go -out ../asm_rsqrtss_128.s -stubs ../stub_rsqrtss_128.go -pkg rsqrtss. DO NOT EDIT.

package rsqrtss

func rsqrtss128(vals *[4]float32, ret *[4]float32)
