// Code generated by command: go run asm_vrsqrtss_128.go -out ../asm_vrsqrtss_128.s -stubs ../stub_vrsqrtss_128.go -pkg rsqrtss. DO NOT EDIT.

package rsqrtss

func vrsqrtss128(vals *[4]float32, ret *[4]float32)
