// Code generated by command: go run asm_vpsllvw_256.go -out ../asm_vpsllvw_256.s -stubs ../stub_vpsllvw_256.go -pkg vpsllvw. DO NOT EDIT.

#include "textflag.h"

// func vpsllvw256(vals *[16]uint16, shifts *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX512BW, AVX512VL
TEXT ·vpsllvw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPSLLVW: shift packed doubleword integers in vals left by variable counts in shifts
	VPSLLVW Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
