// Code generated by command: go run asm_vpsllvw_256.go -out ../asm_vpsllvw_256.s -stubs ../stub_vpsllvw_256.go -pkg vpsllvw. DO NOT EDIT.

package vpsllvw

func vpsllvw256(vals *[16]uint16, shifts *[16]uint16, ret *[16]uint16)
