// Code generated by command: go run asm_vpsllvw_128.go -out ../asm_vpsllvw_128.s -stubs ../stub_vpsllvw_128.go -pkg vpsllvw. DO NOT EDIT.

package vpsllvw

func vpsllvw128(vals *[8]uint16, shifts *[8]uint16, ret *[8]uint16)
