// Code generated by command: go run asm_vmaxps_128.go -out ../asm_vmaxps_128.s -stubs ../stub_vmaxps_128.go -pkg maxps. DO NOT EDIT.

package maxps

func vmaxps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
