// Code generated by command: go run asm_maxps_128.go -out ../asm_maxps_128.s -stubs ../stub_maxps_128.go -pkg maxps. DO NOT EDIT.

package maxps

func maxps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
