// Code generated by command: go run asm_vmaxps_256.go -out ../asm_vmaxps_256.s -stubs ../stub_vmaxps_256.go -pkg maxps. DO NOT EDIT.

package maxps

func vmaxps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
