// Code generated by command: go run asm_vaddsubpd_256.go -out ../asm_vaddsubpd_256.s -stubs ../stub_vaddsubpd_256.go -pkg vaddsubpd. DO NOT EDIT.

#include "textflag.h"

// func vaddsubpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vaddsubpd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQU (AX), Y0

	// Load vals2 into YMM register
	VMOVDQU (CX), Y1

	// Execute the instruction being demonstrated
	VADDSUBPD Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQU Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
