// Code generated by command: go run asm_vaddsubpd_256.go -out ../asm_vaddsubpd_256.s -stubs ../stub_vaddsubpd_256.go -pkg vaddsubpd. DO NOT EDIT.

package vaddsubpd

func vaddsubpd256(vals1 *[4]float64, vals2 *[4]float64, ret *[4]float64)
