// Code generated by command: go run asm_vpermq_256_identity.go -out ../asm_vpermq_256_identity.s -stubs ../stub_vpermq_256_identity.go -pkg vpermq. DO NOT EDIT.

#include "textflag.h"

// func vpermq256Identity(vals *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpermq256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM register
	VMOVDQA (AX), Y0

	// VPERMQ identity: imm8=0xE4 selects indices 0,1,2,3
	VPERMQ $0xe4, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
