// Code generated by command: go run asm_vpermq_256_all_zeros.go -out ../asm_vpermq_256_all_zeros.s -stubs ../stub_vpermq_256_all_zeros.go -pkg vpermq. DO NOT EDIT.

#include "textflag.h"

// func vpermq256All_zeros(vals *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpermq256All_zeros(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM register
	VMOVDQA (AX), Y0

	// VPERMQ all zeros: imm8=0x00 selects index 0 for all outputs
	VPERMQ $0x00, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
