// Code generated by command: go run asm_vpermq_256_reverse.go -out ../asm_vpermq_256_reverse.s -stubs ../stub_vpermq_256_reverse.go -pkg vpermq. DO NOT EDIT.

#include "textflag.h"

// func vpermq256Reverse(vals *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpermq256Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM register
	VMOVDQA (AX), Y0

	// VPERMQ reverse: imm8=0x1B selects indices 3,2,1,0
	VPERMQ $0x1b, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
