// Code generated by command: go run asm_vpermq_256_all_ones.go -out ../asm_vpermq_256_all_ones.s -stubs ../stub_vpermq_256_all_ones.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256All_ones(vals *[4]uint64, ret *[4]uint64)
