// Code generated by command: go run asm_vpermq_256_reverse.go -out ../asm_vpermq_256_reverse.s -stubs ../stub_vpermq_256_reverse.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256Reverse(vals *[4]uint64, ret *[4]uint64)
