// Code generated by command: go run asm_vpermq_256_all_zeros.go -out ../asm_vpermq_256_all_zeros.s -stubs ../stub_vpermq_256_all_zeros.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256All_zeros(vals *[4]uint64, ret *[4]uint64)
