// Code generated by command: go run asm_vpermq_256_all_threes.go -out ../asm_vpermq_256_all_threes.s -stubs ../stub_vpermq_256_all_threes.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256All_threes(vals *[4]uint64, ret *[4]uint64)
