// Code generated by command: go run asm_vpermq_256_all_twos.go -out ../asm_vpermq_256_all_twos.s -stubs ../stub_vpermq_256_all_twos.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256All_twos(vals *[4]uint64, ret *[4]uint64)
