// Code generated by command: go run asm_vpermq_256_identity.go -out ../asm_vpermq_256_identity.s -stubs ../stub_vpermq_256_identity.go -pkg vpermq. DO NOT EDIT.

package vpermq

func vpermq256Identity(vals *[4]uint64, ret *[4]uint64)
