// Code generated by command: go run asm_vpermps_256.go -out ../asm_vpermps_256.s -stubs ../stub_vpermps_256.go -pkg vpermps. DO NOT EDIT.

#include "textflag.h"

// func vpermps256(vals *[8]float32, control *[8]uint32, ret *[8]float32)
// Requires: AVX, AVX2
TEXT ·vpermps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load control and source into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERMPS: permute packed single-precision floats with per-lane dword indices
	VPERMPS Y0, Y1, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
