// Code generated by command: go run asm_vpermps_256.go -out ../asm_vpermps_256.s -stubs ../stub_vpermps_256.go -pkg vpermps. DO NOT EDIT.

package vpermps

func vpermps256(vals *[8]float32, control *[8]uint32, ret *[8]float32)
