// Code generated by command: go run asm_vandnps_256.go -out ../asm_vandnps_256.s -stubs ../stub_vandnps_256.go -pkg andnps. DO NOT EDIT.

package andnps

func vandnps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
