// Code generated by command: go run asm_vandnps_128.go -out ../asm_vandnps_128.s -stubs ../stub_vandnps_128.go -pkg andnps. DO NOT EDIT.

package andnps

func vandnps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
