// Code generated by command: go run asm_andnps_128.go -out ../asm_andnps_128.s -stubs ../stub_andnps_128.go -pkg andnps. DO NOT EDIT.

package andnps

func andnps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
