// Code generated by command: go run asm_vpermilpd_256_identity.go -out ../asm_vpermilpd_256_identity.s -stubs ../stub_vpermilpd_256_identity.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd256Identity(vals *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vpermilpd256Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPD imm8=0xE4 per 128-bit lane: identity mapping
	VPERMILPD $0xe4, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
