// Code generated by command: go run asm_vpermilpd_256.go -out ../asm_vpermilpd_256.s -stubs ../stub_vpermilpd_256.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd256(vals *[4]float64, control *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vpermilpd256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source and control into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VPERMILPD with control register (per-lane 2-bit selectors, per 128-bit lane)
	VPERMILPD Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// Return from function
	RET
