// Code generated by command: go run asm_vpermilpd_256_all_one.go -out ../asm_vpermilpd_256_all_one.s -stubs ../stub_vpermilpd_256_all_one.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd256All_one(vals *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vpermilpd256All_one(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPD imm8=0x55 per 128-bit lane: broadcast lane1 element
	VPERMILPD $0x55, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// Return from function
	RET
