// Code generated by command: go run asm_vpermilpd_128_identity.go -out ../asm_vpermilpd_128_identity.s -stubs ../stub_vpermilpd_128_identity.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd128Identity(vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vpermilpd128Identity(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPD imm8=0xE4 (identity): dst = [a0 a1]
	VPERMILPD $0xe4, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
