// Code generated by command: go run asm_vpermilpd_128.go -out ../asm_vpermilpd_128.s -stubs ../stub_vpermilpd_128.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd128(vals *[2]float64, control *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vpermilpd128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ control+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load source and control into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPERMILPD with control register (per-lane 2-bit selectors)
	VPERMILPD X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
