// Code generated by command: go run asm_vpermilpd_128_all_zero.go -out ../asm_vpermilpd_128_all_zero.s -stubs ../stub_vpermilpd_128_all_zero.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd128All_zero(vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vpermilpd128All_zero(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPD imm8=0x00: broadcast a0 to all lanes
	VPERMILPD $0x00, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
