// Code generated by command: go run asm_vpermilpd_128_reverse.go -out ../asm_vpermilpd_128_reverse.s -stubs ../stub_vpermilpd_128_reverse.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd128Reverse(vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vpermilpd128Reverse(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into XMM
	VMOVDQA (AX), X0

	// VPERMILPD imm8=0x1B: reverse [a3 a2 a1 a0]
	VPERMILPD $0x1b, X0, X0

	// Store result
	VMOVDQA X0, (CX)

	// Return from function
	RET
