// Code generated by command: go run asm_vpermilpd_256_all_zero.go -out ../asm_vpermilpd_256_all_zero.s -stubs ../stub_vpermilpd_256_all_zero.go -pkg vpermilpd. DO NOT EDIT.

#include "textflag.h"

// func vpermilpd256All_zero(vals *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vpermilpd256All_zero(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load source into YMM
	VMOVDQA (AX), Y0

	// VPERMILPD imm8=0x00 per 128-bit lane: broadcast lane0 element
	VPERMILPD $0x00, Y0, Y0

	// Store result
	VMOVDQA Y0, (CX)

	// YMM/ZMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
