// Code generated by command: go run asm_vpermilpd_128_reverse.go -out ../asm_vpermilpd_128_reverse.s -stubs ../stub_vpermilpd_128_reverse.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd128Reverse(vals *[2]float64, ret *[2]float64)
