// Code generated by command: go run asm_vpermilpd_128_all_one.go -out ../asm_vpermilpd_128_all_one.s -stubs ../stub_vpermilpd_128_all_one.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd128All_one(vals *[2]float64, ret *[2]float64)
