// Code generated by command: go run asm_vpermilpd_256_all_zero.go -out ../asm_vpermilpd_256_all_zero.s -stubs ../stub_vpermilpd_256_all_zero.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd256All_zero(vals *[4]float64, ret *[4]float64)
