// Code generated by command: go run asm_vpermilpd_256.go -out ../asm_vpermilpd_256.s -stubs ../stub_vpermilpd_256.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd256(vals *[4]float64, control *[4]float64, ret *[4]float64)
