// Code generated by command: go run asm_vpermilpd_256_identity.go -out ../asm_vpermilpd_256_identity.s -stubs ../stub_vpermilpd_256_identity.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd256Identity(vals *[4]float64, ret *[4]float64)
