// Code generated by command: go run asm_vpermilpd_128.go -out ../asm_vpermilpd_128.s -stubs ../stub_vpermilpd_128.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd128(vals *[2]float64, control *[2]float64, ret *[2]float64)
