// Code generated by command: go run asm_vpermilpd_256_all_one.go -out ../asm_vpermilpd_256_all_one.s -stubs ../stub_vpermilpd_256_all_one.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd256All_one(vals *[4]float64, ret *[4]float64)
