// Code generated by command: go run asm_vpermilpd_256_reverse.go -out ../asm_vpermilpd_256_reverse.s -stubs ../stub_vpermilpd_256_reverse.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd256Reverse(vals *[4]float64, ret *[4]float64)
