// Code generated by command: go run asm_vpermilpd_128_identity.go -out ../asm_vpermilpd_128_identity.s -stubs ../stub_vpermilpd_128_identity.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd128Identity(vals *[2]float64, ret *[2]float64)
