// Code generated by command: go run asm_vpermilpd_128_all_zero.go -out ../asm_vpermilpd_128_all_zero.s -stubs ../stub_vpermilpd_128_all_zero.go -pkg vpermilpd. DO NOT EDIT.

package vpermilpd

func vpermilpd128All_zero(vals *[2]float64, ret *[2]float64)
