// Code generated by command: go run asm_vpslld_256.go -out ../asm_vpslld_256.s -stubs ../stub_vpslld_256.go -pkg psll. DO NOT EDIT.

#include "textflag.h"

// func vpslld256(vals *[8]uint32, shift *[4]uint64, ret *[8]uint32)
// Requires: AVX, AVX2
TEXT ·vpslld256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), X1

	// Logical left shift packed dwords by per-lane counts (register)
	VPSLLD X1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
