// Code generated by command: go run asm_vpsllq_128.go -out ../asm_vpsllq_128.s -stubs ../stub_vpsllq_128.go -pkg psll. DO NOT EDIT.

#include "textflag.h"

// func vpsllq128(vals *[2]uint64, shift *[2]uint64, ret *[2]uint64)
// Requires: AVX
TEXT ·vpsllq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Logical left shift packed qwords by per-lane counts (register)
	VPSLLQ X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
