// Code generated by command: go run asm_vpsllq_256.go -out ../asm_vpsllq_256.s -stubs ../stub_vpsllq_256.go -pkg psll. DO NOT EDIT.

#include "textflag.h"

// func vpsllq256(vals *[4]uint64, shift *[4]uint64, ret *[4]uint64)
// Requires: AVX, AVX2
TEXT ·vpsllq256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shift+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load values and shift counts into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), X1

	// Logical left shift packed qwords by per-lane counts (register)
	VPSLLQ X1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
