// Code generated by command: go run asm_vpsllw_256.go -out ../asm_vpsllw_256.s -stubs ../stub_vpsllw_256.go -pkg psll. DO NOT EDIT.

package psll

func vpsllw256(vals *[16]uint16, shift *[4]uint64, ret *[16]uint16)
