// Code generated by command: go run asm_vpslld_256.go -out ../asm_vpslld_256.s -stubs ../stub_vpslld_256.go -pkg psll. DO NOT EDIT.

package psll

func vpslld256(vals *[8]uint32, shift *[4]uint64, ret *[8]uint32)
