// Code generated by command: go run asm_vpslld_128.go -out ../asm_vpslld_128.s -stubs ../stub_vpslld_128.go -pkg psll. DO NOT EDIT.

package psll

func vpslld128(vals *[4]uint32, shift *[2]uint64, ret *[4]uint32)
