// Code generated by command: go run asm_vpsllq_128.go -out ../asm_vpsllq_128.s -stubs ../stub_vpsllq_128.go -pkg psll. DO NOT EDIT.

package psll

func vpsllq128(vals *[2]uint64, shift *[2]uint64, ret *[2]uint64)
