// Code generated by command: go run asm_vpsllq_256.go -out ../asm_vpsllq_256.s -stubs ../stub_vpsllq_256.go -pkg psll. DO NOT EDIT.

package psll

func vpsllq256(vals *[4]uint64, shift *[4]uint64, ret *[4]uint64)
