// Code generated by command: go run asm_vpsllw_128.go -out ../asm_vpsllw_128.s -stubs ../stub_vpsllw_128.go -pkg psll. DO NOT EDIT.

package psll

func vpsllw128(vals *[8]uint16, shift *[2]uint64, ret *[8]uint16)
