// Code generated by command: go run asm_vroundss_128_two.go -out ../asm_vroundss_128_two.s -stubs ../stub_vroundss_128_two.go -pkg rounds. DO NOT EDIT.

#include "textflag.h"

// func vroundss128Two(base *[4]float32, vals *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vroundss128Two(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ vals+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and vals into XMM registers
	VMOVAPS (AX), X0
	VMOVAPS (CX), X1

	// Round scalar single imm8=2 (ceil), copy upper lanes from base
	VROUNDSS $0x02, X1, X0, X0

	// Write results into return memory address
	VMOVAPS X0, (DX)

	// Return from function
	RET
