// Code generated by command: go run asm_vroundsd_128_zero.go -out ../asm_vroundsd_128_zero.s -stubs ../stub_vroundsd_128_zero.go -pkg rounds. DO NOT EDIT.

#include "textflag.h"

// func vroundsd128Zero(base *[2]float64, vals *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vroundsd128Zero(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ vals+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and vals into XMM registers
	VMOVAPD (AX), X0
	VMOVAPD (CX), X1

	// Round scalar double imm8=0 (nearest), copy upper lane from base
	VROUNDSD $0x00, X1, X0, X0

	// Write results into return memory address
	VMOVAPD X0, (DX)

	// Return from function
	RET
