// Code generated by command: go run asm_vroundss_128_one.go -out ../asm_vroundss_128_one.s -stubs ../stub_vroundss_128_one.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundss128One(base *[4]float32, vals *[4]float32, ret *[4]float32)
