// Code generated by command: go run asm_vroundss_128_zero.go -out ../asm_vroundss_128_zero.s -stubs ../stub_vroundss_128_zero.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundss128Zero(base *[4]float32, vals *[4]float32, ret *[4]float32)
