// Code generated by command: go run asm_vroundss_128_two.go -out ../asm_vroundss_128_two.s -stubs ../stub_vroundss_128_two.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundss128Two(base *[4]float32, vals *[4]float32, ret *[4]float32)
