// Code generated by command: go run asm_vroundss_128_three.go -out ../asm_vroundss_128_three.s -stubs ../stub_vroundss_128_three.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundss128Three(base *[4]float32, vals *[4]float32, ret *[4]float32)
