// Code generated by command: go run asm_vroundsd_128_three.go -out ../asm_vroundsd_128_three.s -stubs ../stub_vroundsd_128_three.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundsd128Three(base *[2]float64, vals *[2]float64, ret *[2]float64)
