// Code generated by command: go run asm_vroundsd_128_two.go -out ../asm_vroundsd_128_two.s -stubs ../stub_vroundsd_128_two.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundsd128Two(base *[2]float64, vals *[2]float64, ret *[2]float64)
