// Code generated by command: go run asm_vroundsd_128_one.go -out ../asm_vroundsd_128_one.s -stubs ../stub_vroundsd_128_one.go -pkg rounds. DO NOT EDIT.

package rounds

func vroundsd128One(base *[2]float64, vals *[2]float64, ret *[2]float64)
