// Code generated by command: go run asm_vpmulhrsw_128.go -out ../asm_vpmulhrsw_128.s -stubs ../stub_vpmulhrsw_128.go -pkg vpmulhrsw. DO NOT EDIT.

#include "textflag.h"

// func vpmulhrsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
// Requires: AVX
TEXT ·vpmulhrsw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQU (AX), X0

	// Load vals2 into XMM register
	VMOVDQU (CX), X1

	// Execute the instruction being demonstrated
	VPMULHRSW X0, X1, X0

	// Write results into return memory address
	VMOVDQU X0, (DX)

	// Return from function
	RET
