// Code generated by command: go run asm_vpmulhrsw_128.go -out ../asm_vpmulhrsw_128.s -stubs ../stub_vpmulhrsw_128.go -pkg vpmulhrsw. DO NOT EDIT.

package vpmulhrsw

func vpmulhrsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
