// Code generated by command: go run asm_vpmulhw_256.go -out ../asm_vpmulhw_256.s -stubs ../stub_vpmulhw_256.go -pkg pmulhw. DO NOT EDIT.

#include "textflag.h"

// func vpmulhw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpmulhw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// Multiply packed signed 16-bit integers; keep high 16 bits of 32-bit products
	VPMULHW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Clear upper halves after YMM usage
	VZEROUPPER

	// Return from function
	RET
