// Code generated by command: go run asm_vpmulhw_128.go -out ../asm_vpmulhw_128.s -stubs ../stub_vpmulhw_128.go -pkg pmulhw. DO NOT EDIT.

#include "textflag.h"

// func vpmulhw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
// Requires: AVX
TEXT ·vpmulhw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 and vals2 into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Multiply packed signed 16-bit integers; keep high 16 bits of 32-bit products
	VPMULHW X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
