// Code generated by command: go run asm_vpmulhw_128.go -out ../asm_vpmulhw_128.s -stubs ../stub_vpmulhw_128.go -pkg pmulhw. DO NOT EDIT.

package pmulhw

func vpmulhw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
