// Code generated by command: go run asm_vpmulhw_256.go -out ../asm_vpmulhw_256.s -stubs ../stub_vpmulhw_256.go -pkg pmulhw. DO NOT EDIT.

package pmulhw

func vpmulhw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
