// Code generated by command: go run asm_vpsrlvq_128.go -out ../asm_vpsrlvq_128.s -stubs ../stub_vpsrlvq_128.go -pkg vpsrlvq. DO NOT EDIT.

#include "textflag.h"

// func vpsrlvq128(vals *[2]uint64, shifts *[2]uint64, ret *[2]uint64)
// Requires: AVX, AVX2
TEXT ·vpsrlvq128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals+0(FP), AX
	MOVQ shifts+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals and shifts into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VPSRLVQ: shift packed quadword integers in vals right by variable counts in shifts
	VPSRLVQ X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
