// Code generated by command: go run asm_vpsrlvq_128.go -out ../asm_vpsrlvq_128.s -stubs ../stub_vpsrlvq_128.go -pkg vpsrlvq. DO NOT EDIT.

package vpsrlvq

func vpsrlvq128(vals *[2]uint64, shifts *[2]uint64, ret *[2]uint64)
