// Code generated by command: go run asm_vpsrlvq_256.go -out ../asm_vpsrlvq_256.s -stubs ../stub_vpsrlvq_256.go -pkg vpsrlvq. DO NOT EDIT.

package vpsrlvq

func vpsrlvq256(vals *[4]uint64, shifts *[4]uint64, ret *[4]uint64)
