// Code generated by command: go run asm_vgatherqpd_128.go -out ../asm_vgatherqpd_128.s -stubs ../stub_vgatherqpd_128.go -pkg vgatherqdp. DO NOT EDIT.

#include "textflag.h"

// func vgatherqpd128(base *[8]float64, index *[2]uint64, mask *[2]float64, ret *[2]float64)
// Requires: AVX, AVX2
TEXT ·vgatherqpd128(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 64-bit indices into XMM register (lower 2 qwords used)
	VMOVDQA (CX), X0

	// Load mask into XMM register
	VMOVDQA (DX), X1

	// Load destination/src vector
	VMOVDQA (BX), X2

	// Gather two f64 elements using 64-bit indices; scale=8 for f64 element size
	VGATHERQPD X1, (AX)(X0*8), X2

	// Store result vector
	VMOVDQA X2, (BX)

	// Return
	RET
