// Code generated by command: go run asm_vgatherqpd_256.go -out ../asm_vgatherqpd_256.s -stubs ../stub_vgatherqpd_256.go -pkg vgatherqdp. DO NOT EDIT.

#include "textflag.h"

// func vgatherqpd256(base *[8]float64, index *[4]uint64, mask *[4]float64, ret *[4]float64)
// Requires: AVX, AVX2
TEXT ·vgatherqpd256(SB), NOSPLIT, $0-32
	// Load parameters
	MOVQ base+0(FP), AX
	MOVQ index+8(FP), CX
	MOVQ mask+16(FP), DX
	MOVQ ret+24(FP), BX

	// Load 64-bit indices into YMM register (lower 4 qwords used)
	VMOVDQA (CX), Y0

	// Load mask into YMM register
	VMOVDQA (DX), Y1

	// Load destination/src vector
	VMOVDQA (BX), Y2

	// Gather four f64 elements using 64-bit indices; scale=8 for f64 element size
	VGATHERQPD Y1, (AX)(Y0*8), Y2

	// Store result vector
	VMOVDQA Y2, (BX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return
	RET
