// Code generated by command: go run asm_vgatherqpd_128.go -out ../asm_vgatherqpd_128.s -stubs ../stub_vgatherqpd_128.go -pkg vgatherqdp. DO NOT EDIT.

package vgatherqdp

func vgatherqpd128(base *[8]float64, index *[2]uint64, mask *[2]float64, ret *[2]float64)
