// Code generated by command: go run asm_vgatherqpd_256.go -out ../asm_vgatherqpd_256.s -stubs ../stub_vgatherqpd_256.go -pkg vgatherqdp. DO NOT EDIT.

package vgatherqdp

func vgatherqpd256(base *[8]float64, index *[4]uint64, mask *[4]float64, ret *[4]float64)
