// Code generated by command: go run asm_vxorps_256.go -out ../asm_vxorps_256.s -stubs ../stub_vxorps_256.go -pkg xorps. DO NOT EDIT.

#include "textflag.h"

// func vxorps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
// Requires: AVX
TEXT ·vxorps256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Bitwise XOR with VEX encoding (per 128-bit lane)
	VXORPS Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
