// Code generated by command: go run asm_xorps_128.go -out ../asm_xorps_128.s -stubs ../stub_xorps_128.go -pkg xorps. DO NOT EDIT.

package xorps

func xorps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
