// Code generated by command: go run asm_vxorps_128.go -out ../asm_vxorps_128.s -stubs ../stub_vxorps_128.go -pkg xorps. DO NOT EDIT.

package xorps

func vxorps128(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
