// Code generated by command: go run asm_vxorps_256.go -out ../asm_vxorps_256.s -stubs ../stub_vxorps_256.go -pkg xorps. DO NOT EDIT.

package xorps

func vxorps256(vals1 *[8]float32, vals2 *[8]float32, ret *[8]float32)
