// Code generated by command: go run asm_vblendpd_256_even.go -out ../asm_vblendpd_256_even.s -stubs ../stub_vblendpd_256_even.go -pkg blendpd. DO NOT EDIT.

#include "textflag.h"

// func vblendpd256Even(base *[4]float64, blend *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vblendpd256Even(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VBLENDPD 256: imm=0x05 selects even lanes (0,2) from blend; others from base
	VBLENDPD $0x05, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
