// Code generated by command: go run asm_vblendpd_256_all.go -out ../asm_vblendpd_256_all.s -stubs ../stub_vblendpd_256_all.go -pkg blendpd. DO NOT EDIT.

#include "textflag.h"

// func vblendpd256All(base *[4]float64, blend *[4]float64, ret *[4]float64)
// Requires: AVX
TEXT ·vblendpd256All(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into YMM registers
	VMOVDQA (AX), Y0
	VMOVDQA (CX), Y1

	// VBLENDPD 256: imm=0x0F selects all lanes from blend
	VBLENDPD $0x0f, Y1, Y0, Y0

	// Store result
	VMOVDQA Y0, (DX)

	// YMM processing complete, clear upper half of YMM registers
	VZEROUPPER

	// Return from function
	RET
