// Code generated by command: go run asm_vblendpd_128_all.go -out ../asm_vblendpd_128_all.s -stubs ../stub_vblendpd_128_all.go -pkg blendpd. DO NOT EDIT.

#include "textflag.h"

// func vblendpd128All(base *[2]float64, blend *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vblendpd128All(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VBLENDPD 128: imm=0x03 selects both lanes from blend
	VBLENDPD $0x03, X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
