// Code generated by command: go run asm_vblendpd_128_even.go -out ../asm_vblendpd_128_even.s -stubs ../stub_vblendpd_128_even.go -pkg blendpd. DO NOT EDIT.

#include "textflag.h"

// func vblendpd128Even(base *[2]float64, blend *[2]float64, ret *[2]float64)
// Requires: AVX
TEXT ·vblendpd128Even(SB), NOSPLIT, $0-24
	// load params
	MOVQ base+0(FP), AX
	MOVQ blend+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load base and blend into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// VBLENDPD 128: imm=0x01 selects lane 0 (even) from blend; lane 1 from base
	VBLENDPD $0x01, X1, X0, X0

	// Store result
	VMOVDQA X0, (DX)

	// Return from function
	RET
