// Code generated by command: go run asm_vblendpd_128_even.go -out ../asm_vblendpd_128_even.s -stubs ../stub_vblendpd_128_even.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd128Even(base *[2]float64, blend *[2]float64, ret *[2]float64)
