// Code generated by command: go run asm_vblendpd_128_high_half.go -out ../asm_vblendpd_128_high_half.s -stubs ../stub_vblendpd_128_high_half.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd128High_half(base *[2]float64, blend *[2]float64, ret *[2]float64)
