// Code generated by command: go run asm_vblendpd_128_none.go -out ../asm_vblendpd_128_none.s -stubs ../stub_vblendpd_128_none.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd128None(base *[2]float64, blend *[2]float64, ret *[2]float64)
