// Code generated by command: go run asm_vblendpd_256_low_half.go -out ../asm_vblendpd_256_low_half.s -stubs ../stub_vblendpd_256_low_half.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd256Low_half(base *[4]float64, blend *[4]float64, ret *[4]float64)
