// Code generated by command: go run asm_vblendpd_256_all.go -out ../asm_vblendpd_256_all.s -stubs ../stub_vblendpd_256_all.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd256All(base *[4]float64, blend *[4]float64, ret *[4]float64)
