// Code generated by command: go run asm_vblendpd_256_even.go -out ../asm_vblendpd_256_even.s -stubs ../stub_vblendpd_256_even.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd256Even(base *[4]float64, blend *[4]float64, ret *[4]float64)
