// Code generated by command: go run asm_vblendpd_128_all.go -out ../asm_vblendpd_128_all.s -stubs ../stub_vblendpd_128_all.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd128All(base *[2]float64, blend *[2]float64, ret *[2]float64)
