// Code generated by command: go run asm_vblendpd_256_none.go -out ../asm_vblendpd_256_none.s -stubs ../stub_vblendpd_256_none.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd256None(base *[4]float64, blend *[4]float64, ret *[4]float64)
