// Code generated by command: go run asm_vblendpd_128_odd.go -out ../asm_vblendpd_128_odd.s -stubs ../stub_vblendpd_128_odd.go -pkg blendpd. DO NOT EDIT.

package blendpd

func vblendpd128Odd(base *[2]float64, blend *[2]float64, ret *[2]float64)
