// Code generated by command: go run asm_vpabgw_256.go -out ../asm_vpabgw_256.s -stubs ../stub_vpabgw_256.go -pkg pavgw. DO NOT EDIT.

#include "textflag.h"

// func vpabgw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
// Requires: AVX, AVX2
TEXT ·vpabgw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Average packed unsigned words with VEX (per 128-bit lane)
	VPAVGW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
