// Code generated by command: go run asm_vpabgw_256.go -out ../asm_vpabgw_256.s -stubs ../stub_vpabgw_256.go -pkg pavgw. DO NOT EDIT.

package pavgw

func vpabgw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
