// Code generated by command: go run asm_vpabgw_128.go -out ../asm_vpabgw_128.s -stubs ../stub_vpabgw_128.go -pkg pavgw. DO NOT EDIT.

package pavgw

func vpabgw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
