// Code generated by command: go run asm_pabgw_128.go -out ../asm_pabgw_128.s -stubs ../stub_pabgw_128.go -pkg pavgw. DO NOT EDIT.

package pavgw

func pabgw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
