// Code generated by command: go run asm_rcpss_128.go -out ../asm_rcpss_128.s -stubs ../stub_rcpss_128.go -pkg rcpss. DO NOT EDIT.

#include "textflag.h"

// func rcpss128(vals *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·rcpss128(SB), NOSPLIT, $0-16
	// load params
	MOVQ vals+0(FP), AX
	MOVQ ret+8(FP), CX

	// Load vals into XMM register
	VMOVDQA (AX), X0

	// Compute reciprocal of scalar single precision value (lowest 32 bits)
	RCPSS X0, X0

	// Write results into return memory address
	VMOVDQA X0, (CX)

	// Return from function
	RET
