// Code generated by command: go run asm_vrcpss_128.go -out ../asm_vrcpss_128.s -stubs ../stub_vrcpss_128.go -pkg rcpss. DO NOT EDIT.

package rcpss

func vrcpss128(vals *[4]float32, ret *[4]float32)
