// Code generated by command: go run asm_vpmaxub_128.go -out ../asm_vpmaxub_128.s -stubs ../stub_vpmaxub_128.go -pkg pmaxu. DO NOT EDIT.

#include "textflag.h"

// func vpmaxub128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
// Requires: AVX
TEXT ·vpmaxub128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load into XMM registers
	VMOVDQA (AX), X0
	VMOVDQA (CX), X1

	// Unsigned max of packed bytes
	VPMAXUB X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
