// Code generated by command: go run asm_vpmaxub_128.go -out ../asm_vpmaxub_128.s -stubs ../stub_vpmaxub_128.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxub128(vals1 *[16]uint8, vals2 *[16]uint8, ret *[16]uint8)
