// Code generated by command: go run asm_vpmaxub_256.go -out ../asm_vpmaxub_256.s -stubs ../stub_vpmaxub_256.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxub256(vals1 *[32]uint8, vals2 *[32]uint8, ret *[32]uint8)
