// Code generated by command: go run asm_vpmaxuw_256.go -out ../asm_vpmaxuw_256.s -stubs ../stub_vpmaxuw_256.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxuw256(vals1 *[16]uint16, vals2 *[16]uint16, ret *[16]uint16)
