// Code generated by command: go run asm_vpmaxud_256.go -out ../asm_vpmaxud_256.s -stubs ../stub_vpmaxud_256.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxud256(vals1 *[8]uint32, vals2 *[8]uint32, ret *[8]uint32)
