// Code generated by command: go run asm_vpmaxud_128.go -out ../asm_vpmaxud_128.s -stubs ../stub_vpmaxud_128.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxud128(vals1 *[4]uint32, vals2 *[4]uint32, ret *[4]uint32)
