// Code generated by command: go run asm_vpmaxuw_128.go -out ../asm_vpmaxuw_128.s -stubs ../stub_vpmaxuw_128.go -pkg pmaxu. DO NOT EDIT.

package pmaxu

func vpmaxuw128(vals1 *[8]uint16, vals2 *[8]uint16, ret *[8]uint16)
