package register

import (
	"fmt"
)

type changeBroadcaster struct {
	simdsize  int
	active    bool
	receivers []*RegisterParts
}

func newChangeBroadcaster(simdsize int) *changeBroadcaster {
	return &changeBroadcaster{
		simdsize:  simdsize,
		active:    true,
		receivers: []*RegisterParts{},
	}
}

func (b *changeBroadcaster) addReceiver(r *RegisterParts) {
	b.receivers = append(b.receivers, r)
}

func (b *changeBroadcaster) broadcastZeros() {
	// Resets all parts to zero
	b.broadcastChange(make([]byte, b.simdsize/8))
}

func (b *changeBroadcaster) broadcastChange(bytes []byte) {
	if !b.active {
		return
	}

	for _, r := range b.receivers {
		b.writeDataChange(bytes, r)
	}
}

func (b *changeBroadcaster) writeDataChange(bytes []byte, r *RegisterParts) {
	if (len(bytes) * 8) != b.simdsize {
		panic(fmt.Errorf("Bad data update, received %d bits, but need %d", len(bytes)*8, b.simdsize))
	}
	partsCount := r.dataParts()
	fmt.Printf("%s received data change %0.8b\n\n", r.describe(), bytes)

	if len(bytes)%partsCount != 0 {
		panic(fmt.Errorf("%s update with %d bytes, not cleanly divisible by %d parts", r.describe(), len(bytes), partsCount))
	}

	// Disable change eventbroadcasts generated by this update, this prevents ping/pong updates
	b.deactivate()
	defer b.activate()

	bytesPer := len(bytes) / partsCount
	for i := range partsCount {
		idx := i * bytesPer
		chunk := bytes[idx : idx+bytesPer]
		r.setPart(i, chunk)
	}
}

func (b *changeBroadcaster) activate() {
	b.active = true
}

func (b *changeBroadcaster) deactivate() {
	b.active = false
}
