package register

import "github.com/fmstephe/simd_explorer/pkg/assembly"

type changeBroadcaster struct {
	inst            assembly.Instruction
	active          bool
	inputReceivers  []*RegisterParts
	outputReceivers []*RegisterParts
}

func newChangeBroadcaster(inst assembly.Instruction) *changeBroadcaster {
	return &changeBroadcaster{
		inst:            inst,
		active:          true,
		inputReceivers:  []*RegisterParts{},
		outputReceivers: []*RegisterParts{},
	}
}

func (b *changeBroadcaster) addInputReceiver(r *RegisterParts) {
	b.inputReceivers = append(b.inputReceivers, r)
}

func (b *changeBroadcaster) addOutputReceiver(r *RegisterParts) {
	b.outputReceivers = append(b.outputReceivers, r)
}

func (b *changeBroadcaster) broadcastZeros() {
	// Resets all parts to zero
	b.broadcastChange(make([]byte, b.inst.InputSize()/8))
}

func (b *changeBroadcaster) broadcastChange(input []byte) {
	if !b.active {
		return
	}

	// Disable change eventbroadcasts generated by this update, this prevents ping/pong updates
	b.deactivate()
	defer b.activate()

	output := b.inst.Run(input)

	for _, r := range b.inputReceivers {
		r.setData(input)
	}

	for _, r := range b.outputReceivers {
		r.setData(output)
	}
}

func (b *changeBroadcaster) activate() {
	b.active = true
}

func (b *changeBroadcaster) deactivate() {
	b.active = false
}
