package register

import "github.com/fmstephe/simd_explorer/pkg/assembly"

type changeBroadcaster struct {
	inst      assembly.Instruction
	active    bool
	receivers []*UIRegister
}

func newChangeBroadcaster(inst assembly.Instruction) *changeBroadcaster {
	return &changeBroadcaster{
		inst:      inst,
		active:    true,
		receivers: []*UIRegister{},
	}
}

func (b *changeBroadcaster) addReceiver(r *UIRegister) {
	b.receivers = append(b.receivers, r)
}

func (b *changeBroadcaster) broadcastZeros() {
	// Resets all parts to zero
	inputSizes := b.inst.InputSizes()
	zeroVals := make([][]byte, len(inputSizes))
	for i, size := range inputSizes {
		zeroVals[i] = make([]byte, size/8)
	}
	b.broadcastChange(zeroVals)
}

func (b *changeBroadcaster) broadcastChange(inputs [][]byte) {
	if !b.active {
		return
	}

	// Disable change eventbroadcasts generated by this update, this prevents ping/pong updates
	b.deactivate()
	defer b.activate()

	output := b.inst.Run(inputs)

	for _, r := range b.receivers {
		r.setData(inputs, output)
	}
}

func (b *changeBroadcaster) activate() {
	b.active = true
}

func (b *changeBroadcaster) deactivate() {
	b.active = false
}
