// Code generated by command: go run asm_vcmpss_128_ord.go -out ../asm_vcmpss_128_ord.s -stubs ../stub_vcmpss_128_ord.go -pkg cmpss. DO NOT EDIT.

#include "textflag.h"

// func vcmpss128Ord(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX
TEXT ·vcmpss128Ord(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Compare scalar single precision values for ordered (lowest 32 bits)
	VCMPSS $0x07, X1, X0, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
