// Code generated by command: go run asm_cmpss_128_eq.go -out ../asm_cmpss_128_eq.s -stubs ../stub_cmpss_128_eq.go -pkg cmpss. DO NOT EDIT.

#include "textflag.h"

// func cmpss128Eq(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
// Requires: AVX, SSE
TEXT ·cmpss128Eq(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Compare scalar single precision values for equality (lowest 32 bits)
	CMPSS X1, X0, $0x00

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
