// Code generated by command: go run asm_cmpss_128_nle.go -out ../asm_cmpss_128_nle.s -stubs ../stub_cmpss_128_nle.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Nle(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
