// Code generated by command: go run asm_vcmpss_128_ord.go -out ../asm_vcmpss_128_ord.s -stubs ../stub_vcmpss_128_ord.go -pkg cmpss. DO NOT EDIT.

package cmpss

func vcmpss128Ord(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
