// Code generated by command: go run asm_cmpss_128_unord.go -out ../asm_cmpss_128_unord.s -stubs ../stub_cmpss_128_unord.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Unord(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
