// Code generated by command: go run asm_cmpss_128_lt.go -out ../asm_cmpss_128_lt.s -stubs ../stub_cmpss_128_lt.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Lt(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
