// Code generated by command: go run asm_cmpss_128_eq.go -out ../asm_cmpss_128_eq.s -stubs ../stub_cmpss_128_eq.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Eq(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
