// Code generated by command: go run asm_vcmpss_128_eq.go -out ../asm_vcmpss_128_eq.s -stubs ../stub_vcmpss_128_eq.go -pkg cmpss. DO NOT EDIT.

package cmpss

func vcmpss128Eq(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
