// Code generated by command: go run asm_vcmpss_128_le.go -out ../asm_vcmpss_128_le.s -stubs ../stub_vcmpss_128_le.go -pkg cmpss. DO NOT EDIT.

package cmpss

func vcmpss128Le(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
