// Code generated by command: go run asm_cmpss_128_nlt.go -out ../asm_cmpss_128_nlt.s -stubs ../stub_cmpss_128_nlt.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Nlt(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
