// Code generated by command: go run asm_cmpss_128_le.go -out ../asm_cmpss_128_le.s -stubs ../stub_cmpss_128_le.go -pkg cmpss. DO NOT EDIT.

package cmpss

func cmpss128Le(vals1 *[4]float32, vals2 *[4]float32, ret *[4]float32)
