// Code generated by command: go run asm_vpminsw_256.go -out ../asm_vpminsw_256.s -stubs ../stub_vpminsw_256.go -pkg pminsw. DO NOT EDIT.

#include "textflag.h"

// func vpminsw256(vals1 *[16]int16, vals2 *[16]int16, ret *[16]int16)
// Requires: AVX, AVX2
TEXT ·vpminsw256(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into YMM register
	VMOVDQA (AX), Y0

	// Load vals2 into YMM register
	VMOVDQA (CX), Y1

	// Packed signed word min per lane (VEX, per 128-bit lane)
	VPMINSW Y1, Y0, Y0

	// Write results into return memory address
	VMOVDQA Y0, (DX)

	// Return from function
	RET
