// Code generated by command: go run asm_pminsw_128.go -out ../asm_pminsw_128.s -stubs ../stub_pminsw_128.go -pkg pminsw. DO NOT EDIT.

#include "textflag.h"

// func pminsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
// Requires: AVX, SSE2
TEXT ·pminsw128(SB), NOSPLIT, $0-24
	// load params
	MOVQ vals1+0(FP), AX
	MOVQ vals2+8(FP), CX
	MOVQ ret+16(FP), DX

	// Load vals1 into XMM register
	VMOVDQA (AX), X0

	// Load vals2 into XMM register
	VMOVDQA (CX), X1

	// Packed signed word min per lane
	PMINSW X1, X0

	// Write results into return memory address
	VMOVDQA X0, (DX)

	// Return from function
	RET
