// Code generated by command: go run asm_pminsw_128.go -out ../asm_pminsw_128.s -stubs ../stub_pminsw_128.go -pkg pminsw. DO NOT EDIT.

package pminsw

func pminsw128(vals1 *[8]int16, vals2 *[8]int16, ret *[8]int16)
